### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by karndubey** [Netflix/conductor#1004]
While running the Main.java class in server module I am encountering following error:
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The method bind(Class<EventServiceImplBase>) from the type AbstractModule refers to the missing type EventServiceImplBase
	EventServiceGrpc cannot be resolved to a type
	The method bind(Class<MetadataServiceImplBase>) from the type AbstractModule refers to the missing type MetadataServiceImplBase
	MetadataServiceGrpc cannot be resolved to a type
	The method bind(Class<TaskServiceImplBase>) from the type AbstractModule refers to the missing type TaskServiceImplBase
	TaskServiceGrpc cannot be resolved to a type
	The method bind(Class<WorkflowServiceImplBase>) from the type AbstractModule refers to the missing type WorkflowServiceImplBase
	WorkflowServiceGrpc cannot be resolved to a type

	at com.netflix.conductor.grpc.server.GRPCModule.configure(GRPCModule.java:24)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at com.netflix.conductor.server.ServerModule.configure(ServerModule.java:46)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:53)

** Also  import com.netflix.conductor.grpc.EventServiceGrpc;
import com.netflix.conductor.grpc.EventServicePb;
import com.netflix.conductor.grpc.ProtoMapper;
import com.netflix.conductor.proto.EventHandlerPb; 
can't import above packages. Am I missing something while building the project??

**Comment by apanicker-nflx** [comment]
Please follow steps [here](https://netflix.github.io/conductor/intro/#start-local-server) to run the server locally.

**Comment by sunnygupta1890** [comment]
@apanicker-nflx this link is not working. Would you please paste a working link?

**Comment by apanicker-nflx** [comment]
Apologies for the broken link, please use this [link](https://netflix.github.io/conductor/architecture/#start-local-server). Also, please refer the complete documentation at [https://netflix.github.io/conductor/](https://netflix.github.io/conductor/).
