### ISSUE TITLE
Running unregistered task as part of Dynamic workflow

### ISSUE THREAD

**Issue by sujaysudheenda** [Netflix/conductor#1089]
Hi,

I am trying to follow the docs here https://netflix.github.io/conductor/configuration/systask/#dynamic-task

I want to execute Dynamic workflows by passing in proper JSON to the `POST /api/workflow` endpoint. Based on the docs, the above endpoint allows you to send-in unregistered workflows.
according to the docs:
>If the need arises to run a one-time workflow, and it doesn't make sense to register Task and Workflow definitions in Conductor Server, as it could change dynamically for each execution, dynamic workflow executions can be used.

I am unable to get this work and I this following error:

```
com.netflix.conductor.core.execution.TerminateWorkflowException: Invalid task specified. Cannot find task by name task_40 in the task definitions
        at com.netflix.conductor.core.execution.mapper.HTTPTaskMapper.lambda$null$0(HTTPTaskMapper.java:73)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.netflix.conductor.core.execution.mapper.HTTPTaskMapper.lambda$getMappedTasks$1(HTTPTaskMapper.java:71)
        at java.util.Optional.orElseGet(Optional.java:267)
        at com.netflix.conductor.core.execution.mapper.HTTPTaskMapper.getMappedTasks(HTTPTaskMapper.java:70)
        at com.netflix.conductor.core.execution.DeciderService.getTasksToBeScheduled(DeciderService.java:563)
```
Because `task_40` is not registered.

Is it expected that we register the task even for dynamic workflows?

**Comment by kishorebanala** [comment]
Hi @sujaysudheenda, you don't have to register task defs for dynamic workflow execution. Can you please post a mock workflow for which you're seeing this error.

**Comment by sujaysudheenda** [comment]
@kishorebanala I tried to reproduce it after pulling the latest version and I am not able to see that error. I will close this, for now. Will re-open if I am able to reproduce it with an example workflow.

Thanks for getting back to me.

Cheers!

**Comment by sujaysudheenda** [comment]
Hi @kishorebanala I am able to see this issue again (this time happening consistently)

Here is the example worfklow
```
{
  "name": "unregistered_workflow",
  "workflowDef": {
    "ownerApp": "my_owner_app",
    "createdBy": "my_username",
    "name": "unregistered_workflow",
    "description": "Test Workflow setup",
    "version": 1,
    "tasks": [
      {
        "name": "fetch_data",
        "type": "HTTP",
        "taskReferenceName": "fetch_data",
        "inputParameters": {
          "http_request": {
            "connectionTimeOut": "3600",
            "readTimeOut": "3600",
            "uri": "${workflow.input.uri}",
            "method": "GET",
            "accept": "application/json",
            "content-Type": "application/json",
            "headers": {
            }
          }
        }
      }
    ],
    "outputParameters": {
    }
  },
  "input": {
    "uri": "google.com"
  }
}
```

Here is the output of `GET http://localhost:8080/api/workflow/8aa6dd4e-f7a7-4c88-98d4-be91a1b5798b?includeTasks=false`
```
{
  "createTime": 1557785888209,
  "updateTime": 1557785888217,
  "status": "FAILED",
  "endTime": 1557785888217,
  "workflowId": "8aa6dd4e-f7a7-4c88-98d4-be91a1b5798b",
  "input": {
    "uri": "google.com"
  },
  "workflowType": "unregistered_workflow",
  "version": 1,
  "reasonForIncompletion": "Invalid task specified. Cannot find task by name fetch_data in the task definitions",
  "schemaVersion": 2,
  "workflowDefinition": {
    "ownerApp": "my_owner_app",
    "createdBy": "my_username",
    "name": "unregistered_workflow",
    "description": "Test Workflow setup",
    "version": 1,
    "tasks": [
      {
        "name": "fetch_data",
        "taskReferenceName": "fetch_data",
        "inputParameters": {
          "http_request": {
            "connectionTimeOut": "3600",
            "readTimeOut": "3600",
            "uri": "${workflow.input.uri}",
            "method": "GET",
            "accept": "application/json",
            "content-Type": "application/json",
            "headers": {}
          },
          "asyncComplete": false
        },
        "type": "HTTP",
        "startDelay": 0,
        "optional": false,
        "asyncComplete": false
      }
    ],
    "schemaVersion": 2,
    "restartable": true,
    "workflowStatusListenerEnabled": false
  },
  "startTime": 1557785888209,
  "workflowName": "unregistered_workflow",
  "workflowVersion": 1
}
```

**Comment by kishorebanala** [comment]
Hey @sujaysudheenda, Apologies for delays in responding.

Here are my findings - When `workflowDef` is used, it is also expecting a `taskDefinition` in tasks array, for each task that isn't already defined with Metadata api. I.e The task definition has to be predefined with Metadata API, or supplied in workflowDef above to use in Dynamic workflow.

In the above example, I've added `taskDefinition` to object in `tasks` array (Similar to how a completed workflow json's `workflowDefinition` is) to get it working:

```json
"taskDefinition": {
	"name": "fetch_data",
	"retryCount": 0,
	"timeoutSeconds": 3600,
	"timeoutPolicy": "TIME_OUT_WF",
	"retryLogic": "FIXED",
	"retryDelaySeconds": 0,
	"responseTimeoutSeconds": 3000
}
```
Here is complete workflow:
```json
{
  "name": "unregistered_workflow",
  "workflowDef": {
    "ownerApp": "my_owner_app",
    "createdBy": "my_username",
    "name": "unregistered_workflow",
    "description": "Test Workflow setup",
    "version": 1,
    "tasks": [
    	{
	        "name": "fetch_data",
	        "type": "HTTP",
	        "taskReferenceName": "fetch_data",
	        "inputParameters": {
	          "http_request": {
	            "connectionTimeOut": "3600",
	            "readTimeOut": "3600",
	            "uri": "${workflow.input.uri}",
	            "method": "GET",
	            "accept": "application/json",
	            "content-Type": "application/json",
	            "headers": {
	            }
	          }
	        },
	        "taskDefinition": {
	            "name": "fetch_data",
			    "retryCount": 0,
			    "timeoutSeconds": 3600,
			    "timeoutPolicy": "TIME_OUT_WF",
			    "retryLogic": "FIXED",
			    "retryDelaySeconds": 0,
			    "responseTimeoutSeconds": 3000
	        }
	    }
    ],
    "outputParameters": {
    }
  },
  "input": {
    "uri": "http://www.google.com"
  }
}
```

This is very subtle and could easily cause confusion, thanks for pointing. I'll update docs.

**Comment by sujaysudheenda** [comment]
@kishorebanala thanks for the help 🏆 Will try this out
