### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: ERR syntax error

### ISSUE THREAD

**Issue by GEverding** [Netflix/conductor#110]
Hey,

I've been trying to run conductor in a test environment and I keep getting this error. 

```
7438 [qtp1423752095-32] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve download_task
37459 [pool-4-thread-1] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR syntax error
37461 [pool-4-thread-1] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite-1} to host Host [hostname=dynomite-1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up]
37462 [pool-4-thread-1] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dynomite-1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up] Unexpected end of stream.
37479 [pool-4-thread-3] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR syntax error
37479 [pool-4-thread-3] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite-1} to host Host [hostname=dynomite-1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up]
37480 [pool-4-thread-3] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dynomite-1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up] Unexpected end of stream.
37490 [pool-4-thread-5] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR syntax error
37490 [pool-4-thread-5] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite-1} to host Host [hostname=dynomite-1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up]
37490 [pool-4-thread-5] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dynomite-1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up] Unexpected end of stream.
37491 [qtp1423752095-32] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
java.lang.RuntimeException: com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
	at com.netflix.dyno.queues.redis.RedisDynoQueue.executeWithRetry(RedisDynoQueue.java:611)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.executeWithRetry(RedisDynoQueue.java:608)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.executeWithRetry(RedisDynoQueue.java:608)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.execute(RedisDynoQueue.java:595)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:216)
	at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:153)
	at com.netflix.conductor.service.ExecutionService.poll(ExecutionService.java:96)
	at com.netflix.conductor.server.resources.TaskResource.poll(TaskResource.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:99)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:105)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:298)
	at com.netflix.dyno.jedis.DynoJedisClient.d_zadd(DynoJedisClient.java:1653)
	at com.netflix.dyno.jedis.DynoJedisClient.zadd(DynoJedisClient.java:1648)
	at com.netflix.dyno.queues.redis.RedisDynoQueue._pop(RedisDynoQueue.java:278)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.lambda$pop$7(RedisDynoQueue.java:232)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concu
```

```
java -server  -Ddb=dynomite -Dworkflow.dynomite.cluster.hosts=dynomite-1:8102:us-east- 1c -Dworkflow.dynomite.cluster.name=dyn_o_mite -Dworkflow.namespace.prefix=loki -Dworkflow.namespace.queue.prefix=loki_queues -Dqueues.dynomite.nonQuorum.port=22122 -Dworkflow.elasticsearch.url=10.240.0.2:9300 -Dworkflow.elasticsearch.index.name=loki -jar conductor.jar
```

When I look inside of redis its creating keys but when I go to fetch work for a task I get the above error. I have a feeling its some sort of configuration error but I'm not sure. Have you seen this error before?

**Comment by v1r3n** [comment]
@GEverding I see there is a blank space in `-Dworkflow.dynomite.cluster.hosts=dynomite-1:8102:us-east- 1c` - for "us-east-1c".
Can you also add this property? `-DEC2_AVAILABILTY_ZONE=us-east-1c`

Are you running the docker images?  The error is a bit strange, what are the steps to reproduce this error?

**Comment by v1r3n** [comment]
@GEverding can you check the version of redis you are using?  It should be 3.0.2 or greater.

**Comment by ipapapa** [comment]
@v1r3n hm, interesting error. To be safe Redis >3.0.7 is safe in production, but any above 2.8 would be fine. The Dyno still uses Jedis APIs 2.8.6.

**Comment by gsambasiva** [comment]
@GEverding  I am facing a similar issue is this issue got fixed.
If it is fixed for you, could you please let me know how to fix this issue
