### ISSUE TITLE
Conductor is not recovering after dynomite restart

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#1107]
Conductor server is not recovering after dynomite restart. pollAndExecute of SystemTaskWorker is executing repeatedly in interval forever. 

```
java.lang.RuntimeException: java.lang.RuntimeException: com.netflix.dyno.connectionpool.exception.NoAvailableHostsException: NoAvailableHostsException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down, hashtag=null], latency=0(0), attempts=0]Local rack host offline and could not find any remote hosts for fallback connection
	at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:232)
	at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:153)
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.pollAndExecute(SystemTaskWorkerCoordinator.java:142)
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$listen$0(SystemTaskWorkerCoordinator.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any thoughts on the issue?

**Comment by emiteze** [comment]
We have a Kotlin server application besides conductor here that connects on the same dynomite as Conductor do, and we faced the same issue after dynomite restarts/failover. So, it might be a bug in the dynomite client.

See this issue:
https://github.com/Netflix/dyno/issues/256

**Comment by kishorebanala** [comment]
@jkaipa I suggest to open this issue with Dynomite, as they might be able to help better.

**Comment by xiyan1120** [comment]
How do I do the task fallback？
