### ISSUE TITLE
Redis Cluster NOAUTH

### ISSUE THREAD

**Issue by RileyMichael** [Netflix/conductor#1116]
I'm attempting to use Conductor (v2.10.1) backed with a [redis cluster](https://github.com/helm/charts/tree/master/stable/redis).

Config: 
```
db: redis_cluster
workflow.dynomite.cluster.hosts: redis-master.ns.skydns.local:6379:us-east-1c:password
workflow.dynomite.cluster.name: conductor
workflow.elasticsearch.index.name: conductor
workflow.elasticsearch.url: http://pl-conductor-es-client.ns.skydns.local:9200
workflow.namespace.prefix: conductor
```
I believe support for redis-auth was added in commit a24b7c8ae10a63ea65128a3fb18dd62d41cbfe02
I'm getting the following exception though:
```
Error in custom provider, redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
  while locating com.netflix.conductor.jedis.RedisClusterJedisProvider
  while locating redis.clients.jedis.JedisCommands
    for the 1st parameter of com.netflix.conductor.dyno.DynoProxy.<init>(DynoProxy.java:56)
  at com.netflix.conductor.dao.RedisWorkflowModule.configure(RedisWorkflowModule.java:34) (via modules: com.google.inject.util.Modules$OverrideModule -> com.netflix.conductor.dao.RedisWorkflowModule)
  while locating com.netflix.conductor.dyno.DynoProxy
    for the 1st parameter of com.netflix.conductor.dao.dynomite.RedisMetadataDAO.<init>(RedisMetadataDAO.java:65)
  at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.class(RedisMetadataDAO.java:51)
  while locating com.netflix.conductor.dao.dynomite.RedisMetadataDAO
  while locating com.netflix.conductor.dao.MetadataDAO
    for the 1st parameter of com.netflix.conductor.core.metadata.MetadataMapperService.<init>(MetadataMapperService.java:60)
  at com.netflix.conductor.core.metadata.MetadataMapperService.class(MetadataMapperService.java:55)
  while locating com.netflix.conductor.core.metadata.MetadataMapperService
    for the 4th parameter of com.netflix.conductor.core.execution.WorkflowExecutor.<init>(WorkflowExecutor.java:106)
  while locating com.netflix.conductor.core.execution.WorkflowExecutor
    for the 1st parameter of com.netflix.conductor.core.execution.WorkflowSweeper.<init>(WorkflowSweeper.java:60)
  at com.netflix.conductor.server.ServerModule.configure(ServerModule.java:53) (via modules: com.google.inject.util.Modules$OverrideModule -> com.netflix.conductor.server.ServerModule)
  while locating com.netflix.conductor.core.execution.WorkflowSweeper
Caused by: redis.clients.jedis.exceptions.JedisDataException (same stack trace as error #12)
```

Has anyone else ran into this issue, or am I overlooking a property?

**Comment by kishorebanala** [comment]
Hey @RileyMichael, thanks for cleaning up the issue. I'd appreciate if you can update with resolution, if you found one.

**Comment by RileyMichael** [comment]
@kishorebanala I chalked it up to user error & just ended up switching to sentinel and disabling authentication.
