### ISSUE TITLE
Error with elasticsearch

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#1141]
I am seeing the following exception while running the workflow. What could be happening here?
```
{"level":"DEBUG", "time":"15/May/2019:15:39:03 UTC", "thread":"RxComputationScheduler-2", "log":"Attempt # 3, 6644 millis since first attempt. Operation: updateWithRetry, description:Index workflow into doc_type workflow"}
{"level":"DEBUG", "time":"15/May/2019:15:39:03 UTC", "thread":"RxComputationScheduler-2", "log":"Operation 'updateWithRetry:Index workflow into doc_type workflow' failed after retrying 3 times, retry limit 3"}
java.lang.IllegalArgumentException: Rejecting mapping update to [conductor] as the final mapping would have more than 1 type: [task, workflow]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:407)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:355)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:287)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:312)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:229)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
{"level":"ERROR", "time":"15/May/2019:15:39:03 UTC", "thread":"RxComputationScheduler-2", "log":"Failed to index conductor for request type: task"}
java.lang.RuntimeException: Operation 'updateWithRetry:Index workflow into doc_type workflow' failed after retrying 3 times, retry limit 3
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:124)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.updateWithRetry(ElasticSearchDAOV5.java:437)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexTask(ElasticSearchDAOV5.java:308)
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateTask(ExecutionDAOFacade.java:235)
	at com.netflix.conductor.core.execution.WorkflowExecutor.scheduleTask(WorkflowExecutor.java:1160)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:832)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:850)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:850)
	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:742)
	at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:192)
	at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:188)
	at com.netflix.conductor.contribs.queue.QueueManager.lambda$startMonitor$7(QueueManager.java:141)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
	at rx.Observable.unsafeSubscribe(Observable.java:10140)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
	at rx.Scheduler$Worker$1.call(Scheduler.java:137)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [conductor] as the final mapping would have more than 1 type: [task, workflow]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:407)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:355)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:287)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:312)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:229)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
	... 3 more
```

**Comment by kishorebanala** [comment]
@jkaipa Which ES cluster version you're using? I believe ES6 has removed support for multiple types in same index. If this is happening in ES5 cluster, can you post your configuration to help us reproduce this issue?

**Comment by microsoftly** [comment]
+1 on this. I'm also facing this error

**Comment by demichej** [comment]
@microsoftly and @jkaipa this is most certainly a case of you running ElasticSearch 6 instead of 5. If you want to use ES 6, there are instructions here:

https://github.com/Netflix/conductor/tree/master/es6-persistence

Personally, I feel like we should figure out how to make it easier for people to switch to ES6, but for right now that's the way to do it. It's probably easiest to just roll with ES 5 though, to be honest.

**Comment by jkaipa** [comment]
This could be a ES5 to ES6 compatibility issue. I didn't get a chance to pursue later after that. Closing the issue.
