### ISSUE TITLE
Read timed out for a task calling a long running microservice

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/conductor#1191]
I am trying to run a long running  HTTP task but it fails if not completed by within 10 seconds. Please let me know what else needs to be provided. 

441546 [system-task-worker-0] ERROR com.netflix.conductor.contribs.http.HttpTask  - Failed to invoke http task - uri: http://localhost:8181/entityapp/entity, vipAddress: null
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.method(WebResource.java:623)
        at com.netflix.conductor.contribs.http.HttpTask.httpCall(HttpTask.java:191)
        at com.netflix.conductor.contribs.http.HttpTask.start(HttpTask.java:118)
        at com.netflix.conductor.core.execution.WorkflowExecutor.executeSystemTask(WorkflowExecutor.java:1035)
        at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$pollAndExecute$1(SystemTaskWorkerCoordinator.java:148)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
        ... 13 more

Task definition-
{
"name": "createEntity",
"description": "Create an Entity Record",
"retryCount": 0,
"timeoutSeconds": 3600,
"timeoutPolicy": "ALERT_ONLY",
"retryLogic": "FIXED",
"retryDelaySeconds": 60,
"responseTimeoutSeconds": 3600,
"concurrentExecLimit": 0
}
And following workflow task-
{
"name": "createEntity",
"taskReferenceName": "create_entity",
"type": "HTTP",
"startDelay": 0,
"inputParameters": {
             "http_request": {
                     "uri": "https://localhost:8181/entityapp/entity",
                     "method": "POST",
                     "body": {
                          "name": "${workflow.input.name}",
                          "email": "${workflow.input.email}"
                      },
		     "connectionTimeOut": "3600",
                     "readTimeOut": "6000"
            }
}

**Comment by rituparnopal** [comment]
I found out that the read timeout is set to milliseconds so in the above example for 6000 actually means 6 seconds and not 1 min.
