### ISSUE TITLE
docker-compose build error

### ISSUE THREAD

**Issue by aresares** [Netflix/conductor#1201]
Hi, I get this error when trying to build it from docker-compose. Im working under ubuntu

```
root@my-server:/home/my/netflixConductor/conductor-master/docker# docker-compose build
dynomite uses an image, skipping
elasticsearch uses an image, skipping
Building conductor-server
Step 1/16 : FROM openjdk:8-jdk AS builder
 ---> b84359d0cbce
Step 2/16 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> 6be829eb3ee6
Step 3/16 : COPY . /conductor
 ---> Using cache
 ---> 87a878c9a673
Step 4/16 : WORKDIR /conductor
 ---> Using cache
 ---> 8b1ac2fa32c5
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in e41bfb556efb
Downloading https://services.gradle.org/distributions/gradle-4.8.1-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 1

```

**Comment by apanicker-nflx** [comment]
Seems like a connection error trying to download the gradle wrapper. Please try to reset the connection and try again.

**Comment by crazy-cpu** [comment]
i have same problem,how to solve it?
