### ISSUE TITLE
Unable to install UI based on the instruction provided

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/conductor#1204]
$ gulp watch
[10:31:08] Failed to load external module @babel/register
[10:31:08] Error: Cannot find module '@babel/register' from 'C:\conductor\ui'
[10:31:08] Failed to load external module babel-register
[10:31:08] Error: Cannot find module 'babel-register' from 'C:\conductor\ui'
[10:31:08] Failed to load external module babel-core/register
[10:31:08] Error: Cannot find module 'babel-core/register' from 'C:\conductor\ui'
[10:31:08] Failed to load external module babel/register
[10:31:08] Error: Cannot find module 'babel/register' from 'C:\conductor\ui'
C:\conductor\ui\gulpfile.babel.js:2
import gulp from 'gulp';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at execute (C:\Users\user\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:36:18)
    at Liftoff.handleArguments (C:\Users\user\AppData\Roaming\npm\node_modules\gulp-cli\index.js:201:24)
    at Liftoff.execute (C:\Users\user\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:201:12)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\flagged-respawn\index.js:51:3)

**Comment by mstier-nflx** [comment]
What are the results for 'npm install'?  It appears it did not download the dependencies correctly.

**Comment by rituparnopal** [comment]
I am a beginner with advanced Javascripts. Looks like the dependencies are not proper. 
Please find the log below-
$ npm install
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

**Comment by vijchint** [comment]
I am facing the same issue. Can anyone help me out here

**Comment by tomasol** [comment]
I had the same issue with `gulp watch`. Apparently there is a conflict between gulp 3.9 that is required by conductor and node v12 as described [here](https://stackoverflow.com/a/57804190). I installed node v11.15.0.
