### ISSUE TITLE
Connecting to Dynomite

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#124]
I've setup Redis and Dynomite on AWS which I'm trying to connect to from the conductor-server running on localhost. I've tunneled ports 8102 and 22122 from AWS to localhost. I'm getting an exception on the server:

```
Using conductor.properties
0    [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
5    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up]
5    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up], with conns:3
42   [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up]
57   [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - registered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
59   [main] INFO  com.netflix.conductor.server.ConductorServer  - Starting conductor server using dynomite cluster dynomite




                     _            _             
  ___ ___  _ __   __| |_   _  ___| |_ ___  _ __ 
 / __/ _ \| '_ \ / _` | | | |/ __| __/ _ \| '__|
| (_| (_) | | | | (_| | |_| | (__| || (_) | |   
 \___\___/|_| |_|\__,_|\__,_|\___|\__\___/|_|   




234  [main] INFO  com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO  - DynoQueueDAO initialized with prefix conductor_queues.test!
798  [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
1048 [main] INFO  org.elasticsearch.plugins  - [Tigra] modules [], plugins [], sites []
1624 [main] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught JedisConnectionException: java.net.SocketException: Connection reset
1627 [main] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=localhost} to host Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up]
1627 [main] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up] java.net.SocketException: Broken pipe (Write failed)
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
  at com.netflix.conductor.core.events.EventProcessor.<init>(EventProcessor.java:74)
  at com.netflix.conductor.core.config.CoreModule.configure(CoreModule.java:37) (via modules: com.netflix.conductor.server.ServerModule -> com.netflix.conductor.core.config.CoreModule)
  while locating com.netflix.conductor.core.events.EventProcessor

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.netflix.conductor.server.ConductorServer.start(ConductorServer.java:194)
	at com.netflix.conductor.server.Main.main(Main.java:62)
Caused by: com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:99)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:298)
	at com.netflix.dyno.jedis.DynoJedisClient.d_hscan(DynoJedisClient.java:588)
	at com.netflix.dyno.jedis.DynoJedisClient.hscan(DynoJedisClient.java:583)
	at com.netflix.conductor.dao.dynomite.DynoProxy.hgetAll(DynoProxy.java:155)
	at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getEventHandlers(RedisMetadataDAO.java:249)
	at com.netflix.conductor.service.MetadataService.getEventHandlers(MetadataService.java:147)
	at com.netflix.conductor.core.events.EventProcessor.refresh(EventProcessor.java:108)
	at com.netflix.conductor.core.events.EventProcessor.<init>(EventProcessor.java:83)
	at com.netflix.conductor.core.events.EventProcessor$$FastClassByGuice$$d41a77ee.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 6 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:242)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:248)
	at redis.clients.jedis.Jedis.hscan(Jedis.java:3152)
	at redis.clients.jedis.Jedis.hscan(Jedis.java:3145)
	at com.netflix.dyno.jedis.DynoJedisClient$26.execute(DynoJedisClient.java:591)
	at com.netflix.dyno.jedis.DynoJedisClient$26.execute(DynoJedisClient.java:588)
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:86)
	... 29 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
	... 40 more
^C43115 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Shutting down connection pool for host:Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up]
43115 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up] Unexpected end of stream.
43115 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=localhost, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up] Unexpected end of stream.
43116 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Remove host: Successfully removed host localhost from connection pool
43116 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - deregistered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
```

conductor.properties:
```
db=dynomite
workflow.dynomite.cluster.hosts=localhost:8102:us-east-1b
queues.dynomite.nonQuorum.port=22122
EC2_AVAILABILITY_ZONE=us-east-1b
workflow.dynomite.cluster.name=dynomite
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
```

dynomite logs:
```
[2017-03-16 00:51:35.547] dn_print_run:206 dynomite-v0.5.8-5_HgetallLocalRack-130-g366999a built for Linux 4.4.0-67-generic x86_64 started on pid 22526
[2017-03-16 00:51:35.547] dn_print_run:211 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[2017-03-16 00:51:35.547] dn_print_run:213                                                                       
     #                                      m                        
  mmm#  m   m  mmmm    mmm   mmmmm  mmm    mm#mm   mmm                
 #   #  \m m/  #   #  #   #  # # #    #      #    #   #               
 #   #   #m#   #   #  #   #  # # #    #      #    #''''               
 \#m##   \#    #   #   #m#   # # #  mm#mm    mm    #mm                
         m/
        ##

[2017-03-16 00:51:35.547] conf_validate_pool:2248 conf: directive "stats_listen:" is missing - using defaults 0.0.0.0:22222
[2017-03-16 00:51:35.547] stats_listen:1369 m 4 listening on '0.0.0.0:22222'
[2017-03-16 00:51:35.547] entropy_key_iv_load:364 Key File name: conf/recon_key.pem - IV File name: conf/recon_iv.pem
[2017-03-16 00:51:35.548] entropy_key_iv_load:419 key loaded: 0123456789012345
[2017-03-16 00:51:35.548] entropy_key_iv_load:427 iv loaded: 0123456789012345
[2017-03-16 00:51:35.548] entropy_listen:328 anti-entropy m 8 listening on '127.0.0.1:8105'
[2017-03-16 00:51:35.548] conn_connect:622 <SERVER 0x1c65eb0 11 to '127.0.0.1:22122:1'> connecting.....
[2017-03-16 00:51:35.548] proxy_init:122 <PROXY 0x1c660c0 12 listening on '127.0.0.1:8102'> inited in redis <POOL 0x1c57080 'dyn_o_mite'>
[2017-03-16 00:51:35.548] dnode_init:110 <PEER_PROXY 0x1c66280 13 listening on '127.0.0.1:8101'> inited in redis <POOL 0x1c57080 'dyn_o_mite'>
[2017-03-16 00:51:35.548] preselect_remote_rack_for_replication:1798 my rack index 0
[2017-03-16 00:51:35.548] core_start:338 YAML provided mbuf_size: 16384
[2017-03-16 00:51:35.548] core_start:345 YAML provided max_msgs: 300000
[2017-03-16 00:51:35.548] core_close_log:461 close <SERVER 0x1c65eb0 11 to '127.0.0.1:22122:1'> on event FFFFFF eof 0 done 0 rb 0 sb 0: Connection refused
[2017-03-16 00:51:35.548] server_close:328 close <SERVER 0x1c65eb0 11 to '127.0.0.1:22122:1'> Dropped 0 outqueue & 0 inqueue requests
[2017-03-16 00:51:35.548] server_failure:183 server '127.0.0.1:22122:1' failure count 1 limit 3
[2017-03-16 00:51:35.548] event_del_conn:234 epoll ctl on e 9 sd 11 failed: No such file or directory
[2017-03-16 00:52:05.578] core_print_peer_status:63 0)0x1c69f80 localdc localrack 127.0.0.1:8101 NORMAL
```

dynomite.yml
```
dyn_o_mite:
  listen: 127.0.0.1:8102
  dyn_listen: 127.0.0.1:8101
  tokens: '101134286'
  servers:
  - 127.0.0.1:22122:1
  data_store: 0
  mbuf_size: 16384
  max_msgs: 300000
```

**Comment by v1r3n** [comment]
@clari-akhilesh couple of quick questions;
1.  Can you try redis-cli and run few commands to ensure dynomite server connectivity is in order?
2.  Dynomite needs a redis server, do you have it running on port 22122 on the same host as Dynomite?
3.  Can you try redis-cli to connect to redis and try?

There is active gitter community for Dynomite @ https://gitter.im/Netflix/dynomite, feel free to join and you might be able to get some more details there too.

**Comment by clari-akhilesh** [comment]
Thanks @v1r3n. I was not running dynomite on the same port as redis. I will close this issue.
