### ISSUE TITLE
MySQL Persistence should retry on Deadlock

### ISSUE THREAD

**Issue by s50600822** [Netflix/conductor#1263]
Should mysql operation in ```withTransaction``` be wrapped inside ```RetryUtil.retryOnException``` so that issue like can be retried on the spot:
```
	at org.eclipse.jetty.server.Server.handle(Server.java:524) 
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) 
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) 
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) 
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) 
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) 
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) 
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) 
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) 
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) 
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) 
	at java.lang.Thread.run(Thread.java:748) 
Caused by: com.netflix.conductor.core.execution.ApplicationException: BACKEND_ERROR - Deadlock found when trying to get lock; try restarting transaction 
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:103) 
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.withTransaction(MySQLBaseDAO.java:152) 
	at com.netflix.conductor.dao.mysql.MySQLExecutionDAO.updateTask(MySQLExecutionDAO.java:137) 
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateTask(ExecutionDAOFacade.java:250) 
	... 51 more 
Caused by: com.netflix.conductor.core.execution.ApplicationException: Deadlock found when trying to get lock; try restarting transaction 
	at com.netflix.conductor.dao.mysql.Query.executeUpdate(Query.java:276) 
	at com.netflix.conductor.dao.mysql.MySQLExecutionDAO.lambda$addWorkflowToTaskMapping$37(MySQLExecutionDAO.java:584) 
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.execute(MySQLBaseDAO.java:197) 
	at com.netflix.conductor.dao.mysql.MySQLExecutionDAO.addWorkflowToTaskMapping(MySQLExecutionDAO.java:583) 
	at com.netflix.conductor.dao.mysql.MySQLExecutionDAO.updateTask(MySQLExecutionDAO.java:523) 
	at com.netflix.conductor.dao.mysql.MySQLExecutionDAO.lambda$updateTask$2(MySQLExecutionDAO.java:137) 
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.lambda$withTransaction$3(MySQLBaseDAO.java:153) 
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:98) 
	... 54 more 

```

I think we wrap ES operations but not MySQL for some reason, the Exception above was recorded on v2.3.15.

**Comment by kishorebanala** [comment]
@s50600822 Definitely makes sense to add retries here. Please feel free to submit a PR when you have a chance.

**Comment by s50600822** [comment]
> @s50600822 Definitely makes sense to add retries here. Please feel free to submit a PR when you have a chance.

will do, in the meant time, let me know if there's a guideline I should follow. Like:
- code coverage
- PR target branch

**Comment by 0532** [comment]
m

**Comment by s50600822** [comment]
https://github.com/Netflix/conductor/pull/1299/commits/d861fb5dadef82479af78725128bbc0c34e099df
