### ISSUE TITLE
MYSQL v3 migration contains invalid MYSQL syntax(only supported by MariaDB)?

### ISSUE THREAD

**Issue by s50600822** [Netflix/conductor#1264]
From:
https://github.com/Netflix/conductor/blob/master/mysql-persistence/src/main/resources/db/migration/V3__queue_add_priority.sql

```
ALTER TABLE `queue_message` ADD COLUMN IF NOT EXISTS `priority` TINYINT DEFAULT 0 AFTER `message_id`;
```
ADD COLUMN IF NOT EXISTS does not seem to be a valid ALTER TABLE option: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

As a result:
```
mysql> ALTER TABLE 'queue_message' ADD COLUMN IF NOT EXISTS 'priority' TINYINT DEFAULT 0 AFTER 'message_id';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''queue_message' ADD COLUMN IF NOT EXISTS 'priority' TINYINT DEFAULT 0 AFTER 'mes' at line 1
```

An interesting side effect of this is that even though the migration failed, flyway recorded this as done in schema_version
<img width="1231" alt="Screen Shot 2019-08-19 at 10 15 06 pm" src="https://user-images.githubusercontent.com/5586453/63264629-e73b8580-c2ce-11e9-9aed-6e09a02ce7b6.png">

Which fails startup later and require manual fix in database. Subsequent startup will not show the SQL syntax error.
```
delete  from schema_version where installed_rank =3;
```

Upgrading flyway fixes the issue where flyway.migrate() combine with com.netflix.conductor.mysql.MySQLDataSourceProvider.get() and Guice creates a vicious cycle of unlimited connection pool until:
```
10005 [main] ERROR com.zaxxer.hikari.pool.HikariPool  - HikariPool-21 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.get(MySQLDataSourceProvider.java:27)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.get(MySQLDataSourceProvider.java:15)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.netflix.governator.event.ApplicationEventModule$ApplicationEventSubscribingProvisionListener.onProvision(ApplicationEventModule.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
```
[unlimited_connection_pool.log](https://github.com/Netflix/conductor/files/3528790/unlimited_connection_pool.log)

<img width="1590" alt="Screen Shot 2019-08-22 at 5 29 34 pm" src="https://user-images.githubusercontent.com/5586453/63495056-71b7fb00-c502-11e9-8d96-02a807592668.png">

****
ADD COLUMN IF NOT EXIST is actually valid for MariaDB(https://mariadb.com/kb/en/library/alter-table/). So if Conductor choose to not support vanilla MySQL, this could use some fix or document.
Overall MySQL is known to have better performance compare to MariaDB. Not sure how relevant in conductor context where most query are quite simple.

**Comment by apanicker-nflx** [comment]
@s50600822 Thanks for flagging this. Please feel free to submit a PR with the fix.

**Comment by s50600822** [comment]
> @s50600822 Thanks for flagging this. Please feel free to submit a PR with the fix.

https://github.com/Netflix/conductor/issues/1264
- is there a script to run code coverage on my local, any trick to deal with it when it doesn't really make sense?
- is there a gradle task or script to update dependencies.lock ?

**Comment by s50600822** [comment]
See https://github.com/Netflix/conductor/pull/1280.
