### ISSUE TITLE
JsonJqTransform does not always provide an error message

### ISSUE THREAD

**Issue by Jiehong** [Netflix/conductor#1284]
Hello,

For some inputs, the JsonJqTransform task does not always provide the correct error message.

Here is a case reproducing this case:

```java
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import com.netflix.conductor.common.metadata.tasks.Task;
import com.netflix.conductor.common.run.Workflow;
import com.netflix.conductor.contribs.json.JsonJqTransform;

public class JsonJqTransformTest {
  @Test
  void wrongInputCausesNoMessage() {
    final JsonJqTransform t = new JsonJqTransform();
    final Workflow w = new Workflow();
    final Task task = new Task();
    final Map<String, Object> inputData = new HashMap<>();
    inputData.put("queryExpression", "{officeID: (.inputJson.OIDs | unique)[], requestedIndicatorList: .inputJson.requestedindicatorList}");
    final Map<String, Object> inputJson = new HashMap<>();
    inputJson.put("OIDs", Collections.singletonList("VALUE"));
    final Map<String, Object> indicatorList = new HashMap<>();
    indicatorList.put("indicator", "AFA");
    indicatorList.put("value", false);
    inputJson.put("requestedindicatorList", Collections.singletonList(indicatorList));
    inputData.put("inputJson", inputJson);
    task.setInputData(inputData);
    task.setOutputData(new HashMap<>());

    t.start(w, task, null);

    Assertions.assertEquals("N/A", task.getOutputData().get("error"));
  }
}
```

This test passes, but it shouldn't.

Indeed, if we look at the stacktrace we get inside the catch part of `JsonJqTransform::start`, we get the following:

```
java.util.concurrent.ExecutionException: net.thisptr.jackson.jq.exception.JsonQueryException: N/A
  at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
  at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
  at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
  at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2373)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2337)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
  at com.netflix.conductor.contribs.json.JsonJqTransform.start(JsonJqTransform.java:68)
(...)
Caused by: net.thisptr.jackson.jq.exception.JsonQueryException: N/A
  at net.thisptr.jackson.jq.JsonQuery.compile(JsonQuery.java:38)
  at com.netflix.conductor.contribs.json.JsonJqTransform$1.load(JsonJqTransform.java:94)
  at com.netflix.conductor.contribs.json.JsonJqTransform$1.load(JsonJqTransform.java:91)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  ... 83 more
Caused by: net.thisptr.jackson.jq.internal.javacc.ParseException: Encountered " "|" "| "" at line 1, column 40.
Was expecting one of:
    "}" ...
    "," ...
    
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.generateParseException(JsonQueryParser.java:2258)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.jj_consume_token(JsonQueryParser.java:2123)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.ObjectConstruction(JsonQueryParser.java:751)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.PrimaryExpression(JsonQueryParser.java:488)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.BinaryOperatorExpression(JsonQueryParser.java:226)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.TupleExpression(JsonQueryParser.java:199)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.JsonQuery(JsonQueryParser.java:126)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.ArrayConstruction(JsonQueryParser.java:888)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.PrimaryExpression(JsonQueryParser.java:474)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.BinaryOperatorExpression(JsonQueryParser.java:226)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.TupleExpression(JsonQueryParser.java:199)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.JsonQuery(JsonQueryParser.java:126)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.Start(JsonQueryParser.java:117)
  at net.thisptr.jackson.jq.internal.javacc.JsonQueryParser.compile(JsonQueryParser.java:22)
  at net.thisptr.jackson.jq.JsonQuery.compile(JsonQuery.java:36)
  ... 87 more
```

So we have 2 levels of exceptions saying "N/A", and the third one does provide the correct error message.

The correct error message should be retrieved instead.

Here:
```
Encountered " "|" "| "" at line 1, column 40.
Was expecting one of:
    "}" ...
    "," ...
```

**Comment by apanicker-nflx** [comment]
Closed since #1286 is merged.
