### ISSUE TITLE
./gradlew build fails - Task :conductor-mysql-persistence:test FAILED

### ISSUE THREAD

**Issue by maheshyaddanapudi** [Netflix/conductor#1319]
Hi,

I did git clone and then ./gradlew build in the conductor root folder.

git clone https://github.com/Netflix/conductor.git
Cloning into 'conductor'...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 31522 (delta 42), reused 122 (delta 34), pack-reused 31374
Receiving objects: 100% (31522/31522), 9.52 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (11660/11660), done.

Getting the below error now matter what I try ...

> Task :conductor-mysql-persistence:test

com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > pollDeferredMessagesTest FAILED
    java.lang.ExceptionInInitializerError at MySQLQueueDAOTest.java:43
        Caused by: java.lang.RuntimeException at MySQLQueueDAOTest.java:43
            Caused by: ch.vorburger.exec.ManagedProcessException at MySQLQueueDAOTest.java:43
                Caused by: ch.vorburger.exec.ManagedProcessException at MySQLQueueDAOTest.java:43
                    Caused by: org.apache.commons.exec.ExecuteException
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49

com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > processUnacksTest FAILED
    java.lang.NoClassDefFoundError at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49

com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > complexQueueTest FAILED
    java.lang.NoClassDefFoundError at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49

com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > pollMessagesTest FAILED
    java.lang.NoClassDefFoundError at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49

com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testWorkflowDefOperations FAILED
    java.lang.NoClassDefFoundError at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46

com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testEventHandlers FAILED
    java.lang.NoClassDefFoundError at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46

com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testRemoveTaskDef FAILED
    java.lang.NoClassDefFoundError at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46

com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testDuplicate FAILED
    java.lang.NoClassDefFoundError at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46

com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testTaskDefOperations FAILED
    java.lang.NoClassDefFoundError at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testPendingByCorrelationId FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testTaskOps FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > complexExecutionTest FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testPending FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testCreateTaskException FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testTaskCreateDups FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testCreateTaskException2 FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testPollData FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testTaskExceedsLimit FAILED
    java.lang.NoClassDefFoundError at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51

18 tests completed, 18 failed

> Task :conductor-mysql-persistence:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-mysql-persistence:test'.
> There were failing tests. See the report at: file:///Users/mahesh/git/conductor/mysql-persistence/build/reports/tests/test/index.html

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':conductor-mysql-persistence:test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///Users/mahesh/git/conductor/mysql-persistence/build/reports/tests/test/index.html
        at org.gradle.api.tasks.testing.AbstractTestTask.handleTestFailures(AbstractTestTask.java:612)
        at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:484)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:603)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 30 more

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
103 actionable tasks: 14 executed, 89 up-to-date

**Comment by kishorebanala** [comment]
@maheshyaddanapudi Mysql module uses embedded MariaDB for some of the tests. Sometimes, MariaDB has to be installed on your local machine for the tests to complete successfully.

@jvemugunta @picaron As some of the frequent committers to Mysql module, do you think we can reevaluate the need for embedded MariaDB?

**Comment by maheshyaddanapudi** [comment]
Well I was happily able to bypass the test phase in Gradle build using ./Gradle build -x test

However, just as a suggestion, it would be better to retain the test part in Gradle but comment it our default for MySQL.
