### ISSUE TITLE
Conductor gradlew build failing: Task :conductor-test-harness:test FAILED

### ISSUE THREAD

**Issue by faheemzunjani** [Netflix/conductor#1359]
Unable to build conductor using ```./gradlew build``` and ```./gradlew clean build``` from the root directory of conductor repository on both ```master``` and ```dev``` branches.

Below is the snapshot of the build log:  
```
com.netflix.conductor.tests.integration.HttpEndToEndTest STANDARD_OUT
    138751 [Test worker] INFO  org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.s.ServletContextHandler@e2c6116{/,null,AVAILABLE}
    138753 [Test worker] INFO  com.netflix.conductor.elasticsearch.es5.EmbeddedElasticSearchV5  - Stopping Elastic Search
    138811 [Test worker] INFO  com.netflix.conductor.elasticsearch.es5.EmbeddedElasticSearchV5  - Elastic Search on port 9201 stopped

Gradle Test Executor 36 finished executing tests.

> Task :conductor-test-harness:test FAILED

com.netflix.conductor.tests.integration.HttpEndToEndTest > classMethod FAILED
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:390)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.netflix.conductor.jetty.server.JettyServer.start(JettyServer.java:72)
        at com.netflix.conductor.tests.integration.HttpEndToEndTest.setup(HttpEndToEndTest.java:50)

162 tests completed, 1 failed, 7 skipped
Finished generating test XML results (0.015 secs) into: /Users/b0213178/IdeaProjects/conductor/test-harness/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.015 secs) into: /Users/b0213178/IdeaProjects/conductor/test-harness/build/reports/tests/test
:conductor-test-harness:test (Thread[Task worker for ':',5,main]) completed. Took 2 mins 37.766 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-test-harness:test'.
> There were failing tests. See the report at: file:///Users/b0213178/IdeaProjects/conductor/test-harness/build/reports/tests/test/index.html
```

How do I fix this?

**Comment by kishorebanala** [comment]
@faheemzunjani `java.net.BindException: Address already in use`: The port this test is trying to use is probably not available. Consider freeing up this port or change the port used by this test.
