### ISSUE TITLE
Conductor server cannot be used normally by “PoolOfflineException”

### ISSUE THREAD

**Issue by manheiba** [Netflix/conductor#1400]
Who has encountered this problem, thanks

```
java.lang.RuntimeException: com.netflix.dyno.connectionpool.exception.PoolOfflineException: PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down, hashtag=null, password=null], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
        at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:343)
        at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:192)
        at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.pollAndExecute(SystemTaskWorkerCoordinator.java:162)
        at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$listen$0(SystemTaskWorkerCoordinator.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.netflix.dyno.connectionpool.exception.PoolOfflineException: PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down, hashtag=null, password=null], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnection(HostSelectionWithFallback.java:161)
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnectionUsingRetryPolicy(HostSelectionWithFallback.java:120)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:305)
        at com.netflix.dyno.jedis.DynoJedisClient.d_zrangeByScore(DynoJedisClient.java:2231)
        at com.netflix.dyno.jedis.DynoJedisClient.zrangeByScore(DynoJedisClient.java:2225)
        at com.netflix.dyno.queues.redis.RedisDynoQueue.doPeekIdsFromShardHelper(RedisDynoQueue.java:290)
        at com.netflix.dyno.queues.redis.RedisDynoQueue.doPrefetchIdsHelper(RedisDynoQueue.java:520)
        at com.netflix.dyno.queues.redis.RedisDynoQueue.prefetchIds(RedisDynoQueue.java:471)
        at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:335)
        ... 10 more

```

**Comment by manheiba** [comment]
This problem occurs in the high concurrency scenario of 2.19.0, which is not found in version 2.21.0.

**Comment by apanicker-nflx** [comment]
@manheiba Please provide more details about your setup including Dynomite server version, Conductor version, etc.
From the stack trace provided, it looks like the dynomite connection was unsuccessful.

**Comment by manheiba** [comment]
@apanicker-nflx thank you

conductor version 2.19.0，I didn't use Dynomite server

I used  
`db=redis`

This may be a problem caused by my test cases. However, the update to version 2.21.0 does not have this problem.
