### ISSUE TITLE
Communicate with Redis through SSL/TLS

### ISSUE THREAD

**Issue by DemisB** [Netflix/conductor#1424]
Hi,

First of all, thanks for open-sourcing conductor, it is a great tool!

I am trying to setup a conductor server that works with a Redis persistence model. My redis instance runs on a different server and can only be accessed through SSL/TLS encryption (to be honest, my knowledge of encryption using SSL and/or TLS is quite vague). I think it is the reason why conductor seems to be unable to communicate with my redis instance, as I read this in the conductor output (cf. the first `[ERROR]`, followed by `Unexpected end of stream`):
```
Using config file: settings.properties
[INFO ] 2019-11-28 16:33:49,098 ModulesProvider - Starting conductor server using dynomite/redis cluster.
[WARN ] 2019-11-28 16:33:49,101 ModulesProvider - Starting locking module using Noop Lock.
[INFO ] 2019-11-28 16:33:49,103 ModulesProvider - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:48)
	at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:151)
	at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:59)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:50)
[INFO ] 2019-11-28 16:33:49,158 SystemTaskWorkerCoordinator - Adding the queue for system task: HTTP
[INFO ] 2019-11-28 16:33:49,266 HttpTask - HttpTask initialized...
[INFO ] 2019-11-28 16:33:49,268 SystemTaskWorkerCoordinator - Adding the queue for system task: KAFKA_PUBLISH
[INFO ] 2019-11-28 16:33:49,268 KafkaPublishTask - KafkaTask initialized...
[INFO ] 2019-11-28 16:33:49,268 SystemTaskWorkerCoordinator - Adding the queue for system task: JSON_JQ_TRANSFORM
[INFO ] 2019-11-28 16:33:49,871 ConfigurationInjectingListener - Initializing ConfigurationInjectingListener
[INFO ] 2019-11-28 16:33:50,040 DynoJedisClient - Starting connection pool for app conductor
[DEBUG] 2019-11-28 16:33:50,041 HostStatusTracker - New host up: ****
[INFO ] 2019-11-28 16:33:50,041 ConnectionPoolImpl - Getting Hosts from TokenMapSupplier
[INFO ] 2019-11-28 16:33:50,073 ConnectionPoolImpl - Adding host connection pool for host: Host [hostname=****, ipAddress=null, port=***, rack: us-east-1b, datacenter: us-east-1, status: Up, hashtag=null, password=masked]
[INFO ] 2019-11-28 16:33:50,074 HostConnectionPoolImpl - Priming connection pool for host:Host [hostname=****, ipAddress=null, port=***, rack: us-east-1b, datacenter: us-east-1, status: Up, hashtag=null, password=masked], with conns:10
[ERROR] 2019-11-28 16:33:50,167 HostConnectionPoolImpl - Failed to create connection
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
	at redis.clients.jedis.Protocol.process(Protocol.java:154)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:103)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1862)
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.open(JedisConnectionFactory.java:176)
	at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl$ConnectionPoolActive.createConnection(HostConnectionPoolImpl.java:313)
	at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl.createConnectionWithRetries(HostConnectionPoolImpl.java:221)
	at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl.reconnect(HostConnectionPoolImpl.java:193)
	at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl.primeConnections(HostConnectionPoolImpl.java:172)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.addHost(ConnectionPoolImpl.java:186)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl$2.call(ConnectionPoolImpl.java:519)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl$2.call(ConnectionPoolImpl.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[...]
```

Note that, on the same machine as the one conductor runs on, I am able to communicate with my redis instance using python and redis-py client with SSL turned on (cf. https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L650). That comforts me in thinking that the reason why conductor is unable to communicate with redis is the absence of SSL/TLS encryption.

I seem to understand that I cannot simply "switch on" SSL in conductor by adding some configuration variable in the `settings.properties` file. However, the java redis client used in conductor seems to be SSL-capable (cf. https://github.com/Netflix/dyno/blob/master/dyno-jedis/src/main/java/com/netflix/dyno/jedis/DynoJedisClient.java#L4759), so I am figuring I could  modify the way conductor uses `DynoJedisClient` to use its SSL capabilities.

Do you think that this approach makes sense? If so, I could use some advice :)
Or is there something that I missed in the configuration that could explain my problem?
A sample of my `settings.properties`:
```properties
# memory : The data is stored in memory and lost when the server dies.  Useful for testing or demo
# redis : non-Dynomite based redis instance
# dynomite : Dynomite cluster.  Use this for HA configuration.
db=redis

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=[host]:[port]:us-east-1b:[password]
#EC2_REGION=us-east-1
#EC2_AVAILABILITY_ZONE=us-east-1d

# Dynomite cluster name
#workflow.dynomite.cluster.name=dyno_cluster_name

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
#queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=[same as the one in workflow.dynomite.cluster.hosts]

# Elastic search stuffs:
[...]
```
There are quite a few commented things, because I want to know exactly which parameters are really necessary, which are not.

Thank you for your help!

**Comment by kishorebanala** [comment]
@DemisB You're on the right track. Here's how Conductor initialized db modules from provided configuration: https://github.com/Netflix/conductor/blob/master/server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java#L64L82

Provided you are using `db=redis`, The `DynomiteClusterModule` plugs in `DynomiteJedisProvider ` to `JedisCommands`: https://github.com/Netflix/conductor/blob/master/server/src/main/java/com/netflix/conductor/server/DynomiteClusterModule.java#L35/ 

`DynomiteJedisProvider` doesn't use `.withSSLSocketFactory(...)` in the `DynoJedisClient` builder: https://github.com/Netflix/conductor/blob/master/redis-persistence/src/main/java/com/netflix/conductor/jedis/DynomiteJedisProvider.java#L54.

Adding this through configuration should enable you to provide required SSL configuration. Please send us a PR if that works for you.

**Comment by DemisB** [comment]
Thank you @kishorebanala! Your directions helped me well :)
I managed to get something that works, cf. https://github.com/Netflix/conductor/pull/1441
