### ISSUE TITLE
NPE when worker queue is empty

### ISSUE THREAD

**Issue by Valarin** [Netflix/conductor#1477]
I have upgraded to v2.23.0 and started using `TaskRunnerConfigurer` instead of deprecated `WorkflowTaskCoordinator` for workers. However when there is nothing to poll I get NPE in the log.

`ERROR c.n.c.c.automator.TaskPollExecutor - Error when polling for tasks
java.lang.NullPointerException: null
	at com.netflix.conductor.client.http.TaskClient.populateTaskInput(TaskClient.java:176)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:125)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$0(TaskPollExecutor.java:101)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:42)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:101)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$null$0(TaskRunnerConfigurer.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	
...`

Newly used GET of `tasks/poll/{taskType}` returns 204 instead of previously used batch poll that returned 200. That leads to throwing `com.sun.jersey.api.client.UniformInterfaceException` in `
com.netflix.conductor.client.http.ClientBase#getForEntity(java.lang.String, java.lang.Object[], java.util.function.Function<com.sun.jersey.api.client.ClientResponse,T>, java.lang.Object...)`. 

Then task in `com.netflix.conductor.client.http.TaskClient#pollTask` ends up being null and `populateTaskInput` method ends up with NPE as stated above.

Not much really happens as catch block in `com.netflix.conductor.client.automator.TaskPollExecutor#pollAndExecute` handles the NPE, but log is full of errors and TaskPollErrorCount is all wrong.

**Comment by apanicker-nflx** [comment]
@Valarin Thanks for reporting the issue, we will release a fix for this soon.
Please follow this PR - https://github.com/Netflix/conductor/pull/1480 for the fix.

**Comment by Valarin** [comment]
Awesome, thanks @apanicker-nflx !

Any chance you could start sync to maven central? I guess you have that automated, but this time 2.4.1 did not get propagated - https://repo1.maven.org/maven2/com/netflix/conductor/conductor-client/
