### ISSUE TITLE
Elasticsearch Inquiry

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#153]
This is not an issue just an inquiry.  If there is another place I should post things like this please refer me to it.  I see on the documentation (https://netflix.github.io/conductor/server/) that Elasticsearch is a requirement and was wondering if it is possible to configure Conductor without Elasticsearch with Dynomite?  I see it is used to index workflows, so without it would server performance take too much of a hit?  When I give an invalid URL, I still seem to be able to query the API's, but all of the workflow executionGUI tabs throw an exception, with the server stack trace being:

[qtp10885570-31] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9200}]
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:326)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:223)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:295)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at com.netflix.conductor.dao.index.ElasticSearchDAO.search(ElasticSearchDAO.java:391)
	at com.netflix.conductor.dao.index.ElasticSearchDAO.searchWorkflows(ElasticSearchDAO.java:329)
	at com.netflix.conductor.service.ExecutionService.search(ExecutionService.java:284)
	at com.netflix.conductor.server.resources.WorkflowResource.search(WorkflowResource.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...

**Comment by xsank** [comment]
@cquon how did you fix that?

**Comment by cquon** [comment]
I just used elastic search :)

**Comment by saidatta** [comment]
@xsank @cquon I think he might be referring to the exception stack trace?
