### ISSUE TITLE
NullPointerException when polling

### ISSUE THREAD

**Issue by markusa380** [Netflix/conductor#1550]
After some changes to our service we weren't able to poll anything anymore during the integration test, so we decided to check the logs of the server:

```
111292 [qtp131837504-52] ERROR com.netflix.conductor.service.ExecutionService  - Error polling for task: conductor-utils-test from worker: conductor-utils-test-worker in domain: null, count: 1
redis.clients.jedis.exceptions.JedisException: java.lang.NullPointerException
        at com.netflix.conductor.jedis.JedisMock.zrangeByScore(JedisMock.java:1006)
        at com.netflix.conductor.dyno.DynoProxy.zrangeByScore(DynoProxy.java:88)
        at com.netflix.conductor.dao.dynomite.RedisExecutionDAO.exceedsInProgressLimit(RedisExecutionDAO.java:276)
        at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.exceedsInProgressLimit(ExecutionDAOFacade.java:304)
        at com.netflix.conductor.service.ExecutionService.poll(ExecutionService.java:136)
        at com.netflix.conductor.service.ExecutionService.getLastPollTask(ExecutionService.java:161)
        at com.netflix.conductor.service.TaskServiceImpl.poll(TaskServiceImpl.java:72)
        at com.netflix.conductor.service.TaskServiceImpl$$EnhancerByGuice$$79bb704a.CGLIB$poll$19(<generated>)
        at com.netflix.conductor.service.TaskServiceImpl$$EnhancerByGuice$$79bb704a$$FastClassByGuice$$aff4b283.invoke(<generated>)
        at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
        at com.netflix.conductor.interceptors.ServiceInterceptor.invoke(ServiceInterceptor.java:52)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
        at com.netflix.conductor.service.TaskServiceImpl$$EnhancerByGuice$$79bb704a.poll(<generated>)
        at com.netflix.conductor.server.resources.TaskResource.poll(TaskResource.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:82)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.rarefiedredis.redis.RedisMock.zrangebyscore(RedisMock.java:1753)
        at com.netflix.conductor.jedis.JedisMock.zrangeByScore(JedisMock.java:1003)
        ... 63 more

```

What could this mean?

**Comment by kishorebanala** [comment]
@markusa380 So, the poll logic also checks for concurrent execution limits before returning the tasks. It's not clear from the logs why exceedsInProgressLimit is failing with NPE. Is this reproducible? Would you be able to debug and find where it ends with NPE?

**Comment by markusa380** [comment]
Unfortunately I have meanwhile left the project where Conductor has been used.

**Comment by kishorebanala** [comment]
Closing this for now. Please feel free to reopen if this can be reproduced.
