### ISSUE TITLE
Race condition: NPE in org.elasticsearch.action.bulk.BulkRequest.validate()

### ISSUE THREAD

**Issue by skissane** [Netflix/conductor#1553]
### Reproduce steps

1. Checkout latest conductor master (I tested with `9d44897f37450fb7ad602bd016ff9a5813bee98c`, but same issue occurs with older versions)
2. Run `./gradlew build -x test`
3. `java -jar ./server/build/libs/conductor-server-2.26.0-SNAPSHOT-all.jar`
4. Run three copies of the `conductor-test.py` script (given below) simultaneously

### Results

After a while, the test scripts start to hang and this error happens in log:
```
[ERROR] 2020-03-02 12:21:40,531 RetryUtil - Operation 'indexObject:Bulk Indexing task' failed after retrying 3 times, retry limit 3
java.lang.NullPointerException
	at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:604)
	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:46)
	at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:250)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.lambda$updateWithRetry$10(ElasticSearchDAOV5.java:570)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:117)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.updateWithRetry(ElasticSearchDAOV5.java:569)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexBulkRequest(ElasticSearchDAOV5.java:561)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexObject(ElasticSearchDAOV5.java:555)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexTask(ElasticSearchDAOV5.java:403)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateWorkflow(ExecutionDAOFacade.java:232)
	at com.netflix.conductor.core.execution.WorkflowExecutor.completeWorkflow(WorkflowExecutor.java:634)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:964)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1014)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:398)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:328)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:153)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:130)
```

### Hypothesised Cause

I think the problem is that the ElasticSearch `BulkRequestBuilder` is not thread-safe, and Conductor is using it from multiple threads. This can result in one of the elements of the requests list being set to null, which then causes the above NPE. When I modify the ElasticSearchDAOV5 to replace  `BulkRequestBuilder` with a `BulkRequestBuilderWrapper`, which makes all calls to `BulkRequestBuilder` be inside a `synchronized(){}` block, this problem goes away.

### Notes on configuration

- Same issue occurs with both ES5 and ES6 persistence modules
- Maybe we are also hanging when in-memory mode is on due to too many workflows in memory? However, I reproduced the same problem using postgres persistence enabled, which would rule out that issue

### Test script

```python
#!/usr/bin/env python3
from http.client import HTTPConnection
from uuid import uuid4
import json

testWorkflowId = 'load-test-workflow-' + str(uuid4())

hc = HTTPConnection('localhost:8080')
hdrs = {
        'Content-Type': 'application/json',
         'Accept': 'application/json'
}

json_body = {
        "name":testWorkflowId,
        "ownerEmail":"none@example.com",
        "tasks":[
                {
                  "name": "LAMBDA_TASK",
                  "taskReferenceName": "lambda_test",
                  "type": "LAMBDA",
                  "inputParameters": {
                      "scriptExpression": "return {}"
                  }
                }
        ]
}
hc.request(method='POST',url='/api/metadata/workflow',body=json.dumps(json_body),headers=hdrs)
x = hc.getresponse()
body = x.read().decode('utf8')
if x.status != 204:
        raise Exception(body)

while True:
        wfids = []
        for i in range(0,100):
                json_body = {}
                hc.request(method='POST',url='/api/workflow/' + testWorkflowId,body=json.dumps({}),headers={'Content-Type': 'application/json'})
                x = hc.getresponse()
                body = x.read().decode('utf8')
                if x.status != 200:
                        raise Exception(body)
                wfids += [body]
                print("SUBMIT|%s" % body)
                
        for wfid in wfids:
                hc.request(method='GET',url='/api/workflow/' + wfid,headers={'Content-Type': 'application/json'})
                x = hc.getresponse()
                body = x.read().decode('utf8')
                if x.status != 200:
                        raise Exception(body)
                #print(body)
                body = json.loads(body)
                status = body['status']
                createTime = body['createTime']
                endTime = body['endTime']
                duration = endTime - createTime
                print("RESULT|%s|%s|%d" % (wfid, status, duration))
```

**Comment by apanicker-nflx** [comment]
@skissane Thanks for the detailed error report and the PR for resolution.
