### ISSUE TITLE
Got errors when boot conductor server via Mysql

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1601]
Caused by: org.flywaydb.core.api.FlywayException: Schema `conductor` contains a failed migration to version 3 !
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:218)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.flywayMigrate(MySQLDataSourceProvider.java:80)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.get(MySQLDataSourceProvider.java:30)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.get(MySQLDataSourceProvider.java:15)

**I used local mysql server, and my server.properties as below:**

db=mysql
jdbc.url=jdbc:mysql://127.0.0.1:3306/conductor?createDatabaseIfNotExist=true&useSSL=false
jdbc.username=salt
jdbc.password=salt
conductor.mysql.connection.pool.size.max=10
conductor.mysql.connection.pool.idle.min=2

**Comment by Nafalgar** [comment]
Did you end up finding what the problem was, I am having the same issue.

**Comment by andyyumiao** [comment]
> Did you end up finding what the problem was, I am having the same issue.

@Nafalgar this is a MySQL syntax problem, the dev branch have fixed this issue, you can switch to dev branch then try again.
or you can also change the file **V3__queue_add_priority.sql** to: **ALTER TABLE `queue_message` ADD COLUMN `priority` TINYINT DEFAULT 0 AFTER `message_id`;**
