### ISSUE TITLE
Redis:  Unexpected end of stream

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1613]
When used redis as the storage,  I just meet the error : **Unexpected end of stream**., pls note the error stack: **Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)**, it seems that redis server has output buffer limit, so redis server sometimes will close the client connection, and conductor redis persistence will not try to establish the connection again. how to fix this now? i think may be we need retry mechanism for conductor redis client?

**Below is the complete error stack:**
ERROR] 2020-03-28 19:44:15,864 RedisMetadataDAO - refresh TaskDefs failed 
com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=xxx.xxx.xxx.xxx, ipAddress=null, port=6379, rack: us-east-1e, datacenter: us-east-1, status: Up, hashtag=null, password=masked], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:141)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:310)
        at com.netflix.dyno.jedis.DynoJedisClient.d_hscan(DynoJedisClient.java:798)
        at com.netflix.dyno.jedis.DynoJedisClient.hscan(DynoJedisClient.java:793)
        at com.netflix.conductor.dyno.DynoProxy.hgetAll(DynoProxy.java:176)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getAllTaskDefs(RedisMetadataDAO.java:123)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.refreshTaskDefs(RedisMetadataDAO.java:90)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
        at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
        at redis.clients.jedis.Protocol.process(Protocol.java:154)
        at redis.clients.jedis.Protocol.read(Protocol.java:219)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
        at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:276)
        at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:280)
        at redis.clients.jedis.Jedis.hscan(Jedis.java:3231)
        at redis.clients.jedis.Jedis.hscan(Jedis.java:3223)
        at com.netflix.dyno.jedis.DynoJedisClient$33.execute(DynoJedisClient.java:802)
        at com.netflix.dyno.jedis.DynoJedisClient$33.execute(DynoJedisClient.java:799)
        at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:128)
        ... 13 more

**Comment by apanicker-nflx** [comment]
Can you try configuring the jedis client that you are using with retries to see if that helps?

**Comment by andyyumiao** [comment]
> Can you try configuring the jedis client that you are using with retries to see if that helps?

OK, @apanicker-nflx , does it support redis retries configuration in server.properties?

**Comment by apanicker-nflx** [comment]
The redis retries are not abstracted out by Conductor, and you would need to check redis properties. If this is a redis client-side property, setting this in `server.properties` would work, else this would need to be set on the redis-server.

**Comment by iuprade** [comment]
I am having same error. Feeding below config DynoJedisClient. I have simple redis cluster with 2 nodes, multi AZ, failover enabled running with default 5.0 parameter group config. Please suggest what could been missing here.

 ```
   ConnectionPoolConfigurationImpl connectionPoolConfiguration =
        new ConnectionPoolConfigurationImpl(configuration.getClusterName())
            .withTokenSupplier(tokenMapSupplier)
            .setLocalRack(configuration.getAvailabilityZone())
            .setLocalDataCenter(configuration.getRegion())
            .setSocketTimeout(0)
            .setConnectTimeout(0)
            .setRetryPolicyFactory(new RetryNTimes.RetryFactory(3))
            .setMaxConnsPerHost(configuration.getMaxConnectionsPerHost());
```

When performing manual failover connection switches back to new primary but it takes almost more than 2 minutes.
