### ISSUE TITLE
ES5 Persistence Rest Client, AWS Elasticsearch

### ISSUE THREAD

**Issue by kushalhalder** [Netflix/conductor#1634]
I have been using the following configuration for AWS Elasticsearch connection with Rest client

```
workflow.elasticsearch.instanceType=EXTERNAL

# Transport address to elasticsearch
workflow.elasticsearch.version=5-rest
workflow.elasticsearch.url=https://xxxx.ap-south-1.es.amazonaws.com
```

```
workflow.elasticsearch.instanceType=EXTERNAL

# Transport address to elasticsearch
workflow.elasticsearch.version=5
workflow.elasticsearch.url=https://xxxx.ap-south-1.es.amazonaws.com:443
```

```
workflow.elasticsearch.instanceType=external

# Transport address to elasticsearch
workflow.elasticsearch.version=5
workflow.elasticsearch.url=https://xxxx.ap-south-1.es.amazonaws.com:443
```

None of them seem to be working. All throw the following:
```
conductor-server_1  | Error setting up elasticsearch index
conductor-server_1  | java.io.IOException: listener timeout after waiting for [30000] ms
conductor-server_1  | 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)
conductor-server_1  | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
conductor-server_1  | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
conductor-server_1  | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:170)
conductor-server_1  | 	at com.netflix.conductor.dao.es5.index.ElasticSearchRestDAOV5.waitForHealthyCluster(ElasticSearchRestDAOV5.java:257)
conductor-server_1  | 	at com.netflix.conductor.dao.es5.index.ElasticSearchRestDAOV5.setup(ElasticSearchRestDAOV5.java:216)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.BootstrapUtil.setupIndex(BootstrapUtil.java:49)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.Main.main(Main.java:50)
```

Any help in the above is appreciated.

**Comment by manan164** [comment]
Looks like it is not reachable. Can you try with http:// or port number is different. Try to telnet from the conductor box and verify

**Comment by kushalhalder** [comment]
```
curl https://xxxxx.ap-south-1.es.amazonaws.com:443
{
  "name" : "xx",
  "cluster_name" : "xx",
  "cluster_uuid" : "xx",
  "version" : {
    "number" : "5.6.17",
    "build_hash" : "59bb0dc",
    "build_date" : "2020-01-03T11:28:23.851Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```
Curl from the EC2 machine works. 
I have launched the conductor server in the same EC2 machine using docker.

**Comment by manan164** [comment]
Is cluster health green?

**Comment by kushalhalder** [comment]
It is Yellow. But that is because it is with 1 node.

**Comment by kushalhalder** [comment]
No Success with http and port 80 too. Curl works on it.

**Comment by manan164** [comment]
It should be green. Otherwise, it won't work. It is waiting for the cluster to be green. Change this [property](https://github.com/Netflix/conductor/blob/master/es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java#L31) to yellow

**Comment by kushalhalder** [comment]
I'll give it a shot.

**Comment by kushalhalder** [comment]
The ES status to green worked. Thanks. Closing the issue
