### ISSUE TITLE
Seeing lots of 'java.io.exception: Transport endpoint is not connected' errors in new code

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1665]
Has anyone else seen these errors in your logs after getting one of the more recent releases of Conductor? Tough to tell where in the codebase this is coming from...

`[WARN ] 2020-04-30 12:19:27,373 AbstractConnector - 
 	java.io.IOException: Transport endpoint is not connected 
 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) 
 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) 
 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) 
 	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385) 
 	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:701) 
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) 
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) 
 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by rickfish** [comment]
I also noticed that netty-codec is a recent dependency. What is it used for and is it possible that it is causing the exception?

**Comment by apanicker-nflx** [comment]
Please reopen if still relevant.
