### ISSUE TITLE
Error when use redis version 2.8.19 

### ISSUE THREAD

**Issue by walrus1967** [Netflix/conductor#1703]
[WARN ] 2020-05-06 03:55:44,342 ConnectionPoolImpl - Received FatalConnectionException; closing connection {datastorePort=22122, port=6379, host=****** to host Host [hostname=******, ipAddress=null, port=6379, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=masked]
[ERROR] 2020-05-06 03:55:44,348 WorkflowSweeper - Error when sweeping workflow
java.lang.RuntimeException: com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=******, ipAddress=null, port=6379, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=masked], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
	at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:343)
	at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:192)
	at com.netflix.conductor.core.execution.WorkflowSweeper.lambda$init$0(WorkflowSweeper.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=******, ipAddress=null, port=6379, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=masked], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR syntax error

**Comment by apanicker-nflx** [comment]
From a cursory look at the error stack trace, this looks like a connection error with Dynomite. Can you verify if connections are allowed between the server and dynomite instance?
