### ISSUE TITLE
ES5 Broken in Docker Deployment of Server 2.27.0

### ISSUE THREAD

**Issue by demichej** [Netflix/conductor#1716]
We are using ES5 still, and we attempted to upgrade to 2.27.0. Everything built fine with the docker-compose (albeit the > Task :conductor-es6-persistence:shadowJar taking a VERY long time)....... but when we start the server now, we get this

`
Using config file: /app/config/config.properties
Using log4j config /app/config/log4j.properties
0    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - Starting conductor server using MySQL data store.
9    [main] WARN  com.netflix.conductor.bootstrap.ModulesProvider  - Starting locking module using Noop Lock.
494  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: HTTP
495  [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
502  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: KAFKA_PUBLISH
502  [main] INFO  com.netflix.conductor.contribs.kafka.KafkaPublishTask  - KafkaTask initialized...
504  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: JSON_JQ_TRANSFORM
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/client/Client
	at com.netflix.conductor.elasticsearch.ElasticSearchModule.configure(ElasticSearchModule.java:28)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.client.Client
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
`

Any help would be great. Thanks.

**Comment by demichej** [comment]
Ah I see, I think it has always been that you build either es5 OR es6, not both at the same time. 

@apanicker-nflx it looks like both are added. I think that this can result in jar conflicts possibly: 
https://github.com/Netflix/conductor/commit/167180ad517ef8d65679e2094ad3a63f4920cd5b#diff-88b7c47e47b8ee65263b6784b86fa0a7

It's always been that if you want to use ES6, you had to switch ES5 -> ES6 manually (https://github.com/Netflix/conductor/tree/master/es6-persistence)

**Comment by apanicker-nflx** [comment]
@demichej This should be fixed in [v2.27.2](https://github.com/Netflix/conductor/releases/tag/v2.27.2). 
JAR conflicts are prevented here by shading the ES6 dependency.
