### ISSUE TITLE
Do conductor-server 2.27.1 supports java 11 ?

### ISSUE THREAD

**Issue by osamakhan-jmi** [Netflix/conductor#1731]
I'm getting below error on building with java 11:

java -jar conductor-server-2.27.1-all.jar 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/okappzillon1/conductor-server-2.27.1-all.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO ] 2020-06-08 08:35:32,837 ModulesProvider - Starting conductor server using in memory data store.
[WARN ] 2020-06-08 08:35:32,840 ModulesProvider - Starting locking module using Noop Lock.
[INFO ] 2020-06-08 08:35:32,996 SystemTaskWorkerCoordinator - Adding the queue for system task: HTTP
[INFO ] 2020-06-08 08:35:32,996 HttpTask - HttpTask initialized...
[INFO ] 2020-06-08 08:35:32,999 SystemTaskWorkerCoordinator - Adding the queue for system task: KAFKA_PUBLISH
[INFO ] 2020-06-08 08:35:33,000 KafkaPublishTask - KafkaTask initialized...
[INFO ] 2020-06-08 08:35:33,000 SystemTaskWorkerCoordinator - Adding the queue for system task: JSON_JQ_TRANSFORM
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/client/Client
	at com.netflix.conductor.elasticsearch.ElasticSearchModule.configure(ElasticSearchModule.java:28)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.client.Client
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Comment by apanicker-nflx** [comment]
The build failure is fixed in [v2.27.2](https://github.com/Netflix/conductor/releases/tag/v2.27.2)
