### ISSUE TITLE
StackOverflowError when terminating workflow that has a subworkflow

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1743]
There is a scenario that we have where terminating a workflow that has a subworkflow causes a StackOverflowError. This happens because the terminateWorkflow method goes thru its list of tasks and cancels the subworkflow task which calls terminateWorkflow on the subworkflow and then decide() is called with the parent workflow, etc. I am trying to come up with a simple way to reproduce it but it isn't easy as this scenario unfolds with a workflow that has about 20 subworkflows and I don't know if it something specific about one of the subworkflows.

The solution is to update the workflow with TERMINATED status *before* the list of tasks is checked in WorkflowExecutor. But I don't know that this won't cause other issues - maybe the update of the workflow was done after going thru the task list for a reason?

Anyway, I will be submitting a PR for this but I am creating this issue in case someone is aware of this and already has a solution...

**Comment by rickfish** [comment]
Honed in on the scenario more. It is when DELETE /workflow/<workflowId> is called on a parent workflow that has a SUB_WORKFLOW task that is IN_PROGRESS. 

What causes the StackOverflowError (parent is workflow id 1, subworkflow is workflow id 1a):
1. terminateWorkflow(1)
1.a. (workflowid 1a).cancel()
1.a.1 terminateWorkflow(1a)
1.a.1.a updateWorkflow(1a) with status TERMINATED
1.a.1.b decide(1) for parent - (updateWorkflow() not yet called on parent so it is still RUNNING)
1.a.1.b.1 DeciderService.decide(1)
1.a.1.b.1.a pendingTask (1a) is now TERMINATED so !isSuccessful()
1.a.1.b.1.a.1 retry task (1a)
1.a.1.b.1.a.1.a task status is not retryable, throw TerminateWorkflowException
back to step 1 - parent workflow still has not been updated to TERMINATED, so endless loop.

My PR will update parent right away in terminateWorkflow(), then go thru the tasks. Not sure if this causes other issues, i.e. maybe it is updated at the end for a reason...

**Comment by rickfish** [comment]
More information. I think the problem might lie in that the SUB_WORKFLOW task is IN_PROGRESS even though the actual subworkflow is TERMINATED. If the SUB_WORKFLOW task was also TERMINATED, step 1a would never happen.
So I need to find out what would cause this out-of-sync situation.

**Comment by kishorebanala** [comment]
Hey @rickfish, Thanks for reporting this. Please let us know when you have an example to reproduce this. I'd be glad to debug.

**Comment by demichej** [comment]
@rickfish (and @kishorebanala) did you get a fix for this at all? We're seeing what looks to be some kind of infinite loop that has to do with Subworkflows and termination thereof. Also, we are unable to Terminate the parent workflow in this state.

`2325527593 [pool-17-thread-5] INFO  com.netflix.conductor.core.execution.WorkflowExecutor  - Execution terminated of workflow: 9f2fcf5d-fce3-44b3-90e6-2cf8e5afe375
com.netflix.conductor.core.execution.TerminateWorkflowException: Invalid or Missing Street Address
        at com.netflix.conductor.core.execution.DeciderService.retry(DeciderService.java:397)
        at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:183)
        at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:112)
        at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:961)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:727)
        at com.netflix.conductor.core.execution.tasks.SubWorkflow.cancel(SubWorkflow.java:158)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:698)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminate(WorkflowExecutor.java:1439)
        at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1031)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:727)
        at com.netflix.conductor.core.execution.tasks.SubWorkflow.cancel(SubWorkflow.java:158)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:698)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminate(WorkflowExecutor.java:1439)
        at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1031)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:727)
        at com.netflix.conductor.core.execution.tasks.SubWorkflow.cancel(SubWorkflow.java:158)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:698)
        at com.netflix.conductor.core.execution.WorkflowExecutor.terminate(WorkflowExecutor.java:1439)`

**Comment by rickfish** [comment]
We spent a lot of time debugging this. As mentioned previously, we found that a StackOverflowError would happen if a SUB_WORKFLOW task is IN_PROGRESS when the underlying subworkflow was FAILED. The problem was that we could not get to the bottom of what use case in Conductor could cause this out-of-sync condition to happen. So right now we added some code in WorkflowExecutor in the terminateWorkflow() method (below). I will not be contributing this back because it is a patch. I was hoping to find the root cause and provide a PR for that but, like I said, we couldn't find the root cause.

```
            for (Task task : tasks) {
            	/*
            	 * Fix up out-of-sync conditions where SUB_WORKFLOW task status is IN_PROGRESS while the actual subworkflow is terminal.
            	 */
				if(TaskType.SUB_WORKFLOW.name().equals(task.getTaskType()) && !task.getStatus().isTerminal()) {
					String subWorkflowId = task.getSubWorkflowId();
					if(subWorkflowId != null) {
						Workflow subWorkflow = executionDAOFacade.getWorkflowById(subWorkflowId, false);
						if(subWorkflow != null && subWorkflow.getStatus().isTerminal()) {
							task.setStatus(WorkflowStatus.COMPLETED == subWorkflow.getStatus() ? Task.Status.COMPLETED : Task.Status.FAILED);
							task.setReasonForIncompletion("SUB_WORKFLOW task status was not terminal while the actual subworkflow was terminal. Fixing that by making the task status equate to subworkflow status.");
						    executionDAOFacade.updateTask(task);
						}
					}
				}
                if (!task.getStatus().isTerminal()) {
etc, etc

```

BTW, we also found that the same team in our company whose workflows somehow cause this condition also has workflows that can spawn another instance of themselves (doing a sort of do_while functionality) and in some cases were more than 5,000 levels deep. That also caused StackOverflowErrors on not only workflow termination but other use cases as well. That would have to be fixed by increasing the JVM stacksize but we have not done that yet.
