### ISSUE TITLE
error while running command -> $ docker-compose up

### ISSUE THREAD

**Issue by bhawani021** [Netflix/conductor#1946]
Tried multiple times getting same error.
```
$ docker-compose up
Building conductor-server
Step 1/16 : FROM openjdk:8-jdk AS builder
 ---> 3edb5f36304e
Step 2/16 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> d129fd898e8f
Step 3/16 : COPY . /conductor
 ---> Using cache
 ---> 4a589c800189
Step 4/16 : WORKDIR /conductor
 ---> Using cache
 ---> 1312c295574e
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in 3b30d5f042fb
Downloading https://services.gradle.org/distributions/gradle-4.8.1-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 1
```

**Comment by wixaw** [comment]
I have same probleme with  an other project, i think is an error with openjdk or gradle,  i follow this

**Comment by aravindanr** [comment]
@bhawani021 Is this still an issue? `docker-compose up` works as expected and the stacktrace looks like a network issue.

**Comment by SaumitraChaskar** [comment]
I am facing the same problem.

Stacktrace:

Building conductor-server
Step 1/16 : FROM openjdk:8-jdk AS builder
 ---> 7f5d492e2c8a
Step 2/16 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> 6fdeceb32892
Step 3/16 : COPY . /conductor
 ---> Using cache
 ---> 4ef0d55e2fa5
Step 4/16 : WORKDIR /conductor
 ---> Using cache
 ---> 7ed5fb063f41
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in 080fede4a37a
/usr/bin/env: ‘sh\r’: No such file or directory
ERROR: Service 'conductor-server' failed to build : The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 127

I am using a windows machine.

**Comment by kishorebanala** [comment]
@SaumitraChaskar We couldn't reproduce this. `returned a non-zero code` appears to be Docker configuration issue. Hope this helps: https://stackoverflow.com/questions/31876031/the-command-bin-sh-c-returned-a-non-zero-code-127

Please feel free to reopen if the issue still persists and / or if we need to tweak anything in Conductor.
