### ISSUE TITLE
Errror while running conductor 3.0 beta with postgresDB

### ISSUE THREAD

**Issue by bhawani021** [Netflix/conductor#2006]
```
20238 [pool-11-thread-1] ERROR com.netflix.conductor.core.execution.WorkflowSweeper [] - Error when sweeping workflow
com.netflix.conductor.core.exception.ApplicationException: BACKEND_ERROR - HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransactionWithOutErrorPropagation(PostgresBaseDAO.java:177) ~[conductor-postgres-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.postgres.dao.PostgresQueueDAO.pollMessages(PostgresQueueDAO.java:97) ~[conductor-postgres-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.postgres.dao.PostgresQueueDAO.pop(PostgresQueueDAO.java:79) ~[conductor-postgres-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.core.execution.WorkflowSweeper.lambda$init$0(WorkflowSweeper.java:77) ~[conductor-core-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-3.4.5.jar!/:?]
	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransactionWithOutErrorPropagation(PostgresBaseDAO.java:162) ~[conductor-postgres-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	... 10 more
=================================================
```

I am using in my properties file

db=postgres

**Comment by bhawani021** [comment]
```
5429 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - HikariPool-1 - configuration:
5435 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - allowPoolSuspension.............false
5435 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - autoCommit......................false
5435 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - catalog.........................none
5435 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - connectionInitSql...............none
5436 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - connectionTestQuery.............none
5436 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - connectionTimeout...............1800000
5436 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - dataSource......................none
5436 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - dataSourceClassName.............none
5436 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - dataSourceJNDI..................none
5437 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - dataSourceProperties............{password=<masked>}
5437 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - driverClassName.................none
5437 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - exceptionOverrideClassName......none
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - healthCheckProperties...........{}
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - healthCheckRegistry.............none
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - idleTimeout.....................600000
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - initializationFailTimeout.......1
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - isolateInternalQueries..........false
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - jdbcUrl.........................jdbc:postgresql://localhost:5432/testdb2?currentSchema=conductor
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - leakDetectionThreshold..........0
5438 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - maxLifetime.....................1800000
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - maximumPoolSize.................10
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - metricRegistry..................none
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - metricsTrackerFactory...........none
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - minimumIdle.....................1
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - password........................<masked>
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - poolName........................"HikariPool-1"
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - readOnly........................false
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - registerMbeans..................false
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - scheduledExecutor...............none
5439 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - schema..........................none
5440 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - threadFactory...................com.google.common.util.concurrent.ThreadFactoryBuilder$1@d29f28
5440 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - transactionIsolation............default
5440 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - username........................"postgres"
5440 [main] DEBUG com.zaxxer.hikari.HikariConfig [] - validationTimeout...............5000
5442 [main] INFO  com.zaxxer.hikari.HikariDataSource [] - HikariPool-1 - Starting...
```

**Comment by bhawani021** [comment]
settings in properties file

```
db=postgres
jdbc.url=jdbc:postgresql://localhost:5432/testdb2?currentSchema=conductor
jdbc.username=postgres
jdbc.password=postgres
flyway.enabled:true
```

When I run conductor it will create schema in postgresDB and will close connection.

**Comment by bhawani021** [comment]
8832 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsatisfied dependency expressed through method 'flyway' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.jdbc.DataSourceProperties]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/dao/DataAccessException

**Comment by apanicker-nflx** [comment]
@bhawani021 Thanks for reporting this issue. This is caused by the FlywayAutoConfiguration which SpringBoot instantiates because flyway is on the classpath. You would want to disable this by setting `spring.flyway.enabled:false` similar to how it is done in the [test here.](https://github.com/Netflix/conductor/blob/3.0/test-harness/src/test/java/com/netflix/conductor/test/integration/grpc/postgres/PostgresGrpcEndToEndTest.java#L35) 

We would appreciate it if you could contribute a pull request to change the manual invocation of flyway in the Postgres and MySQL modules and rely on SpringBoot for this.
