### ISSUE TITLE
Conductor 3.0 -> what configuration is required  to connect with Standalone Redis server instance

### ISSUE THREAD

**Issue by bhawani021** [Netflix/conductor#2019]
I have shared Redis instance (standalone remote). I need help in understanding configuration so that Conductor 3.0 can connect to Redis DB.
 
While connecting with DB conductor is throwing error
```
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR command is not allowed
```

**Comment by bhawani021** [comment]
Configuration
```
db=redis_cluster
workflow.indexing.enabled=true
workflow.dynomite.cluster.hosts=<HOST>:<PORT>
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor
queues.dynomite.threads=10
```

DB connection
```
redis.clients.jedis.JedisCluster cmd = new redis.clients.jedis.JedisCluster(
                new HostAndPort("<HOST>", <PORT>),
                1000,
                1000,
                3,
                "<PASSWORD>",
                genericObjectPoolConfig);
```
Error
```
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR command is not allowed
	at redis.clients.jedis.Protocol.processError(Protocol.java:132) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:166) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:220) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3435) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterNodesAndSlots(JedisClusterInfoCache.java:73) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:61) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:33) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:24) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:19) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:27) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:60) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:114) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:60) ~[jedis-3.1.0.jar!/:?]
	at com.netflix.conductor.redis.config.RedisClusterConfiguration.createJedisCommands(RedisClusterConfiguration.java:100) ~[conductor-redis-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.redis.config.JedisCommandsConfigurer.jedisCommands(JedisCommandsConfigurer.java:23) ~[conductor-redis-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.redis.config.RedisClusterConfiguration.jedisCommands(RedisClusterConfiguration.java:31) ~[conductor-redis-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
```

**Comment by aravindanr** [comment]
@bhawani021 Please get the latest from `3.0` and set 

```
conductor.db.type=redis_standalone
conductor.redis.hosts=<HOST>:<PORT>
```

See [CHANGELOG.MD](https://github.com/Netflix/conductor/blob/3.0/CHANGELOG.md) for the new property names.

**Comment by jeremy-l-ford** [comment]
I think a condition needs to be added to the AnyRedisCondition class to handle the new redis_standalone db type.  Also, I think the dynomite one should be removed.

**Comment by aravindanr** [comment]
Good catch. `redis_standalone` is added to `AnyRedisCondition` in an upcoming PR. Why do you think `dynomite` should be removed?

**Comment by jeremy-l-ford** [comment]
Sorry.  Misread something.  Looks like that would still be needed.
