### ISSUE TITLE
when i run my work i got "MIME media type application/octet-stream was not found"

### ISSUE THREAD

**Issue by liangguohun** [Netflix/conductor#2073]
when i run my work i got "MIME media type application/octet-stream was not found" for version 3.0

```
The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader
application/octet-stream ->
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.RenderedImageProvider

二月 03, 2021 8:01:56 下午 com.sun.jersey.api.client.ClientResponse getEntity
严重: The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader
application/octet-stream ->
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.RenderedImageProvider

20:01:56.199 [pool-2-thread-2] ERROR com.netflix.conductor.client.http.ClientBase - Unable to invoke Conductor API with uri: http://192.168.1.14:8080/api/tasks/poll/managerRatify?workerid=DESKTOP-BOMJA8F, runtime exception occurred
com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.netflix.conductor.common.metadata.tasks.Task, and Java type class com.netflix.conductor.common.metadata.tasks.Task, and MIME media type application/octet-stream was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:630)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.netflix.conductor.client.http.ClientBase.lambda$getForEntity$2(ClientBase.java:165)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:181)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:165)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:126)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$1(TaskPollExecutor.java:103)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:42)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:103)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$null$0(TaskRunnerConfigurer.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:01:56.199 [pool-2-thread-1] ERROR com.netflix.conductor.client.http.ClientBase - Unable to invoke Conductor API with uri: http://192.168.1.14:8080/api/tasks/poll/leaderRatify?workerid=DESKTOP-BOMJA8F, runtime exception occurred
com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.netflix.conductor.common.metadata.tasks.Task, and Java type class com.netflix.conductor.common.metadata.tasks.Task, and MIME media type application/octet-stream was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:630)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.netflix.conductor.client.http.ClientBase.lambda$getForEntity$2(ClientBase.java:165)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:181)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:165)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:126)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$1(TaskPollExecutor.java:103)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:42)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:103)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$null$0(TaskRunnerConfigurer.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:01:56.200 [pool-2-thread-2] DEBUG com.netflix.conductor.client.automator.PollingSemaphore - Completed execution; releasing permit
20:01:56.200 [pool-2-thread-1] DEBUG com.netflix.conductor.client.automator.PollingSemaphore - Completed execution; releasing permit
20:01:56.200 [pool-2-thread-2] ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks
com.netflix.conductor.client.exceptions.ConductorClientException: Unable to invoke Conductor API with uri: http://192.168.1.14:8080/api/tasks/poll/managerRatify?workerid=DESKTOP-BOMJA8F, runtime exception occurred
	at com.netflix.conductor.client.http.ClientBase.handleRuntimeException(ClientBase.java:244)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:188)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:165)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:126)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$1(TaskPollExecutor.java:103)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:42)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:103)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$null$0(TaskRunnerConfigurer.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.netflix.conductor.common.metadata.tasks.Task, and Java type class com.netflix.conductor.common.metadata.tasks.Task, and MIME media type application/octet-stream was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:630)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.netflix.conductor.client.http.ClientBase.lambda$getForEntity$2(ClientBase.java:165)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:181)
	... 13 common frames omitted

```

**Comment by aravindanr** [comment]
This might be a possible bug, we will look into it.
