### ISSUE TITLE
Couldn't Start Local Server

### ISSUE THREAD

**Issue by andyzhaozhao** [Netflix/conductor#2076]
I am watching the doc https://netflix.github.io/conductor/architecture/ 
There is an error when running :../gradlew server 
```
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at com.netflix.conductor.jetty.server.JettyServer.start(JettyServer.java:78)
        at com.netflix.conductor.bootstrap.Main.lambda$main$0(Main.java:74)
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:72)
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
        ... 10 more

> Task :conductor-server:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-server:server'.
```
**I have not use the port 8080, the 8080 is started by Conductor it self .**

**Comment by kishorebanala** [comment]
@andyzhaozhao Can you confirm if some other process is already using the port 8080? (For eg., in linux: `sudo lsof -n -i :8080 | grep LISTEN`).

If you still see port 8080 is open and that Conductor server is unable to start, can you provide the steps to reproduce please. Thanks!

**Comment by andyzhaozhao** [comment]
@kishorebanala I run it on windows10 . I am sure there's no other process using the port 8080.  My steps:

**Comment by kishorebanala** [comment]
I couldn't reproduce this when I tried locally. Can you tell us what the port 8080 is doing when you see `Caused by: java.net.BindException: Address already in use: bind`? 

Alternatively, you can try using docker compose files we have to run your local server.

**Comment by liangguohun** [comment]
i got this problem too for the master branch.

**Comment by liangguohun** [comment]
```
ERROR: for conductor-server  Cannot start service conductor-server: driver failed programming external connectivity on endpoint docker_conductor-server_1 (7d85ec407fb565773d3a691fe02c67d525c047b1ed813c8b160c964dbb3c4017): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```
this is use docker-compoe , and the config  of `java -jar conductor-server-*-all.jar $config_file $log4j_file` never work, for days i got that, the "*" isn't work, but the config_file not work too, because default run in memery, the docker-compose use the component of dynomite

**Comment by liangguohun** [comment]
use docker ps found that 'hardcore_nobel' use the port, but the config_file don't work for branch master and 3.0
