### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by soup11** [Netflix/conductor#21]
when I build the conductor project according to the Getting-Start shows on windows 7, it failed.
the 5 errors list as follows:
1.Unable to determine the host name on this Windows instance      ---the first error
......
2.Publication nebula not found in project :.                                       ---the second error
[buildinfo] Not using buildInfo properties file for this build.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.
......                                                                                                    ---the second error
3.826  [main] DEBUG org.elasticsearch.script  - [Hazmat] failed to load mustache
java.lang.ClassNotFoundException: com.github.mustachejava.Mustache
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)         
......                                                                                                     ---the third error
4.2497 [main] WARN  org.elasticsearch.bootstrap  - JNA not found. native methods will be dis                      abled.
java.lang.ClassNotFoundException: com.sun.jna.Native
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
......                                                                                                     ---the fourth error
5.12677 [main] INFO  org.elasticsearch.node  - [Hazmat] started
12677 [main] INFO  com.netflix.conductor.demo.EmbeddedElasticSearch  - ElasticSearch clust                      er elasticsearch_test started in local mode on port 9200
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2                      : /E:/conduct_v1/conductor/test-harness/build/resources/test/es_template.json
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.netflix.conductor.demo.EmbeddedElasticSearch.start(EmbeddedElasticSearch.ja                      va:62)
        at com.netflix.conductor.demo.EmbeddedElasticSearch.start(EmbeddedElasticSearch.ja                      va:37)
        at com.netflix.conductor.demo.Main.main(Main.java:42)
12682 [Thread-1] INFO  org.elasticsearch.node  - [Hazmat] stopping ...
12772 [elasticsearch[Hazmat][clusterService#updateTask][T#1]] INFO  org.elasticsearch.gate                      way  - [Hazmat] recovered [0] indices into cluster_state
12772 [elasticsearch[Hazmat][clusterService#updateTask][T#1]] DEBUG org.elasticsearch.clus                      ter.service  - [Hazmat] processing [local-gateway-elected-state]: took 137ms done applying                       updated cluster_state (version: 2, uuid: OXyaVx67TcqYAZMatWP_Lg)
12787 [Thread-1] INFO  org.elasticsearch.node  - [Hazmat] stopped
12788 [Thread-1] INFO  org.elasticsearch.node  - [Hazmat] closing ...
12793 [Thread-1] INFO  org.elasticsearch.node  - [Hazmat] closed
:conductor-test-harness:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-test-harness:server'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with non-ze                      ro exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to                       get more log output.

BUILD FAILED                                                                                 ---the fatal error which made it quit
----------------------------------------------------------------------------------
As the error shows,My other questions are:
1.Can "conductor" run on window 7?  
2.If i use as the "Getting Started guide" shows, Can I install conductor without Dynomite installed and without Tomcat running but only use its in-memory db when i test the simple kitchen sink workflow?

Thank you very much for answering! i am really confused about these but i am really interested in "conductor".

**Comment by v1r3n** [comment]
*  We have tested builds on Linux and MacOS.  Not tested on Windows 7, looking at the errors, it seems it is related to the path issue for windows (/E:/conduct_v1/conductor/test-harness/build/resources/test/es_template.json).  
*  test-harness builds runs conductor without Dynomite and in-memory db.  You can look at the dependencies for test-harness and [Main.java](https://github.com/Netflix/conductor/blob/dev/test-harness/src/test/java/com/netflix/conductor/demo/Main.java) for starting up.
