### ISSUE TITLE
Dynomite Connection Pool Configuration

### ISSUE THREAD

**Issue by guru1306** [Netflix/conductor#2124]
Hi All

We are getting a connection pool exhaustion issue. I see we can increase the maximum number of connections per host from the below code. How do I override other settings like retry and maxTimeoutWhenExhausted?

[Code](https://github.com/Netflix/conductor/blob/a88e27400aa7666bfb462548a279db378abfff8d/redis-persistence/src/main/java/com/netflix/conductor/jedis/DynomiteJedisProvider.java#L43)

Errors in logs:

com.netflix.dyno.connectionpool.exception.PoolTimeoutException: PoolTimeoutException: [host=Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null], latency=855369(0), attempts=0]Fast fail waiting for connection from pool
	at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl$ConnectionPoolActive.borrowConnection(HostConnectionPoolImpl.java:413)
	at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl.borrowConnection(HostConnectionPoolImpl.java:96)
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnection(HostSelectionWithFallback.java:141)
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnectionUsingRetryPolicy(HostSelectionWithFallback.java:120)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:305)
	at com.netflix.dyno.jedis.DynoJedisClient.d_hget(DynoJedisClient.java:670)
	at com.netflix.dyno.jedis.DynoJedisClient.hget(DynoJedisClient.java:665)
	at com.netflix.conductor.dyno.DynoProxy.hget(DynoProxy.java:147)
	at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getTaskDefFromDB(RedisMetadataDAO.java:109)
	at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.lambda$getTaskDef$1(RedisMetadataDAO.java:102)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getTaskDef(RedisMetadataDAO.java:102)
	at com.netflix.conductor.core.metadata.MetadataMapperService.populateWorkflowTaskWithDefinition(MetadataMapperService.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.netflix.conductor.core.metadata.MetadataMapperService.populateTaskDefinitions(MetadataMapperService.java:107)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:366)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:332)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:157)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:134)
	at com.netflix.conductor.service.WorkflowServiceImpl.startWorkflow(WorkflowServiceImpl.java:180)
	at com.netflix.conductor.interceptors.ServiceInterceptor.invoke(ServiceInterceptor.java:52)
	at com.netflix.conductor.server.resources.WorkflowResource.startWorkflow(WorkflowResource.java:82)
	at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:82)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:562)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)

Thanks
Guru

**Comment by aravindanr** [comment]
Those properties are part of Dyno Queues which is currently deprecated. 

dyno.conductor.connection.connectTimeout -> Connection Timeout in milliseconds
dyno.conductor.connection.maxConnsPerHost
dyno.conductor.retryPolicy=RetryNTimes:2:true

**Comment by guru1306** [comment]
@kishorebanala @aravindanr    Are you suggesting there is another way other than using these properties as you have pointed out dynoQueue is deprecated? I understand that the properties cannot be directly used.

**Comment by apanicker-nflx** [comment]
These properties can be set directly on the server since they are applied to the dyno client. 

DynoQueues being deprecated means that there is limited support for this project and eventually, we will look into removing support for this queuing layer from Conductor.
