### ISSUE TITLE
org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration 1

### ISSUE THREAD

**Issue by liangguohun** [Netflix/conductor#2197]
when i start my server got bug
```
org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration 1
-> Applied to database : 1012454114
-> Resolved locally    : -1880661771
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1008)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.flywayMigrate(MySQLDataSourceProvider.java:80)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.get(MySQLDataSourceProvider.java:30)
	at com.netflix.conductor.mysql.MySQLDataSourceProvider.get(MySQLDataSourceProvider.java:15)
```
or 
```
org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration 1
-> Applied to database : -1880661771
-> Resolved locally    : 1012454114
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1008)
```
but i don't change any，mysql version 5.6.39

**Comment by apanicker-nflx** [comment]
What persistence layer are you using? Also what version of Conductor are you running into this error with?

**Comment by mashurex** [comment]
@liangguohun What version of conductor did you upgrade from? Quite a while ago the Version 1 migration was modified and republished, which is why Flyway is throwing a validation error.

If you do not worry about the data in the database you can drop the schema and re-create it and all will work fine going forward.

If you do care about the database content you can attempt a manual migration which would mean:

1. Stop the service
2. Manually alter every table in the schema to match the DDL in the V1 migration file
3. Manually update the conductor_schema_history  table like so: `UPDATE conductor_schema_history SET checksum='1012454114' WHERE version = '1'`
4. Start the service and Flyway will be able to continue migrations
