### ISSUE TITLE
when access swagger i can't got any

### ISSUE THREAD

**Issue by liangguohun** [Netflix/conductor#2201]
**when i access address**
http://localhost:8080/index.html

can someone tell me what is the flow path, thanks.

![image](https://user-images.githubusercontent.com/10294447/115688760-03d66d80-a38e-11eb-9073-f745e34c6db5.png)

```
2021-04-22 17:09:30.296 ERROR 151312 --- [ qtp12127116-69] c.n.c.s.r.GenericExceptionMapper         : Error NoSuchMethodError url: 'swagger.json'

java.lang.NoSuchMethodError: io.swagger.models.properties.AbstractNumericProperty.setMinimum(Ljava/lang/Double;)V
	at io.swagger.jackson.ModelResolver.applyBeanValidatorAnnotations(ModelResolver.java:564) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:384) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:87) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58) ~[swagger-core-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:784) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.Reader.read(Reader.java:293) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.Reader.read(Reader.java:145) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.listing.BaseApiListingResource.scan(BaseApiListingResource.java:56) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.listing.BaseApiListingResource.process(BaseApiListingResource.java:101) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.listing.BaseApiListingResource.getListingJsonResponse(BaseApiListingResource.java:147) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:32) ~[swagger-jaxrs-1.5.9.jar:1.5.9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_261]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-bundle-1.19.1.jar:1.19.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.31.jar:9.0.31]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
	at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:82) [classes/:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) [jetty-servlet-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545) [jetty-servlet-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) [jetty-servlet-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.Server.handle(Server.java:500) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:562) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378) [jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) ~[jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) ~[jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]

2021-04-22 17:10:22.515  WARN 151312 --- [ool-16-thread-2] c.n.c.core.execution.DeciderService      : Task: 7aff1b75-9434-43de-b56b-f5aa9e1d1792 of type: task_10001 in workflow: 6df7414a-5217-458d-9a87-3c0aa60691cf/ephemeralKitchenSinkEphemeralTasks is in pending state for longer than 3600000 ms
2021-04-22 17:10:22.556  WARN 151312 --- [ool-16-thread-4] c.n.c.core.execution.DeciderService      : Task: 1dff14e5-a539-4e7c-8468-030d1dc2c7b0 of type: task_1 in workflow: 7a056461-be48-4b43-bbe7-ceff70f072d5/kitchensink is in pending state for longer than 3600000 ms
2021-04-22 17:10:22.558  WARN 151312 --- [ool-16-thread-5] c.n.c.core.execution.DeciderService      : Task: 9d7da503-fe9e-41bb-8985-23edd7bafec7 of type: task_1 in workflow: 43591630-8e96-47c0-89b0-3596710f137a/ephemeralKitchenSinkStoredTasks is in pending state for longer than 3600000 ms

```

**Comment by liangguohun** [comment]
![image](https://user-images.githubusercontent.com/10294447/115692985-105cc500-a392-11eb-8696-9ecfe0a1187e.png)
because i change the framwork myself , the version's problem
