### ISSUE TITLE
how to use grpc client view!!

### ISSUE THREAD

**Issue by liangguohun** [Netflix/conductor#2208]
as i know grpc is more effect, so i use grpc replace jersey but got such problem as follow
 
```
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.netflix.conductor.grpc.WorkflowServiceGrpc$WorkflowServiceBlockingStub.returnWorkflowResultDirect(WorkflowServiceGrpc.java:1133)
	at com.netflix.conductor.client.grpc.WorkflowClient.returnWorkflowResultDirect(WorkflowClient.java:63)
	at com.netflix.conductor.server.resources.WorkflowResource.returnWorkflowResultDirect(WorkflowResource.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
my change as bellow
```
    public Workflow returnWorkflowResultDirect(@PathParam("name") String name,
                                @QueryParam("version") Integer version,
                                @QueryParam("correlationId") String correlationId,
                                @QueryParam("priority") @DefaultValue("0") Integer priority,
                                @QueryParam("includeTasks") @DefaultValue("false") boolean includeTasks,
                                Map<String, Object> input) {
        StartWorkflowRequest startWorkflowRequest = new StartWorkflowRequest();
        startWorkflowRequest.setName(name);
        startWorkflowRequest.setVersion(version);
        startWorkflowRequest.setCorrelationId(correlationId);
        startWorkflowRequest.setPriority(priority);
        startWorkflowRequest.setIncludeTasks(includeTasks);
        startWorkflowRequest.setInput(input);
        WorkflowClient wc = new WorkflowClient("127.0.0.1", 8090);
        return wc.returnWorkflowResultDirect(startWorkflowRequest);
    }
```

**Comment by liangguohun** [comment]
it works when i update grpc versiont to 1.37.0
