### ISSUE TITLE
[BUG]: if the output has nested structure the AbstractProtoMapper can't use toProto convert

### ISSUE THREAD

**Issue by liangguohun** [Netflix/conductor#2211]
**Describe the bug**

**To Reproduce**
1、if data structure like follow it work.
```
            Workflow workflow = new Workflow();
            Map<String, Object> output = new HashMap<>();
            output.put("code", "444");
            output.put("msg", "666！");
            output.put("success", false);
            workflow.setOutput(output);
            PROTO_MAPPER.toProto(workflow)
```

2、like follow it donot work.

```
            Workflow workflow = new Workflow();
            Map<String, Object> output = new HashMap<>();
            output.put("code", "444");
            output.put("msg", "666！");
            // map or an abstact object
            Map<String, Object> data = new HashMap<>();
           output.put("data", data  );
            output.put("success", false);
            workflow.setOutput(output);
            PROTO_MAPPER.toProto(workflow)
```
3、 got errors like follow
```
msg
code
Exception in thread "pool-24-thread-1" java.lang.ClassCastException: cannot map to Value type: 0
	at com.netflix.conductor.grpc.ProtoMapper.toProto(ProtoMapper.java:70)
	at com.netflix.conductor.grpc.AbstractProtoMapper.toProto(AbstractProtoMapper.java:952)
	at com.netflix.conductor.grpc.server.utils.WaitCompleteWorkflowUtils$2.onSuccess(WaitCompleteWorkflowUtils.java:54)
	at com.netflix.conductor.grpc.server.utils.WaitCompleteWorkflowUtils$2.onSuccess(WaitCompleteWorkflowUtils.java:48)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
hope can convert nested structure like
 ```
{
 "msg": "ok",
 "code": 200,
 "data":{
    "test": "ok" 
 }
"success":true
}
```

**Screenshots**

**Additional context**

**Comment by komatiraju032** [comment]
@liangguohun expected output you provided is not matching with your code. In your code ket "data" is empty map but in your output it has values.
