### ISSUE TITLE
[BUG]: Subworkflows are assumed to be started by the subworkflow task

### ISSUE THREAD

**Issue by Jiehong** [Netflix/conductor#2248]
When a workflow is decided, it might have a parent, in which case the parent needs to be updated.

Up until 2.30.3, the parent task was correctly retrieved and updated when the sub workflow was finished.

However, updating to 2.31.3, it seems that now it fails, because conductor tries to specifically update the task that started that subworkflow as SUB_WORKFLOW.

However, we have defined multiple custom tasks that do start subworflows, but that are not named SUB_WORKFLOW, and thus this leads to a NPE, because this task with that name is not found.

Code that is failing in 2.31.3: https://github.com/Netflix/conductor/blob/2.31/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L1771

(`subWorkflowSystemTask` is retrieved as null).

This is a regression then.

Extract of the stack trace we got:

```
Unable to update task [363a094f-7e04-4ae7-9cdb-1da617fcabeb]
, java.lang.NullPointerException
	at com.netflix.conductor.core.execution.WorkflowExecutor.executeSubworkflowTaskAndSyncData(WorkflowExecutor.java:1772)
	at com.netflix.conductor.core.execution.WorkflowExecutor.updateParentWorkflowTask(WorkflowExecutor.java:1766)
	at com.netflix.conductor.core.execution.WorkflowExecutor.terminateWorkflow(WorkflowExecutor.java:798)
	at com.netflix.conductor.core.execution.WorkflowExecutor.terminate(WorkflowExecutor.java:1569)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1085)
	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:986)
	at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:227)
(...)
```

**Comment by aravindanr** [comment]
@Jiehong https://github.com/Netflix/conductor/blob/2.31/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L1771, this line will return null only if the `SubWorkflow` task is not registered. The task is registered by default. Can you share the details of how you are running Conductor and whether you have made any changes to the code?

**Comment by Jiehong** [comment]
@aravindanr we run a Spring application, using condutor as the base.

We do provide WorkflowExecutor via Spring injection in which we ensure the mapping is still correct.

It contains something like that:

```java
    final Map<String, TaskMapper> taskMappers = new HashMap<>();
    taskMappers.put("DECISION", new DecisionTaskMapper());
    taskMappers.put("DYNAMIC", new DynamicTaskMapper(taskParametersUtils, metadataDAO));
    taskMappers.put("FORK_JOIN", new ForkJoinTaskMapper());
    taskMappers.put("JOIN", new JoinTaskMapper());
    taskMappers.put("FORK_JOIN_DYNAMIC", new ForkJoinDynamicTaskMapper(taskParametersUtils, objectMapper, metadataDAO));
    taskMappers.put("USER_DEFINED", new UserDefinedTaskMapper(taskParametersUtils, metadataDAO));
    taskMappers.put("SIMPLE", new SimpleTaskMapper(taskParametersUtils));
    taskMappers.put("SUB_WORKFLOW", new SubWorkflowTaskMapper(taskParametersUtils, metadataDAO));
    taskMappers.put("EVENT", new EventTaskMapper(taskParametersUtils));
    taskMappers.put("WAIT", new WaitTaskMapper(taskParametersUtils));
    taskMappers.put("TERMINATE", new TerminateTaskMapper(taskParametersUtils));
    taskMappers.put("DO_WHILE", new DoWhileTaskMapper(metadataDAO));

    final ExternalPayloadStorageUtils externalPayloadStorageUtils =
        new ExternalPayloadStorageUtils(payloadExtStorage, configuration, objectMapper);
    final DeciderService deciderService = new DeciderService(taskParametersUtils, metadataDAO,
                                                             externalPayloadStorageUtils,
                                                             taskMappers,
                                                             configuration);
(...)
```

This hasn't changed in a long time, and works just fine with conductor 2.30.3, but updating to conductor 2.31.3 leads to that issue.

As anything changed by any chance? I'm wondering if WorkflowExecutor might have changed in a way that an assumption changed?

**Comment by Jiehong** [comment]
I just noticed that we also override startWorkflow from WorkflowExecutor due to our DAO being a bit different, but this is done for about at least 1 year now:

```java

public class OurWorkflowExecutor extends WorkflowExecutor {
  @Override
  public String startWorkflow(
      WorkflowDef workflowDefinition,
      Map<String, Object> workflowInput,
      String externalInputPayloadStoragePath,
      String correlationId,
      Integer priority,
      String parentWorkflowId,
      String parentWorkflowTaskId,
      String event,
      Map<String, String> taskToDomain
  ) {

    workflowDefinition = metadataMapperService.populateTaskDefinitions(workflowDefinition);

    // perform validations, only throws if invalid, no changes done to the parameters
    validateWorkflow(workflowDefinition, workflowInput, externalInputPayloadStoragePath);

    //A random UUID is assigned to the work flow instance
    final String workflowId = IDGenerator.generate();

    final ZonedDateTime nowTime = ZonedDateTime.now();
    // Persist the Workflow
    workflowExecution.setWorkflowId(workflowId);
    workflowExecution.setWorkflowDefinition(workflowDefinition);
    workflowExecution.setWorkflowDefinitionName(workflowDefinition.getName());
    workflowExecution.setWorkflowDefinitionVersion(workflowDefinition.getVersion());
    workflowExecution.setWorkflowType(workflowDefinition.getName());
    workflowExecution.setStatus(Workflow.WorkflowStatus.RUNNING);
    workflowExecution.setOwnerApp(WorkflowContext.get().getClientApp());
    workflowExecution.setCreateTime(nowTime.toEpochSecond());
    workflowExecution.setCreationDateTime(nowTime);
    workflowExecution.setUpdateTime(null);

    try {
      executionDAOFacade.createWorkflow(workflowExecution);
      LOGGER
          .debug("A new instance of workflow: {} created with id: {}", workflowExecution.getWorkflowName(), workflowId);
      //then decide to see if anything needs to be done as part of the workflow
      this.decide(workflowId); // from conductor
      return workflowId;
    } catch (final Exception e) {
      executionDAOFacade.removeWorkflow(workflowId, false);
      Monitors.recordWorkflowStartError(workflowDefinition.getName(), WorkflowContext.get().getClientApp());
      LOGGER.error("Unable to start workflow: {}", workflowDefinition.getName(), e);
      throw e;
    }
  }
}
```

**Comment by Jiehong** [comment]
Any change in that direction?

**Comment by aravindanr** [comment]
@Jiehong Sorry about the delay. In your spring application, either create a Bean of type `Subworkflow` or create an instance of `SubWorkflow` during startup.

In the latest version of `2.31`, the code in WorkflowExecutor is changed to load SubWorkflow from the ["system task registry"](https://github.com/Netflix/conductor/blob/2.31/core/src/main/java/com/netflix/conductor/core/execution/tasks/WorkflowSystemTask.java#L42) and it is populated when an instance of `SubWorkflow` is created.

**Comment by Jiehong** [comment]
@aravindanr  thanks! It seems to have fixed the problem, so I'll close this issue.

Thanks again for the support!
