### ISSUE TITLE
[QUESTION]: Why task is getting executed 2 times only in case of failure even though retryCount is 10

### ISSUE THREAD

**Issue by bhawani021** [Netflix/conductor#2282]
**Conductor version: 3**

_Need help in understanding why below task is getting executed only 2 times if task is failed.
 I have given retryCount = 10 that means it should be called 10 times in case response of get_workspace is FAILED_

```
{
  "ownerApp": "bhawani shanker",
  "createTime": 1621771809352,
  "updateTime": 1622616499751,
  "createdBy": "",
  "updatedBy": "",
  "name": "get_workspace",
  "description": "get workspace",
  "retryCount": 10,
  "timeoutSeconds": 200,
  "retryDelaySeconds": 2,
  "responseTimeoutSeconds": 20,
  "inputKeys": [
    "workspaceName"
  ],
  "outputKeys": [
    
  ],
  "timeoutPolicy": "TIME_OUT_WF",
  "retryLogic": "FIXED",

  "inputTemplate": {
    
  },
  "rateLimitPerFrequency": 0,
  "rateLimitFrequencyInSeconds": 1,
  "ownerEmail": "bhawani021@gmail.com"
}
```

**Comment by bhawani021** [comment]
during debugging I see this error in my logs. Is it reason? 
```
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:1024) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:216) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.TaskServiceImpl.updateTask(TaskServiceImpl.java:125) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.TaskServiceImpl$$FastClassBySpringCGLIB$$d78c3007.invoke(<generated>) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at com.netflix.conductor.service.TaskServiceImpl$$EnhancerBySpringCGLIB$$94fd3b44.updateTask(<generated>) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.rest.controllers.TaskResource.updateTask(TaskResource.java:78) ~[conductor-rest-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 43 more
```

**Comment by bhawani021** [comment]
After fixing above error, it's looking good.
