### ISSUE TITLE
[BUG]: Event handler fails to process event due to duplicated meter names

### ISSUE THREAD

**Issue by heinrichcohn** [Netflix/conductor#2375]
**Describe the bug**
When starting a workflow using an event-handler action the following exception is thrown:
**java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'dao_requests_total' containing tag keys [action, class, dao, taskType, workflowType]**

This issue occurs due to duplicated meter names in both recordDaoRequests and recordDaoEventRequests methods and having **conductor.metrics-prometheus.enabled=true**

    public static void recordDaoRequests(String dao, String action, String taskType, String workflowType) {
        counter(classQualifier, **"dao_requests",** "dao", dao, "action", action, "taskType", taskType, "workflowType",
            workflowType);
    }

    public static void recordDaoEventRequests(String dao, String action, String event) {
        counter(classQualifier, **"dao_requests"**, "dao", dao, "action", action, "event", event);
    }

**Details**
Conductor version: 3.X
Event handler definition:
{"name":"handle_test_wait","event":"amqp_queue:conductor_myevents_start_wf","actions":[{"action":"start_workflow","start_workflow":{"name":"my_dummy_workflow","version":1,"correlationId":"111111","input":{"param1":"someinput"}},"expandInlineJSON":false}],"active":true}

Event sent to queue:
{ "field1":"some_value"}

**To Reproduce**
1. Configure conductor with the following properties and then start it:
   conductor.metrics-prometheus.enabled=true
   management.endpoints.web.exposure.include=prometheus
   conductor.event-queues.amqp.enabled=true ( + configure ampq specific properties)
2. Create a dummy workflow called "my_dummy_workflow"
3. Create an event handler (see above) and start it
4. Send message to queue "conductor_myevents_start_wf", payload:    { "field1":"some_value"}
5. Check logs and look for an IllegalArgumentException.

**Expected behavior**
No exception is thrown and a new workflow instance should be started.

**Screenshots**
Stacktrace:

2021-07-27T11:23:36,178  INFO [pool-37-thread-5] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue$1) - receiveMessagesFromQueue- End method [7419b298-0747-495b-b0d2-4e88475e3787]
2021-07-27T11:23:36,193  INFO [RxComputationScheduler-4] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - Batch from conductor_myevents_start to conductor is 7419b298-0747-495b-b0d2-4e88475e3787={
   "f":"empty"
}
2021-07-27T11:23:36,200 ERROR [RxComputationScheduler-4] (com.netflix.conductor.core.events.DefaultEventProcessor) - Error handling message: 7419b298-0747-495b-b0d2-4e88475e3787 on queue:conductor_myevents_start
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'dao_requests_total' containing tag keys [action, class, dao, taskType, workflowType]. The meter you are attempting to register has keys [action, class, dao, event].
                at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:422) ~[micrometer-registry-prometheus-1.5.14.jar!/:1.5.14]
                at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932) ~[?:?]
                at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:406) ~[micrometer-registry-prometheus-1.5.14.jar!/:1.5.14]
                at io.micrometer.prometheus.PrometheusMeterRegistry.newCounter(PrometheusMeterRegistry.java:107) ~[micrometer-registry-prometheus-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:559) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:612) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:566) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:559) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:282) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:128) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:389) ~[micrometer-core-1.5.14.jar!/:1.5.14]
                at com.netflix.spectator.micrometer.MicrometerRegistry.counter(MicrometerRegistry.java:111) ~[spectator-reg-micrometer-0.122.0.jar!/:0.122.0]
                at com.netflix.spectator.api.CompositeRegistry.lambda$newCounter$0(CompositeRegistry.java:140) ~[spectator-api-0.122.0.jar!/:0.122.0]
                at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
                at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
                at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
                at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
                at com.netflix.spectator.api.CompositeRegistry.newCounter(CompositeRegistry.java:141) ~[spectator-api-0.122.0.jar!/:0.122.0]
                at com.netflix.spectator.api.CompositeRegistry.counter(CompositeRegistry.java:152) ~[spectator-api-0.122.0.jar!/:0.122.0]
                at com.netflix.conductor.metrics.Monitors.lambda$getCounter$3(Monitors.java:115) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737) ~[?:?]
                at com.netflix.conductor.metrics.Monitors.getCounter(Monitors.java:113) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.metrics.Monitors.counter(Monitors.java:73) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.metrics.Monitors.recordDaoEventRequests(Monitors.java:298) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.redis.dao.BaseDynoDAO.recordRedisDaoEventRequests(BaseDynoDAO.java:91) ~[conductor-redis-persistence-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.redis.dao.RedisEventHandlerDAO.getEventHandlersForEvent(RedisEventHandlerDAO.java:116) ~[conductor-redis-persistence-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.service.MetadataServiceImpl.getEventHandlersForEvent(MetadataServiceImpl.java:203) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.service.MetadataServiceImpl$$FastClassBySpringCGLIB$$726d989d.invoke(<generated>) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
                at com.netflix.conductor.service.MetadataServiceImpl$$EnhancerBySpringCGLIB$$324c3cfb.getEventHandlersForEvent(<generated>) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.core.events.DefaultEventProcessor.executeEvent(DefaultEventProcessor.java:124) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.core.events.DefaultEventProcessor.handle(DefaultEventProcessor.java:97) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at com.netflix.conductor.core.events.DefaultEventQueueManager.lambda$listen$8(DefaultEventQueueManager.java:145) ~[conductor-core-3.2.0-SNAPSHOT.jar!/:3.2.0-SNAPSHOT]
                at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.3.8.jar!/:1.3.8]
                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.Subscriber.setProducer(Subscriber.java:211) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.Observable.unsafeSubscribe(Observable.java:10327) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.schedulers.SchedulePeriodicHelper$1.call(SchedulePeriodicHelper.java:72) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189) [rxjava-1.3.8.jar!/:1.3.8]
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) [rxjava-1.3.8.jar!/:1.3.8]
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
                at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:834) [?:?]
2021-07-27T11:23:38,555  INFO [metrics-logger-reporter-1-thread-1] (com.codahale.metrics.Slf4jReporter$InfoLoggerProxy) - type=GAUGE, name=_deciderQueue.class-WorkflowMonitor, value=0.0
2021-07-27T11:23:38,555  INFO [metrics-logger-reporter-1-thread-1] (com.codahale.metrics.Slf4jReporter$InfoLoggerProxy) - type=GAUGE, name=dao_payload_size.action-getAllWorkflowDefs.

**Comment by heinrichcohn** [comment]
I created the following PR that fixes the issue
Pull Request: https://github.com/Netflix/conductor/pull/2376

@aravindanr

**Comment by apanicker-nflx** [comment]
Thanks for reporting the issue and the PR with the fix. 💯
