### ISSUE TITLE
[BUG]: AMQP Unknown Tags -  Messages can't be acked because channel is recreated each time there is a network failure

### ISSUE THREAD

**Issue by heinrichcohn** [Netflix/conductor#2382]
**Describe the bug**
I'm using Rabbitmq to send/receive messages from or to workflows. I found out that in case of a network failure, messages that were taken from a queue but not yet acked, conductor won't be able to ack them at all until the server is restarted. 

This happens because in case of a network error the channel is __recreated each time!__ . From the moment the channel is recreated  all delivery tags from previous messages can't be use for acknowledgement  and  "**Unknown Tag**" errors are thrown each time an ack attempt is made. In addition, trying to acknowledge a message with delivery tag created in a different channel  will cause the channel to __close!__.

**Details**
Conductor version: 3.X
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**
1. Enable amqp in conductor config and start
2. Created event-handler that listens to an amqp queue
3. Start sending messages to the queue
4. Simulate a network error between the queue and conductor
5. Connection errors will appear in conductor logs
6. Restore connection between  the queue and conductor
7. Acknowledgement of messages taken before the failure will get  unknow_tag errors in the logs from this moment (these message will appear as unacked in Rabbit)
8. Restarting conductor solves the problem

**Expected behavior**
After a connection between a queue and conductor is restored, messages taken before the failure will be acknowledged successfully by conductor. Aqmp client will be responsible of restoring the amqp channel and handle delivery tags that were created before the failure so they can be acknowledged in the new restored channel.

**Logs**
2020-11-15 09:56:18,622  INFO [RxComputationScheduler-1] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - Batch from conductor.order.cancelled to conductor is a0de6fe3-fe2e-4579-a657-874c6d29306b={"OrderId":"14043973","CancellationReason":"Automation","workflow_meta":{"sourceQueue":"Comp.OrderOrchestrator.Order.Cancelled","workflowId":"85654cc7-db84-4a6b-8a66-d9501d918f27"}}
2020-11-15 09:56:18,708  INFO [pool-13-thread-1] (com.netflix.conductor.dao.dynomite.RedisExecutionDAO) - updating event execution conductor.qa.EVENT_EXECUTION.PMT_order_cancelled.amqp_queue:conductor.order.cancelled.a0de6fe3-fe2e-4579-a657-874c6d29306b
2020-11-15 09:56:18,709  INFO [RxComputationScheduler-1] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - ACK message with delivery tag 8
2020-11-15 09:56:18,711 ERROR [AMQP Connection 10.30.220.205:5672] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - Channel has been shutdown: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 8, class-id=60, method-id=80)
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 8, class-id=60, method-id=80)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:522)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:719)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:646)
	at java.lang.Thread.run(Thread.java:748)
	
	
	
	
2020-11-15 09:44:38,322  INFO [RxComputationScheduler-1] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - Batch from conductor.order.cancelled to conductor is c9605d98-2702-4578-83e0-eefc34aa2296={"OrderId":"14043963","CancellationReason":"Automation","workflow_meta":{"sourceQueue":"Comp.OrderOrchestrator.Order.Cancelled","workflowId":"48442337-8e5f-4e93-a74e-7f5ecb1a048f"}}
2020-11-15 09:44:38,452  INFO [pool-13-thread-2] (com.netflix.conductor.dao.dynomite.RedisExecutionDAO) - updating event execution conductor.qa.EVENT_EXECUTION.PMT_order_cancelled.amqp_queue:conductor.order.cancelled.c9605d98-2702-4578-83e0-eefc34aa2296
2020-11-15 09:44:38,454  INFO [RxComputationScheduler-1] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - ACK message with delivery tag 7
2020-11-15 09:44:38,456 ERROR [AMQP Connection 10.30.220.205:5672] (com.netflix.conductor.contribs.queue.amqp.AMQPObservableQueue) - Channel has been shutdown: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 7, class-id=60, method-id=80)
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 7, class-id=60, method-id=80)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:522)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:719)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:646)
	at java.lang.Thread.run(Thread.java:748)

**Link from rabbit documentation**
https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking
https://www.rabbitmq.com/api-guide.html#recovery

**Comment by heinrichcohn** [comment]
@aravindanr 

Pull Request created: 
https://github.com/Netflix/conductor/pull/2383

**Comment by aravindanr** [comment]
@ritu-p , can you look into this?
