### ISSUE TITLE
Netflix Conductor build fails

### ISSUE THREAD

**Issue by lbarker800** [Netflix/conductor#2394]
### Discussed in https://github.com/Netflix/conductor/discussions/2391

<div type='discussions-op-text'>

<sup>Originally posted by **lbarker800** August  9, 2021</sup>
I am trying to build  Netflix Conductor to perform an evaluation. I am targetting the docker build solution.  Executing gradlew build from the project root, it gets about 70% of the way through...  Then there are 3 errors:   

> Task :conductor-client:pmdTest
Error during type resolution of field 'new' in class com.netflix.conductor.common.metadata.tasks.TaskResult due to: java.lang.NoClassDefFoundError: Lcom/google/protobuf/Any;
Error during type resolution of field 'new' in class com.netflix.conductor.common.metadata.tasks.TaskResult due to: java.lang.NoClassDefFoundError: Lcom/google/protobuf/Any;
Error during type resolution of field 'new' in class com.netflix.conductor.common.metadata.tasks.TaskResult due to: java.lang.NoClassDefFoundError: Lcom/google/protobuf/Any;
  Then it goes a bit rather, and fails on  Task :conductor-es6-persistence:test:

        Caused by:
        NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{E4APunBITXWQ6fQR7bs7-Q}{localhost}{127.0.0.1:32814}]]
            at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
            at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
            at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
            at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:388)
            at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
            at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:391)
            at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1262)
            at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
            at com.netflix.conductor.es6.dao.index.ElasticSearchDAOV6.createIndex(ElasticSearchDAOV6.java:289)
            at com.netflix.conductor.es6.dao.index.ElasticSearchDAOV6.createWorkflowIndex(ElasticSearchDAOV6.java:278)
            at com.netflix.conductor.es6.dao.index.ElasticSearchDAOV6.setup(ElasticSearchDAOV6.java:216)
            at com.netflix.conductor.es6.dao.index.ElasticSearchDaoBaseTest.setup(ElasticSearchDaoBaseTest.java:47)
            at com.netflix.conductor.es6.dao.index.TestElasticSearchDAOV6Batch.setup(TestElasticSearchDAOV6Batch.java:27)

Any thoughts?  </div>

**Comment by lbarker800** [comment]
Oh, and one more thing.   Thinking that it needs an elastic search instance, I create a separate docker compose file from the elastic search config in one of your docker files and spun it up...   When it gets to this test, that docker instance dies with exit code 137...

**Comment by lbarker800** [comment]
I resolved the problem.  Running on mac.  Default Docker memory limit is 2GB.  Increased to 4GB.  Success.
