### ISSUE TITLE
Problem at Conductor UI Server

### ISSUE THREAD

**Issue by eder-santos** [Netflix/conductor#258]
Hi, I get the following exception when I try visualize a workflow from the UI Server. i.e.
 `http://localhost:3000/#/workflow/id/1b40c1d3-71de-4de4-b8d8-2585381a4d75?_k=94ngu1`

```
2449655 [qtp1041451158-32] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - all shards failed
Failed to execute phase [query], all shards failed; shardFailures {[rUJuEcF3R-a1s2i-c3sWvg][task_log_20170702][0]: RemoteTransportException[[Scorpion][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"9dd7675e-830f-4200-a524-c0b6f9d81442\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[rUJuEcF3R-a1s2i-c3sWvg][task_log_20170702][1]: RemoteTransportException[[Scorpion][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"9dd7675e-830f-4200-a524-c0b6f9d81442\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[rUJuEcF3R-a1s2i-c3sWvg][task_log_20170702][2]: RemoteTransportException[[Scorpion][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"9dd7675e-830f-4200-a524-c0b6f9d81442\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[rUJuEcF3R-a1s2i-c3sWvg][task_log_20170702][3]: RemoteTransportException[[Scorpion][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"9dd7675e-830f-4200-a524-c0b6f9d81442\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[rUJuEcF3R-a1s2i-c3sWvg][task_log_20170702][4]: RemoteTransportException[[Scorpion][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"9dd7675e-830f-4200-a524-c0b6f9d81442\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: SearchParseException[No mapping found for [createdTime] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more
```

Elasticsearch version:

```
{
  "name" : "Mountjoy",
  "cluster_name" : "conductor",
  "cluster_uuid" : "7wsrk8JYQnGPWJV5yTTA9g",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```

Feel free to require me more information.

**Comment by milowe** [comment]
I am facing the same issue. Using es 2.4.0 & conductor 1.7.6 & conductor-ui from the docker build.

**Comment by v1r3n** [comment]
@milowe can you check how many mappings are created in the elasticsearch?  There should be a mapping for task.
