### ISSUE TITLE
conductor's workflows work slowly after inititating a workflow 

### ISSUE THREAD

**Issue by Kristin0** [Netflix/conductor#2786]
usually workflows take about minute to complete, but now it takes about an hour to complete, i checked the logs from conductor, seems elasticache has troubles to create an indexes . example is workflowid `b3c1aa93-05a9-42bf-b16b-b8872c434d5d`

```
619252009 [system-task-worker-48] ERROR com.netflix.conductor.common.utils.RetryUtil  - Operation 'indexWorkflow:Indexing workflow document: b3c1aa93-05a9-42bf-b16b-b8872c434d5d' failed after retrying 3 times, retry limit 3
java.lang.RuntimeException: java.io.IOException: listener timeout after waiting for [30000] ms
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWorkflow$2(ElasticSearchRestDAOV6.java:451)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:117)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexWorkflow(ElasticSearchRestDAOV6.java:447)
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateWorkflow(ExecutionDAOFacade.java:235)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1058)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1064)
	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:922)
	at com.netflix.conductor.core.execution.WorkflowExecutor.executeSystemTask(WorkflowExecutor.java:1307)
	at com.netflix.conductor.core.execution.tasks.SystemTaskExecutor.lambda$pollAndExecute$0(SystemTaskExecutor.java:114)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1593)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1546)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1512)
	at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:858)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWorkflow$2(ElasticSearchRestDAOV6.java:449)
	... 14 more
619252009 [system-task-worker-48] ERROR com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6  - Failed to index workflow: b3c1aa93-05a9-42bf-b16b-b8872c434d5d
java.lang.RuntimeException: Operation 'indexWorkflow:Indexing workflow document: b3c1aa93-05a9-42bf-b16b-b8872c434d5d' failed after retrying 3 times, retry limit 3
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:127)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexWorkflow(ElasticSearchRestDAOV6.java:447)
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateWorkflow(ExecutionDAOFacade.java:235)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1058)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1064)
	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:922)
	at com.netflix.conductor.core.execution.WorkflowExecutor.executeSystemTask(WorkflowExecutor.java:1307)
	at com.netflix.conductor.core.execution.tasks.SystemTaskExecutor.lambda$pollAndExecute$0(SystemTaskExecutor.java:114)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: listener timeout after waiting for [30000] ms
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWorkflow$2(ElasticSearchRestDAOV6.java:451)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:117)
	... 11 more
Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1593)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1546)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1512)
	at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:858)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWorkflow$2(ElasticSearchRestDAOV6.java:449)
	... 14 more
619348735 [system-task-worker-38] ERROR com.netflix.conductor.common.utils.RetryUtil  - Operation 'indexWithRetry:Bulk Indexing task' failed after retrying 3 times, retry limit 3
java.lang.RuntimeException: java.io.IOException: listener timeout after waiting for [30000] ms
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWithRetry$15(ElasticSearchRestDAOV6.java:962)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:117)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexWithRetry(ElasticSearchRestDAOV6.java:958)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexBulkRequest(ElasticSearchRestDAOV6.java:943)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexObject(ElasticSearchRestDAOV6.java:936)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexTask(ElasticSearchRestDAOV6.java:478)
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateTask(ExecutionDAOFacade.java:380)
	at com.netflix.conductor.core.execution.WorkflowExecutor.executeSystemTask(WorkflowExecutor.java:1280)
	at com.netflix.conductor.core.execution.tasks.SystemTaskExecutor.lambda$pollAndExecute$0(SystemTaskExecutor.java:114)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1593)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1546)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1512)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:427)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWithRetry$15(ElasticSearchRestDAOV6.java:960)
	... 14 more
619348736 [system-task-worker-38] ERROR com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6  - Failed to index org.elasticsearch.action.bulk.BulkRequest@2b7d5f64 for request type: task
java.lang.RuntimeException: Operation 'indexWithRetry:Bulk Indexing task' failed after retrying 3 times, retry limit 3
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:127)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexWithRetry(ElasticSearchRestDAOV6.java:958)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexBulkRequest(ElasticSearchRestDAOV6.java:943)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexObject(ElasticSearchRestDAOV6.java:936)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.indexTask(ElasticSearchRestDAOV6.java:478)
	at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.updateTask(ExecutionDAOFacade.java:380)
	at com.netflix.conductor.core.execution.WorkflowExecutor.executeSystemTask(WorkflowExecutor.java:1280)
	at com.netflix.conductor.core.execution.tasks.SystemTaskExecutor.lambda$pollAndExecute$0(SystemTaskExecutor.java:114)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: listener timeout after waiting for [30000] ms
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWithRetry$15(ElasticSearchRestDAOV6.java:962)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:117)
	... 11 more
Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1593)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1546)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1512)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:427)
	at com.netflix.conductor.dao.es6.index.ElasticSearchRestDAOV6.lambda$indexWithRetry$15(ElasticSearchRestDAOV6.java:960)
	... 14 more
619424370 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424370 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424370 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424370 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424370 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424371 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424371 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424371 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424371 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b8872c434d5d to the unack shard conductor_queues.test.UNACK._deciderQueue.c
619424371 [pool-15-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add b3c1aa93-05a9-42bf-b16b-b88

```

**Comment by Kristin0** [comment]
@v1r3n

**Comment by manan164** [comment]
Hi @Kristin0 , Can you please check your elastic search health. It may be yellow. If required please delete unused worklfows. This command will help you to delete all the indexes.  ```curl -X DELETE 'http://localhost:9200/_all'```
Be cautious, It will delete everything.

**Comment by Kristin0** [comment]
Hi @manan164 i configured conductor to use elasticsearch with yellow color and i configured elastic to delete indexes every 3 hour, i have thoughts about elasticache

**Comment by manan164** [comment]
Hi @Kristin0 , Looks like the connectivity issue between the conductor server and elasticsearch. Can you please let us know the infra used? Like where is ES hosted and conductor server hosting? Are they in the same shared VPC or different etc?

**Comment by Kristin0** [comment]
yeah, it was network issue, so we can close. thanks a lot !
