### ISSUE TITLE
Bug: Conductor is not working with ElasticSearch-5.3.1 

### ISSUE THREAD

**Issue by mwangtarget** [Netflix/conductor#283]
Can we upgrade Conductor to use 5+ elasticsearch library??

Error following with existing code base:
``
07:30:56.663 51770 INFO  org.elasticsearch.client.transport [elasticsearch[Miguel Espinosa][generic][T#2]] : [Miguel Espinosa] failed to get local cluster state for {#transport#-1}{localhost}{127.0.0.1:9200}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9200][cluster:monitor/state] request_id [4] timed out after [5003ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:698)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by v1r3n** [comment]
@mwangtarget to use the es5, you need t ouse the es5 persistence module as the 2.x client is not compatible with es5.

**Comment by grfeng** [comment]
Please reference https://github.com/Netflix/conductor/tree/master/es5-persistence
