### ISSUE TITLE
DynamicProperty class missing when creating bean with taskRunnerConfigurer

### ISSUE THREAD

**Issue by elvisols** [Netflix/conductor#2859]
**DynamicProperty class not found**
Having issues starting up my taskRunnerConfigurer as found in `spring-client`. 

**Error thrown**
`Error creating bean with name 'taskRunnerConfigurer' defined in class path resource [ng[/exelon/nibss/namenquiryinbound/config/ConductorClientConfig.class]()]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com[/netflix/config/DynamicProperty]()`
I really don't know why that class is used or a fix to this issue.

**Screenshots**
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/4430341/158800181-0b925b2b-88a3-478a-a29b-af8cbb04fe86.png">

Thanks

**Comment by elvisols** [comment]
I searched and added this dependency
`implementation 'com.netflix.archaius:archaius-core:0.7.7` but I am now getting the following exceptions:

```
2022-03-17 16:50:41.134 ERROR 75461 --- [pool-3-thread-2] c.n.c.client.automator.TaskPollExecutor  : Error when polling for tasks

com.netflix.conductor.client.exception.ConductorClientException: Unable to invoke Conductor API with uri: null, runtime exception occurred
	at com.netflix.conductor.client.http.ClientBase.handleRuntimeException(ClientBase.java:334) ~[conductor-client-3.5.3.jar:3.5.3]
ClientBase.java:334
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:255) ~[conductor-client-3.5.3.jar:3.5.3]
ClientBase.java:255
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:224) ~[conductor-client-3.5.3.jar:3.5.3]
ClientBase.java:224
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:130) ~[conductor-client-3.5.3.jar:3.5.3]
TaskClient.java:130
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$2(TaskPollExecutor.java:153) ~[conductor-client-3.5.3.jar:3.5.3]
TaskPollExecutor.java:153
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:43) ~[spectator-api-0.122.0.jar:0.122.0]
SwapTimer.java:43
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:151) ~[conductor-client-3.5.3.jar:3.5.3]
TaskPollExecutor.java:151
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$init$0(TaskRunnerConfigurer.java:255) ~[conductor-client-3.5.3.jar:3.5.3]
TaskRunnerConfigurer.java:255
	at java.base[/java.util.concurrent.Executors]()$RunnableAdapter.call(Executors.java:515) ~[na:na]
Executors.java:515
	at java.base[/java.util.concurrent.FutureTask.runAndReset]()(FutureTask.java:305) ~[na:na]
FutureTask.java:305
	at java.base[/java.util.concurrent.ScheduledThreadPoolExecutor]()$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
ScheduledThreadPoolExecutor.java:305
	at java.base[/java.util.concurrent.ThreadPoolExecutor.runWorker]()(ThreadPoolExecutor.java:1128) ~[na:na]
ThreadPoolExecutor.java:1128
	at java.base[/java.util.concurrent.ThreadPoolExecutor]()$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
ThreadPoolExecutor.java:628
	at java.base[/java.lang.Thread.run]()(Thread.java:829) ~[na:na]
Thread.java:829
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 37: [http://127.0.0.1:8080/api/tasks/poll/{taskType]()}
	at java.base[/java.net.URI.create]()(URI.java:883) ~[na:na]
URI.java:883
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doPath(UriBuilderImpl.java:507) ~[cxf-bundle-jaxrs-2.7.18.jar:2.7.18]
UriBuilderImpl.java:507
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.path(UriBuilderImpl.java:499) ~[cxf-bundle-jaxrs-2.7.18.jar:2.7.18]
UriBuilderImpl.java:499
	at javax.ws.rs.core.UriBuilder.fromPath(UriBuilder.java:148) ~[javax.ws.rs-api-2.0-m10.jar:2.1.6]
UriBuilder.java:148
	at com.netflix.conductor.client.http.ClientBase.getURIBuilder(ClientBase.java:412) ~[conductor-client-3.5.3.jar:3.5.3]
ClientBase.java:412
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:242) ~[conductor-client-3.5.3.jar:3.5.3]
ClientBase.java:242
	... 12 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in path at index 37: [http://127.0.0.1:8080/api/tasks/poll/{taskType]()}
	at java.base[/java.net.URI]()$Parser.fail(URI.java:2913) ~[na:na]
URI.java:2913
	at java.base[/java.net.URI]()$Parser.checkChars(URI.java:3084) ~[na:na]
URI.java:3084
	at java.base[/java.net.URI]()$Parser.parseHierarchical(URI.java:3166) ~[na:na]
URI.java:3166
	at java.base[/java.net.URI]()$Parser.parse(URI.java:3114) ~[na:na]
URI.java:3114
	at java.base[/java.net.URI.]()<init>(URI.java:600) ~[na:na]
URI.java:600
	at java.base[/java.net.URI.create]()(URI.java:881) ~[na:na]
URI.java:881
	... 17 common frames omitted
```
Any assistance will be highly appreciated.

**Comment by jxu-nflx** [comment]
@elvisols The `archaius-core` is a transitive dependency brought in by `eureka-client`, can you do an dependency insight to check all the depenencies?

For the other error, I saw this in your stack trace
```
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 37: [http://127.0.0.1:8080/api/tasks/poll/{taskType}
	at java.base[/java.net.URI.create]()(URI.java:883) ~[na:na]
URI.java:883
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doPath(UriBuilderImpl.java:507) ~[cxf-bundle-jaxrs-2.7.18.jar:2.7.18]
UriBuilderImpl.java:507
```
Can you check your config as well as your worker's task def to see whether anything wrong there?
