### ISSUE TITLE
Problem with conductor docker image using dynomite db

### ISSUE THREAD

**Issue by eder-santos** [Netflix/conductor#290]
Hi, I'm getting the following error with the conductor docker image. It appears to be a problem with the `DynoJedisClient`, this error only occurs using the default `config.properties` (dynomite db) but it will not appear if I swith to the  `config-local.properties` file. Should I report this bug on the [Netflix/dyno-queues](https://github.com/Netflix/dyno-queues) project?

Thank you.

```
46854 [qtp1747721875-46] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - java.lang.UnsupportedOperationException: not yet implemented
java.lang.RuntimeException: java.lang.UnsupportedOperationException: not yet implemented
        at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:224)
        at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:150)
        at com.netflix.conductor.service.ExecutionService.poll(ExecutionService.java:109)
        at com.netflix.conductor.server.resources.TaskResource.batchPoll(TaskResource.java:105)
        at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: not yet implemented
        at com.netflix.dyno.jedis.DynoJedisClient.zadd(DynoJedisClient.java:3639)
        at com.netflix.dyno.queues.redis.RedisDynoQueue._pop(RedisDynoQueue.java:270)
        at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:221)
        ... 50 more
```

**Comment by nbraquart** [comment]
Hello,

I faced the same problem. After investigation, it appears that by upgrading dyno-jedis from 1.0.6 to 1.0.7, dyno-queues-redis was downgraded from 1.5.6 to 1.4.7. In the process, we lost implementation for zadd in the DynoJedisClient.

As a consequence, Conductor releases based on dyno-jedis 1.0.7 are not usable with actual Jedis client (not in memory mock).

Nicolas

**Comment by v1r3n** [comment]
@nbraquart will take a look at it.  We need 1.5.6+ version of dyno-jedis.

**Comment by MythX** [comment]
Hello,

@nbraquart I think it's not a problem with dyno-queues-redis 1.0.7.
You can try with Conductor at the commit `398131c619b85b6ee4101a96dd6929d80de39d0f` and it's ok for me with Redis 4.0.1 and ES5. 

Antoine.

**Comment by picaron** [comment]
I'm having the same issue with the `1.8.0` release which is based on `dyno-queues-1.0.7`

**Comment by picaron** [comment]
@nbraquart @v1r3n 

Adding :

    	compile 'com.netflix.dyno:dyno-jedis:1.5.9' 

in `redis-persistence/build.gradle` sets the proper version for `dyno-jedis` and fixes the issue
