### ISSUE TITLE
`HttpTaskTest` still has `OutOfMemoryError`

### ISSUE THREAD

**Issue by bfrggit** [Netflix/conductor#2935]
**Describe the bug**
`com.netflix.conductor.contribs.tasks.http.HttpTaskTest` was empty and annotated with `@Ignore` in `v3.4.2`, but got re-enabled starting `v.3.5.0` until latest `v3.7.2`. However, this test still causes `OutOfMemoryError` when running `./gradlew clean build`.

Reference:
- v3.4.2: https://github.com/Netflix/conductor/blob/v3.4.2/contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java#L18
- v3.5.0: https://github.com/Netflix/conductor/blob/v3.5.0/contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java#L50
- v3.7.2: https://github.com/Netflix/conductor/blob/v3.7.2/contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java#L50

My local environment (Gradle version w.r.t. v3.5.0):
```
------------------------------------------------------------
Gradle 7.3.2
------------------------------------------------------------

Build time:   2021-12-15 11:22:31 UTC
Revision:     26c186eb63b2b02e68d83b0dbc6ec69ab118653a

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.14.1 (Ubuntu 11.0.14.1+1-Ubuntu-0ubuntu1.20.04)
OS:           Linux 5.4.0-107-generic amd64
```

**Details**
Conductor version: v3.5.0 ~ v3.7.2
Persistence implementation: Cassandra, Postgres, MySQL, Dynomite etc N/A
Queue implementation: Postgres, MySQL, Dynoqueues etc N/A
Lock: Redis or Zookeeper? N/A
Workflow definition: N/A
Task definition: `HttpTask`
Event handler definition: N/A

**To Reproduce**
1. Clone the repository.
2. `git checkout v3.5.0` or `git checkout v3.7.2`.
3. `./gradlew clean build --warning-mode=all --info`.
4. `OutOfMemoryError` in `HttpTastTest`.

**Expected behavior**
Build should be successful and all tests should pass.

**Screenshots**
N/A

**Additional context**
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RxComputationScheduler-3"

HttpTaskTest STANDARD_OUT
    00:21:41.613 [metrics-logger-reporter-2-thread-1] ERROR com.codahale.metrics.ScheduledReporter - Exception thrown from Slf4jReporter#report. Exception was suppressed.
    java.lang.OutOfMemoryError: Java heap space

HttpTaskTest STANDARD_ERROR
    Exception in thread "RxIoScheduler-1 (Evictor)" java.lang.IllegalMonitorStateException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signal(AbstractQueuedSynchronizer.java:1981)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1192)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
    Exception in thread "RxComputationScheduler-2" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
<========-----> 65% EXECUTING [6m 5s]
> IDLE
> IDLE
> :conductor-contribs:test > 40 tests completed
> :conductor-contribs:test > Executing test com.netflix.conductor.contribs.tasks.http.HttpTaskTest
^C%
```

**Comment by bfrggit** [comment]
Another observation is that, when this error happens, the build process gets stuck instead of getting killed, resulting in memory-consuming `java` process running in background even if I use `Ctrl` + `C` to stop Gradle.

**Comment by jxu-nflx** [comment]
Hello @bfrggit the contribs tests are excluded from our build pipeline: https://github.com/Netflix/conductor/blob/main/.github/workflows/ci.yml#L45 And we are going to move the contribs module out to a seperate repo soon. For now, please just ignore the tests locally.

**Comment by bfrggit** [comment]
Okay. Thanks for the info.
