### ISSUE TITLE
[UI] Blank Screen: `Uncaught TypeError: workflowDef.tasks is not iterable`

### ISSUE THREAD

**Issue by gardusig** [Netflix/conductor#2977]
**Describe the bug**
Blank screen when attempting to create a `Workflow Definition` after creating a `Task Definition`.

**Details**
Conductor version: latest (`main` branch).
Simple setup with `./gradlew bootRun` and `yarn run start`.

**To Reproduce**
1. Go to `http://localhost:5001`
1. Click on `Definitions`
1. Click on `Tasks`
1. Click on `+ New Task Definition`
1. Click on `Definitions`
1. Click on `+ New Workflow Definition` 
1. Blank Screen (see errors at console)

**Expected behavior**
No blank screen. Although, works fine after page refresh.

**Screenshots**

https://user-images.githubusercontent.com/32961921/167307014-1e1d6526-a812-478b-bc71-cdb40d922844.mov

**Comment by gardusig** [comment]
Console output:
```
Uncaught TypeError: workflowDef.tasks is not iterable
    at WorkflowDAG.defToGraph (WorkflowDAG.js:74:1)
    at WorkflowDAG.constructGraph (WorkflowDAG.js:36:1)
    at new WorkflowDAG (WorkflowDAG.js:13:1)
    at WorkflowDefinition.jsx:134:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at performSyncWorkOnRoot (react-dom.development.js:21737:1)
    at react-dom.development.js:11089:1
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:1)
    at flushSyncCallbackQueue (react-dom.development.js:11072:1)
    at discreteUpdates$1 (react-dom.development.js:21893:1)
    at discreteUpdates (react-dom.development.js:806:1)
    at dispatchDiscreteEvent (react-dom.development.js:4168:1)
index.js:1 The above error occurred in the <Workflow> component:
    in Workflow (at App.jsx:97)
    in Route (at App.jsx:96)
    in Switch (at App.jsx:83)
    in div (at App.jsx:82)
    in div (at App.jsx:55)
    in App (at src/index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:25)
    in ThemeProvider (at provider.jsx:8)
    in Provider (at src/index.js:24)
    in QueryClientProvider (at src/index.js:23)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
react-dom.development.js:11102 Uncaught TypeError: workflowDef.tasks is not iterable
    at WorkflowDAG.defToGraph (WorkflowDAG.js:74:1)
    at WorkflowDAG.constructGraph (WorkflowDAG.js:36:1)
    at new WorkflowDAG (WorkflowDAG.js:13:1)
    at WorkflowDefinition.jsx:134:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at performSyncWorkOnRoot (react-dom.development.js:21737:1)
    at react-dom.development.js:11089:1
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:1)
    at flushSyncCallbackQueue (react-dom.development.js:11072:1)
    at discreteUpdates$1 (react-dom.development.js:21893:1)
    at discreteUpdates (react-dom.development.js:806:1)
    at dispatchDiscreteEvent (react-dom.development.js:4168:1)
VM138:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1:1)
```

**Comment by jxu-nflx** [comment]
@peterlau could you take a look at this when you got a chance?

**Comment by peterlau** [comment]
Reproduced. Fix in progress.
