### ISSUE TITLE
Bug in the post endpoint for updating a task /api/task

### ISSUE THREAD

**Issue by LemonDevv** [Netflix/conductor#3039]
I've got conductor + dynomite deployed into k8s.

I've got the task being executed in my workflow but when it comes to update the task through the following endpoint:

[POST] task-resource
/api/tasks

 i am getting the following error:

`{
    "status": 500,
    "code": null,
    "message": "INTERNAL_ERROR - Content type 'application/json;charset=UTF-8' not supported",
    "instance": "conductorserver-deployment-856c8799d9-dlvrd",
    "retryable": false,
    "validationErrors": null
}`

Is this a known issue? How can i resolve this issue

**Comment by CherishSantoshi** [comment]
@manan164 @v1r3n @boney9

**Comment by manan164** [comment]
Hi @LemonDevv , Looks like the wrong JSON is being passed. Some extra characters are being passed. Can you please share the complete curl command that is being invoked? Mask the URLs and other sensitive information.

**Comment by LemonDevv** [comment]
Hi @manan164 

Thanks for getting back to me quickly.

Below is the cURL command. 

`curl --location --request POST 'https://someurl.com/conductorserver/api/tasks' \
--header 'Content-Type: application/json' \
--data-raw '{
    "workflowInstanceId": "9ffbcbbf-e90d-4102-beab-988b03db330d",
    "taskId": "b7efc718-a8ba-40e8-9e5f-4dcbcc05ca7b",
    "reasonForIncompletion" : "",
    "callbackAfterSeconds": 0,
    "status": "COMPLETED"
}'`

**Comment by manan164** [comment]
HI @LemonDevv , Can you please try via conductor swagger? I just tried and it worked.
![image](https://user-images.githubusercontent.com/1897158/173073025-01284147-7970-4013-a49d-0fc7f5d9f5c6.png)

**Comment by LemonDevv** [comment]
Hi @manan164 

I have tried through the conductor swagger API, postman and through the client. They all give the same issue.

![image](https://user-images.githubusercontent.com/65916409/173075333-85421c4a-a5e0-44c7-8325-be7ecf95b6a9.png)


Could this be a problem with how it's deployed? I notice you have it running on your localhost.

**Comment by manan164** [comment]
Hi @LemonDevv , It should not be a conductor deployment issue. This is the highest used api in the conductor. Can you please try setting up locally? Or I think some garbage characters are being passed in body. Try creating body by manually typing.

**Comment by LemonDevv** [comment]
Hi @manan164 

I have run this locally as well and i'm having the same problem. I manually typed in the body and had the same result.

![image](https://user-images.githubusercontent.com/65916409/173092665-f28d49e1-0f4e-45af-894b-1efc870d12e8.png)

**Comment by LemonDevv** [comment]
@manan164 

config map for k8s for the storage 

`apiVersion: v1
kind: ConfigMap
metadata:
  name: server-storage-config
data:
  config.properties: |
    # Servers.
    conductor.grpc-server.enabled=false

    # Database persistence type.
    conductor.db.type=dynomite

    # Dynomite Cluster details.
    # format is host:port:rack separated by semicolon
    conductor.redis.hosts=instance.main.svc.cluster.local:8102:us-east-1c

    # Dynomite cluster name
    conductor.redis.clusterName=dyno1

    # Namespace for the keys stored in Dynomite/Redis
    conductor.redis.workflowNamespacePrefix=conductor

    # Namespace prefix for the dyno queues
    conductor.redis.queueNamespacePrefix=conductor_queues

    # No. of threads allocated to dyno-queues (optional)
    queues.dynomite.threads=10

    # By default with dynomite, we want the repairservice enabled
    conductor.app.workflowRepairServiceEnabled=true

    # Non-quorum port used to connect to local redis.  Used by dyno-queues.
    # When using redis directly, set this to the same port as redis server
    # For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
    conductor.redis.queuesNonQuorumPort=22122

    # Elastic search instance indexing is enabled.
    conductor.indexing.enabled=false

    # Transport address to elasticsearch
    #conductor.elasticsearch.url=http://es:9200

    # Name of the elasticsearch cluster
    #conductor.elasticsearch.indexName=conductor
    #conductor.event-queues.amqp.queueType=classic
    #conductor.event-queues.amqp.sequentialMsgProcessing=true

    # Additional modules for metrics collection exposed via logger (optional)
    # conductor.metrics-logger.enabled=true
    # conductor.metrics-logger.reportPeriodSeconds=15

    # Additional modules for metrics collection exposed to Prometheus (optional)
    # conductor.metrics-prometheus.enabled=true
    # management.endpoints.web.exposure.include=prometheus

    # To enable Workflow/Task Summary Input/Output JSON Serialization, use the following:
    # conductor.app.summary-input-output-json-serialization.enabled=true

    # Load sample kitchen sink workflow
    loadSample=false

Logs from our log server when the API is hit:


```
... 36 more
at   org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)   ~[spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)   ~[spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)   ~[spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:211)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
Caused by:   org.springframework.web.HttpMediaTypeNotSupportedException: Content type   'application/json;charset=UTF-8' not supported
at java.lang.Thread.run(Unknown Source)   [?:?]
at   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)   [spring-boot-actuator-2.6.7.jar!/:2.6.7]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)   [tomcat-embed-websocket-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)   [tomcat-embed-core-9.0.62.jar!/:?]
at   javax.servlet.http.HttpServlet.service(HttpServlet.java:764)   [tomcat-embed-core-9.0.62.jar!/:2.5]
at   org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   javax.servlet.http.HttpServlet.service(HttpServlet.java:681)   [tomcat-embed-core-9.0.62.jar!/:2.5]
at   org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1138)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1327)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:142)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:75)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:428)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)   [spring-web-5.3.19.jar!/:5.3.19]
at   java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at   jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)   ~[?:?]
at   jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at   jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at   com.netflix.conductor.rest.controllers.ApplicationExceptionMapper.handleAll(ApplicationExceptionMapper.java:63)   [conductor-rest-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
com.netflix.conductor.core.exception.ApplicationException:   INTERNAL_ERROR - Content type 'application/json;charset=UTF-8' not supported
4050723 [http-nio-8080-exec-1] ERROR   com.netflix.conductor.rest.controllers.ApplicationExceptionMapper [] - Error   ApplicationException url: '/api/tasks'
at java.lang.Thread.run(Unknown Source)   [?:?]
at   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)   [spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)   [spring-boot-actuator-2.6.7.jar!/:2.6.7]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)   [tomcat-embed-websocket-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)   [tomcat-embed-core-9.0.62.jar!/:?]
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)   [tomcat-embed-core-9.0.62.jar!/:?]
at   javax.servlet.http.HttpServlet.service(HttpServlet.java:764)   [tomcat-embed-core-9.0.62.jar!/:2.5]
at   org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   javax.servlet.http.HttpServlet.service(HttpServlet.java:681)   [tomcat-embed-core-9.0.62.jar!/:2.5]
at   org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)   [spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)   ~[spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)   ~[spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)   ~[spring-web-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
at   org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:211)   ~[spring-webmvc-5.3.19.jar!/:5.3.19]
org.springframework.web.HttpMediaTypeNotSupportedException:   Content type 'application/json;charset=UTF-8' not supported
4050723 [http-nio-8080-exec-1] ERROR   com.netflix.conductor.rest.controllers.ApplicationExceptionMapper [] - Error   HttpMediaTypeNotSupportedException url: '/api/tasks'
```

**Comment by LemonDevv** [comment]
@manan164 

application.properties:

```
spring.application.name=conductor
springdoc.api-docs.path=/api-docs
management.endpoints.web.base-path=/conductorserver
springdoc.swagger-ui.configUrl=/conductorserver/api-docs/swagger-config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.oauth2RedirectUrl=/conductorserver/swagger-ui/oauth2-redirect.html
conductor.db.type=dynomite

conductor.indexing.enabled=false

#Redis configuration details.
#format is host:port:rack separated by semicolon
#Auth is supported. Password is taken from host[0]. format: host:port:rack:password
conductor.redis.hosts=dyno1:8102:us-east-1c;host2:port:rack:host3:port:rack

#namespace for the keys stored in Dynomite/Redis
conductor.redis.workflowNamespacePrefix=

#namespace prefix for the dyno queues
conductor.redis.queueNamespacePrefix=

#no. of threads allocated to dyno-queues
queues.dynomite.threads=10

# By default with dynomite, we want the repair service enabled
conductor.workflow-repair-service.enabled=true

#non-quorum port used to connect to local redis.  Used by dyno-queues
conductor.redis.queuesNonQuorumPort=22122

# For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property.
conductor.redis.availabilityZone=us-east-1c
#conductor.redis.maxIdleConnections=8
#conductor.redis.minIdleConnections=5
#conductor.redis.minEvictableIdleTimeMillis = 1800000
#conductor.redis.timeBetweenEvictionRunsMillis = -1L
#conductor.redis.testWhileIdle = false
#conductor.redis.numTestsPerEvictionRun = 3

#Transport address to elasticsearch
conductor.elasticsearch.url=localhost:9300

#Name of the elasticsearch cluster
conductor.elasticsearch.indexName=conductor

#Elasticsearch major release version.
conductor.elasticsearch.version=6
#conductor.elasticsearch.version=7

# Default event queue type to listen on for wait task
conductor.default-event-queue.type=sqs
	
#zookeeper
# conductor.zookeeper-lock.connectionString=host1.2181,host2:2181,host3:2181
# conductor.zookeeper-lock.sessionTimeoutMs
# conductor.zookeeper-lock.connectionTimeoutMs
# conductor.zookeeper-lock.namespace

#disable locking during workflow execution
conductor.app.workflow-execution-lock-enabled=false
conductor.workflow-execution-lock.type=noop_lock

#Redis cluster settings for locking module
# conductor.redis-lock.serverType=single
#Comma separated list of server nodes
# conductor.redis-lock.serverAddress=redis://127.0.0.1:6379
#Redis sentinel master name
# conductor.redis-lock.serverMasterName=master
# conductor.redis-lock.namespace

#Following properties set for using AMQP events and tasks with conductor:
#(To enable support of AMQP queues)
#conductor.event-queues.amqp.enabled=true

# Here are the settings with default values:
#conductor.event-queues.amqp.hosts=<rabbitmq serverip>
#conductor.event-queues.amqp.username=<username>
#conductor.event-queues.amqp.password=<password>

#conductor.event-queues.amqp.virtualHost=/
#conductor.event-queues.amqp.port=5672
#conductor.event-queues.amqp.useNio=false
#conductor.event-queues.amqp.batchSize=1
#conductor.event-queues.amqp.pollTimeDuration=100ms
#conductor.event-queues.amqp.queueType=classic
#conductor.event-queues.amqp.sequentialMsgProcessing=true
#conductor.event-queues.amqp.connectionTimeoutInMilliSecs=180000
#conductor.event-queues.amqp.networkRecoveryIntervalInMilliSecs=5000
#conductor.event-queues.amqp.requestHeartbeatTimeoutInSecs=30
#conductor.event-queues.amqp.handshakeTimeoutInMilliSecs=180000
#conductor.event-queues.amqp.maxChannelCount=5000
#conductor.event-queues.amqp.limit=50
#conductor.event-queues.amqp.duration=1000
#conductor.event-queues.amqp.retryType=REGULARINTERVALS

#conductor.event-queues.amqp.useExchange=true( exchange or queue)
#conductor.event-queues.amqp.listenerQueuePrefix=myqueue
# Use durable queue ?
#conductor.event-queues.amqp.durable=false
# Use exclusive queue ?
#conductor.event-queues.amqp.exclusive=false
# Enable support of priorities on queue. Set the max priority on message.
# Setting is ignored if the value is lower or equals to 0
#conductor.event-queues.amqp.maxPriority=-1

# To enable Workflow/Task Summary Input/Output JSON Serialization, use the following:
# conductor.app.summary-input-output-json-serialization.enabled=true

# Additional modules for metrics collection exposed to Prometheus (optional)
# conductor.metrics-prometheus.enabled=true
# management.endpoints.web.exposure.include=prometheus

# Additional modules for metrics collection exposed to Datadog (optional)
management.metrics.export.datadog.enabled=${conductor.metrics-datadog.enabled:false}
management.metrics.export.datadog.api-key=${conductor.metrics-datadog.api-key:}

```

**Comment by LemonDevv** [comment]
@manan164 

I have found the issue - 

I had added in addCorsMappings to the RestConfiguration.java so that i could do testing locally of a UI i had loaded the swagger spec into. I removed the cors mapping and now i can hit the endpoint successfully.

I don't know why that would cause an issue to that endpoint. Would you know why?

**Comment by manan164** [comment]
Hi @LemonDevv Awesome, I think adding corsMapping is adding a header for content-type to be charset. But yeah thanks for solving this.  Just to double-check try invoking other apis, if they all give the same error then there is an issue in mapping.

**Comment by LemonDevv** [comment]
@manan164  The other APIs worked fine. I could create tasks,workflows etc. Dont know what was the issue with this API. Maybe one for you guys to look into. I can close this now. Thanks.
