### ISSUE TITLE
conducto is failed to load after restarting docker compose with postgress (could not upload workflows)

### ISSUE THREAD

**Issue by johnico** [Netflix/conductor#3095]
I have manages to fixed this issue :
https://github.com/Netflix/conductor/issues/3093. 

so now i have postgress working and elastic - but now after restarting the conductor refuse to work 
and throw lot of exceptions :

**To Reproduce**
 added     runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.9.1' under build.gradle
 
 run docker-compoe -f docker-compose.yaml -f docker-compose-postgress.yaml
 
add workflow
run workflow
run docker-compose down
run docker-compose up

```
 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
docker-conductor-server-1  | 38862 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
docker-conductor-server-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
```

```
 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
```

```
docker-conductor-server-1  | 127302 [pool-2-thread-1] ERROR com.netflix.conductor.postgres.dao.PostgresMetadataDAO [] - refresh TaskDefs failed
docker-conductor-server-1  | com.netflix.conductor.core.exception.ApplicationException: BACKEND_ERROR - HikariDataSource HikariDataSource (HikariPool-1) has been closed.
docker-conductor-server-1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransaction(PostgresBaseDAO.java:136) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
docker-conductor-server-1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.lambda$getWithRetriedTransactions$3(PostgresBaseDAO.java:147) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
docker-conductor-server-1  | 	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.3.jar!/:?]
docker-conductor-server-1  | 	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-1.3.3.jar!/:?]
docker-conductor-server-1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithRetriedTransactions(PostgresBaseDAO.java:147) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
docker-conductor-server-1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.withTransaction(PostgresBaseDAO.java:194) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
docker-conductor-server-1  | 	at com.netflix.conductor.postgres.dao.PostgresMetadataDAO.refreshTaskDefs(PostgresMetadataDAO.java:472) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
docker-conductor-server-1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
docker-conductor-server-1  | 	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
docker-conductor-server-1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
docker-conductor-server-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
docker-conductor-server-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
docker-conductor-server-1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
docker-conductor-server-1  | Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
docker-conductor-server-1  | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-4.0.3.jar!/:?]
docker-conductor-server-1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransaction(PostgresBaseDAO.java:119) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
```

**Comment by jxu-nflx** [comment]
Hello @johnico based on the error log you posted: `Error creating bean with name 'es6IndexRestDAO'. Do you have ES container running?

**Comment by johnico** [comment]
```
run docker-compoe -f docker-compose.yaml -f docker-compose-postgress.yaml


```

yes its trying to up the es from here but there are lot of errors

**Comment by jxu-nflx** [comment]
Can you post the errors?

**Comment by LiadDrori** [comment]
I'm also getting the same errors after restarting the docker-compose
the only way to solve it is by removing the Postgres and elastic volumes
