### ISSUE TITLE
IOException: Premature EOF 

### ISSUE THREAD

**Issue by sung-k** [Netflix/conductor#323]
`Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: 2017-09-13 12:23:27.666 ERROR 12434 --- [pool-3-thread-1] c.v.c.c.ConductorWorkflowTaskCoordinator : Error when polling for task com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Premature EOF
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: java.lang.RuntimeException: com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Premature EOF
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.netflix.conductor.client.http.ClientBase.handleException(ClientBase.java:189) ~[conductor-client-1.7.1.jar!/:1.7.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:179) ~[conductor-client-1.7.1.jar!/:1.7.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.netflix.conductor.client.http.TaskClient.poll(TaskClient.java:88) ~[conductor-client-1.7.1.jar!/:1.7.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.ibm.cloud.video.c3d4.conductor.ConductorWorkflowTaskCoordinator.pollForTask(ConductorWorkflowTaskCoordinator.java:254) [classes!/:na]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.ibm.cloud.video.c3d4.conductor.ConductorWorkflowTaskCoordinator.lambda$null$0(ConductorWorkflowTaskCoordinator.java:230) [classes!/:na]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: Caused by: com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Premature EOF
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:644) ~[jersey-client-1.19.1.jar!/:1.19.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:604) ~[jersey-client-1.19.1.jar!/:1.19.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.sun.jersey.api.client.WebResource.handle(WebResource.java:698) ~[jersey-client-1.19.1.jar!/:1.19.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.sun.jersey.api.client.WebResource.access$300(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:514) ~[jersey-client-1.19.1.jar!/:1.19.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:176) ~[conductor-client-1.7.1.jar!/:1.7.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: ... 10 common frames omitted
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: Caused by: java.io.IOException: Premature EOF
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375) ~[na:1.8.0_121]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:522) ~[jackson-core-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:129) ~[jackson-core-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:246) ~[jackson-core-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1271) ~[jackson-core-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:810) ~[jackson-core-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.jaxrs.base.ProviderBase._createParser(ProviderBase.java:829) ~[jackson-jaxrs-base-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:770) ~[jackson-jaxrs-base-2.8.8.jar!/:2.8.8]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634) ~[jersey-client-1.19.1.jar!/:1.19.1]
Sep 13 16:23:27 ip-10-240-36-115 sh[12433]: ... 15 common frames omitted`

We are currently seeing this issue intermittently across various Conductor clients. This causes workflows to be stuck. Any ideas as to where to begin looking? 

We are using Conductor 1.7.6, Dynomite 0.5.9, Redis 3.2.10. 
We have not modified any Conductor server or client code in any way EXCEPT changing the polling interval. Dynomite seem to be correctly seeding with each other. When we push a task/workflow def through conductor, we see the entries replicated in each Redis instance. Also, our Dynomite cluster has 3 nodes, each in its own AZ.

**Comment by sung-k** [comment]
Our setup at the time of writing the above issue was having a single conductor instance behind an ELB, talking to 3 dynomite nodes, which were spread across 3 AZs. We've made several tweaks since then, which includes 3 AZs each having 1 conductor and a dynomite cluster with 3 nodes. Basically 3 conductors behind 1 ELB, and 9 dynomite nodes across 3 clusters. We are also using Conductor 1.8.0, dyno-core and dyno-jedis 1.5.9, Dynomite 0.5.9, and Redis 3.2.10.

Something along the way stopped the above error. Closing the issue.
