### ISSUE TITLE
ACK is not working

### ISSUE THREAD

**Issue by yamingwa** [Netflix/conductor#326]
Hi there,

I am trying to do a demo for conductor remote workers and I find that the `/tasks/{taskId}/ack` API does NOT work. 
Configuration I am using:
```
conductor version: conductor-server-1.8.0
config file:       config-local.properties (db=memory)
```

Steps to re-produce this issue:
1. start conductor.
2. start worker and poll a task from conductor.
3. worker sends an ack to conductor if it gets a task.
4. call `/tasks/queue/all/verbose` in conductor swagger-UI, response will be like:
```
  "transcode": {
    "c": {
      "size": 0,
      "uacked": 1
    }
  },
```
This means the task is actually not acked by worker right?
5. if work keeps polling, it will get the same task instance after 60 seconds which means the task has been rescheduled by conductor.

I use the following task definition for "transcode task":
```
{
  "name": "transcode",
  "retryCount": 3,
  "timeoutSeconds": 0,
  "inputKeys": [
    "prog_name",
    "source_path",
    "target_path",
    "traget_format"
  ],
  "outputKeys": [
    "result"
  ],
  "timeoutPolicy": "TIME_OUT_WF",
  "retryLogic": "FIXED",
  "retryDelaySeconds": 600,
  "responseTimeoutSeconds": 5
}
```
For the `responseTimeoutSeconds` here, I set it to  be 5 seconds and just want to test the `/tasks/{taskId}/ack` API. 

Maybe I have some misunderstanding on these attributes like `responseTimeoutSeconds`, please help me with this issue, thanks.

**Update:** Well, I find this may be related to the exception in elasticsearch. I get `SearchParseException[No mapping found for [createdTime] in order to sort on]`  in conductor server log. Will do some further investigation. The exception details:
```
Failed to execute phase [query], all shards failed; shardFailures {[3TnwcTg8Qo6zBqOKYuo2Jg][task_log_20170903][0]: RemoteTransportException[[Mary "Skeeter" MacPherran][172.18.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"e5c4bacf-117b-4cde-9c9c-54f3e06412d1\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[3TnwcTg8Qo6zBqOKYuo2Jg][task_log_20170903][1]: RemoteTransportException[[Mary "Skeeter" MacPherran][172.18.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"e5c4bacf-117b-4cde-9c9c-54f3e06412d1\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[3TnwcTg8Qo6zBqOKYuo2Jg][task_log_20170903][2]: RemoteTransportException[[Mary "Skeeter" MacPherran][172.18.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"e5c4bacf-117b-4cde-9c9c-54f3e06412d1\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[3TnwcTg8Qo6zBqOKYuo2Jg][task_log_20170903][3]: RemoteTransportException[[Mary "Skeeter" MacPherran][172.18.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"e5c4bacf-117b-4cde-9c9c-54f3e06412d1\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[3TnwcTg8Qo6zBqOKYuo2Jg][task_log_20170903][4]: RemoteTransportException[[Mary "Skeeter" MacPherran][172.18.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"e5c4bacf-117b-4cde-9c9c-54f3e06412d1\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
     Caused by: SearchParseException[No mapping found for [createdTime] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more

```

**Comment by yamingwa** [comment]
It seems like a bug in conductor-server. I tried `config.properties` instead of `config-local.properties`, the problem remains.

What I did more is that, after I polled task from conductor, I called the `/tasks/{taskId}/ack` from Swagger-UI immediately, the response was `true` but the task was also unacknowledged.

ping @v1r3n , please help with this issue if you have time, thanks very much.

**Comment by yamingwa** [comment]
The problem here is about this variable: `unackHandlerIntervalInMS` in `com.netflix.dyno.queues.redis.RedisQueues`. It determines how often a background thread will be executed to process the unacknowledged tasks and it is fixed as 60 seconds.  The logic here is as follows:

1. Worker sends ACK for a task to conductor and gets `true `returned.
2.  If the task has `responseTimeoutSeconds `set for a non-zero number, it will be put into the `unack` queue with a score as `System.currentTimeMillis() + responseTimeoutSeconds` . In other words, a task with `responseTimeoutSeconds > 0` will never be acknowledged. Every time conductor receives an ACK request for that task, it will delay the task's `unAckTimeout ` for `responseTimeoutSeconds` thus  the task's score is incremented.
3. If the task has responseTimeoutSeconds set as zero, then it will be acknowledged and will be removed from `unack `queue immediately.
4. The background thread will be executing every 60 seconds, and requeuing any task with `score > System.currentTimeMillis()`.
5. So, a `responseTimeoutSeconds ` less than 60 seconds is useless and also meaningless.

Closed.
