### ISSUE TITLE
Starting server error - java.lang.ClassNotFoundException: class_extending_com.google.inject.AbstractModule

### ISSUE THREAD

**Issue by smilejinho** [Netflix/conductor#334]
I am trying to run conductor server on my centos 7 server.

I have  run "java -jar conductor-server-1.8.2-rc1-all.jar ./server.properties ./log4j.properties"
with server.properties as

db=redis
workflow.dynomite.cluster.hosts=127.0.0.1:6379:us-east-1c
workflow.dynomite.cluster.name=dyno_cluster_name
workflow.dynomite.connection.maxConnsPerHost=31
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=6379
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
conductor.additional.modules=class_extending_com.google.inject.AbstractModule

and I have got following error

Using ./server.properties
Using log4j config ./log4j.properties
0    [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
7    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=127.0.0.1, ipAddress=null, port=6379, rack: us-east-1c, datacenter: us-east-1, status: Up]
7    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=127.0.0.1, ipAddress=null, port=6379, rack: us-east-1c, datacenter: us-east-1, status: Up], with conns:31
63   [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 31 of 31 to Host [hostname=127.0.0.1, ipAddress=null, port=6379, rack: us-east-1c, datacenter: us-east-1, status: Up]
81   [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - registered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
84   [main] INFO  com.netflix.conductor.server.ConductorServer  - Starting conductor server using dynomite/redis cluster dyno_cluster_name

                     _            _
  ___ ___  _ __   __| |_   _  ___| |_ ___  _ __
 / __/ _ \| '_ \ / _` | | | |/ __| __/ _ \| '__|
| (_| (_) | | | | (_| | |_| | (__| || (_) | |
 \___\___/|_| |_|\__,_|\__,_|\___|\__\___/|_|

321  [main] INFO  com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO  - DynoQueueDAO initialized with prefix conductor_queues.test!
1031 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task HTTP
1246 [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
1247 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task JSON_JQ_TRANSFORM
1256 [main] WARN  com.netflix.conductor.server.ConductorConfig  - class_extending_com.google.inject.AbstractModule
java.lang.ClassNotFoundException: class_extending_com.google.inject.AbstractModule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.netflix.conductor.server.ConductorConfig.getAdditionalModules(ConductorConfig.java:128)
        at com.netflix.conductor.server.ServerModule.configure(ServerModule.java:102)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.netflix.conductor.server.ConductorServer.start(ConductorServer.java:201)
        at com.netflix.conductor.server.Main.main(Main.java:62)
1612 [main] INFO  org.elasticsearch.plugins  - [Lloigoroth] modules [], plugins [], sites []
2327 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - System Task Worker Initialized with 10 threads and a callback time of 30 second and queue size 100 with pollCount 10
2327 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task SUB_WORKFLOW
2328 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task WAIT
2328 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task EVENT
2328 [Thread-2] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Started listening HTTP
2339 [main] INFO  org.eclipse.jetty.util.log  - Logging initialized @2826ms
2435 [main] INFO  org.eclipse.jetty.server.Server  - jetty-9.3.z-SNAPSHOT
Sep 26, 2017 3:36:56 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  com.netflix.conductor.server.resources
  io.swagger.jaxrs.json
  io.swagger.jaxrs.listing
3372 [pool-9-thread-1] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve HTTP
Sep 26, 2017 3:36:59 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class com.netflix.conductor.server.resources.MetadataResource
  class com.netflix.conductor.server.resources.EventResource
  class io.swagger.jaxrs.listing.AcceptHeaderApiListingResource
  class io.swagger.jaxrs.listing.ApiListingResource
  class com.netflix.conductor.server.resources.TaskResource
  class com.netflix.conductor.server.resources.WorkflowResource
  class com.netflix.conductor.server.resources.AdminResource
Sep 26, 2017 3:36:59 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class com.netflix.conductor.server.resources.GenericExceptionMapper
  class com.netflix.conductor.server.resources.ApplicationExceptionMapper
  class com.netflix.conductor.server.resources.WebAppExceptionMapper
  class io.swagger.jaxrs.listing.SwaggerSerializers
Sep 26, 2017 3:36:59 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider as a provider class
Sep 26, 2017 3:36:59 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19.1 03/11/2016 02:42 PM'
Sep 26, 2017 3:36:59 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.ApplicationExceptionMapper to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:36:59 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.GenericExceptionMapper to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:36:59 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
Sep 26, 2017 3:37:00 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.AdminResource to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:37:00 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.EventResource to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:37:00 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.MetadataResource to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:37:00 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.TaskResource to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:37:00 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.WorkflowResource to GuiceInstantiatedComponentProvider
Sep 26, 2017 3:37:00 PM com.sun.jersey.spi.inject.Errors processErrorMessages
WARNING: The following warnings have been detected with resource and/or provider classes:
  WARNING: Return type java.util.Map<java.lang.String, ?> of method public java.util.Map<java.lang.String, ?> com.netflix.conductor.server.resources.EventResource.getEventQueues(boolean) is not resolvable to a concrete type
5926 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.s.ServletContextHandler@6da9dc6{/,jar:file:/data/conductor/conductor-server-1.8.1-all.jar!/swagger-ui,AVAILABLE}
5933 [main] INFO  org.eclipse.jetty.server.AbstractConnector  - Started ServerConnector@37864b77{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
5933 [main] INFO  org.eclipse.jetty.server.Server  - Started @6420ms
Started server on http://localhost:8080/

**Comment by smilejinho** [comment]
I have removed "conductor.additional.modules=class_extending_com.google.inject.AbstractModule",
and server started successfully.
But I can't access UI.

Is there any other option to start UI server ?

**Comment by smilejinho** [comment]
I have found how to start UI server. And I have run followings.
npm install
gulp build
cd dist
WF_SERVER=http://localhost:8080/api/; node server.js

But, I got the following errors.

/data/conductor/source/conductor/ui/dist/webpack:/~/react-dom/cjs/react-dom-server.node.development.js:3251
})();
 ^
TypeError: Cannot read property 'ReactCurrentOwner' of undefined
    at /data/conductor/source/conductor/ui/dist/webpack:/~/react-dom/cjs/react-dom-server.node.development.js:939:1
    at Object._hyphenPattern (/data/conductor/source/conductor/ui/dist/webpack:/~/react-dom/cjs/react-dom-server.node.development.js:3251:2)
    at __webpack_require__ (/data/conductor/source/conductor/ui/dist/webpack:/webpack/bootstrap 77b553901d86aaaac0af:19:1)
    at Object.<anonymous> (/data/conductor/source/conductor/ui/dist/webpack:/~/react-dom/server.js:6:1)
    at __webpack_require__ (/data/conductor/source/conductor/ui/dist/webpack:/webpack/bootstrap 77b553901d86aaaac0af:19:1)
    at Object.canUseDOM (/data/conductor/source/conductor/ui/dist/webpack:/src/server.js:4:1)
    at __webpack_require__ (/data/conductor/source/conductor/ui/dist/webpack:/webpack/bootstrap 77b553901d86aaaac0af:19:1)
    at Object.<anonymous> (/data/conductor/source/conductor/ui/dist/server.js:48:19)
    at __webpack_require__ (/data/conductor/source/conductor/ui/dist/webpack:/webpack/bootstrap 77b553901d86aaaac0af:19:1)
    at /data/conductor/source/conductor/ui/dist/webpack:/webpack/bootstrap 77b553901d86aaaac0af:39:1

**Comment by smilejinho** [comment]
I downloaded 1.8.1 version. 
And, UI server works fine.
