### ISSUE TITLE
Elasticsearch getTotalHits() fails

### ISSUE THREAD

**Issue by pjanzen** [Netflix/conductor#3413]
Hi,

I am running conductor-community-server-3.13.2-boot.jar and I have set this up with the following config.

`
spring.application.name=conductor
springdoc.api-docs.path=/api-docs

conductor.db.type=postgres

spring.datasource.url=jdbc:postgresql://database_host:5432/conductor
spring.datasource.username=conductor_rw
spring.datasource.password=OneRandomPasSw0rd

\# Hikari pool sizes are -1 by default and prevent startup
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

\# Elasticsearch related
conductor.indexing.enabled=true
conductor.elasticsearch.url=localhost:9300
conductor.elasticsearch.indexName=conductor
conductor.elasticsearch.version=6
conductor.elasticsearch.index-replicas-count=0

\# Default event queue type to listen on for wait task
conductor.default-event-queue.type=sqs

\#disable locking during workflow execution
conductor.app.workflow-execution-lock-enabled=false
conductor.workflow-execution-lock.type=noop_lock

\#Following properties set for using AMQP events and tasks with conductor:
\#(To enable support of AMQP queues)
conductor.event-queues.amqp.enabled=true

\# Here are the settings with default values:
conductor.event-queues.amqp.hosts=amqp_host
conductor.event-queues.amqp.username=conductor
conductor.event-queues.amqp.password=OneRandomPasSw0rd!

conductor.event-queues.amqp.virtualHost=conductor-qa1
conductor.event-queues.amqp.port=5672
conductor.event-queues.amqp.useNio=false
conductor.event-queues.amqp.useSslProtocol=false
conductor.event-queues.amqp.batchSize=1
conductor.event-queues.amqp.pollTimeDuration=100ms
conductor.event-queues.amqp.queueType=classic
conductor.event-queues.amqp.sequentialMsgProcessing=true
conductor.event-queues.amqp.connectionTimeoutInMilliSecs=180000
conductor.event-queues.amqp.networkRecoveryIntervalInMilliSecs=5000
conductor.event-queues.amqp.requestHeartbeatTimeoutInSecs=30
conductor.event-queues.amqp.handshakeTimeoutInMilliSecs=180000
conductor.event-queues.amqp.maxChannelCount=5000
conductor.event-queues.amqp.limit=50
conductor.event-queues.amqp.duration=1000
conductor.event-queues.amqp.retryType=REGULARINTERVALS

conductor.event-queues.amqp.useExchange=true
conductor.event-queues.amqp.listenerQueuePrefix=con_classic
\# Use durable queue ?
conductor.event-queues.amqp.durable=true
\# Use exclusive queue ?
conductor.event-queues.amqp.exclusive=false
\# Enable support of priorities on queue. Set the max priority on message.
\# Setting is ignored if the value is lower or equals to 0
\#conductor.event-queues.amqp.maxPriority=-1

\# To enable Workflow/Task Summary Input/Output JSON Serialization, use the following:
conductor.app.summary-input-output-json-serialization.enabled=true

\# Additional modules for metrics collection exposed to Prometheus (optional)
\# conductor.metrics-prometheus.enabled=true
\# management.endpoints.web.exposure.include=prometheus
`

Running test workflow is going fine and I see data being pushed to elasticsearch

`[2022-12-22T06:43:32,827][INFO ][o.e.c.m.MetaDataMappingService] [PmGHO8a] [conductor_task/kZ3ysjL0T1Wfe-isvLuzDw] create_mapping [task]
[2022-12-22T06:44:02,963][INFO ][o.e.c.m.MetaDataMappingService] [PmGHO8a] [conductor_workflow/5UOzHbFPSwibmUiUiyjZBw] update_mapping [workflow]
[2022-12-22T06:44:03,787][INFO ][o.e.c.m.MetaDataMappingService] [PmGHO8a] [conductor_task/kZ3ysjL0T1Wfe-isvLuzDw] update_mapping [task]`

However, going to the UI / execution page the search always fails. In the log I get the following error.

`
2022-12-22 06:53:45.004 ERROR 83295 --- [nio-8080-exec-2] c.n.c.r.c.ApplicationExceptionMapper     : Error NestedServletException url: '/api/workflow/search'
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'long org.elasticsearch.search.SearchHits.getTotalHits()'
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082) [spring-webmvc-5.3.19.jar!/:5.3.19]
`

Full stacktrace

`2022-12-22 06:54:07.659 ERROR 83295 --- [nio-8080-exec-8] c.n.c.r.c.ApplicationExceptionMapper     : Error NestedServletException url: '/api/workflow/search'
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'long org.elasticsearch.search.SearchHits.getTotalHits()'
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082) [spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.19.jar!/:5.3.19]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [tomcat-embed-core-9.0.62.jar!/:2.5]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.19.jar!/:5.3.19]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.62.jar!/:2.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.19.jar!/:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.19.jar!/:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.6.7.jar!/:2.6.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.19.jar!/:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.19.jar!/:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.62.jar!/:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.62.jar!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'long org.elasticsearch.search.SearchHits.getTotalHits()'
	at com.netflix.conductor.es6.dao.index.ElasticSearchDAOV6.mapSearchResult(ElasticSearchDAOV6.java:849) ~[conductor-es6-persistence-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.es6.dao.index.ElasticSearchDAOV6.search(ElasticSearchDAOV6.java:823) ~[conductor-es6-persistence-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.es6.dao.index.ElasticSearchDAOV6.searchWorkflowSummary(ElasticSearchDAOV6.java:667) ~[conductor-es6-persistence-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.core.dal.ExecutionDAOFacade.searchWorkflowSummary(ExecutionDAOFacade.java:628) ~[conductor-core-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.service.ExecutionService.search(ExecutionService.java:387) ~[conductor-core-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.service.WorkflowServiceImpl.searchWorkflows(WorkflowServiceImpl.java:329) ~[conductor-core-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.service.WorkflowServiceImpl$$FastClassBySpringCGLIB$$c01ac20d.invoke(<generated>) ~[conductor-core-3.13.2.jar!/:3.13.2]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.19.jar!/:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.19.jar!/:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.19.jar!/:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar!/:5.3.19]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123) ~[spring-context-5.3.19.jar!/:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar!/:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar!/:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.19.jar!/:5.3.19]
	at com.netflix.conductor.service.WorkflowServiceImpl$$EnhancerBySpringCGLIB$$99e28bfe.searchWorkflows(<generated>) ~[conductor-core-3.13.2.jar!/:3.13.2]
	at com.netflix.conductor.rest.controllers.WorkflowResource.search(WorkflowResource.java:219) ~[conductor-rest-3.13.2.jar!/:3.13.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.19.jar!/:5.3.19]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.19.jar!/:5.3.19]
	... 43 more`

**Comment by manan164** [comment]
Hi @pjanzen ,
Which version of conductor server you are trying with?
I tried with the latest main and the `community-server-3.13.2`. Also, I have used the property you shared.
Looks like it is working for me.
Let me know if this works, or we can chat [here](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) for more real-time collaboration.
