### ISSUE TITLE
when i run simple java  project its asking token number

### ISSUE THREAD

**Issue by manojkumar968** [Netflix/conductor#3422]
when i run simple java  project its asking token number  but i do not know how to set token number in our project

## Proposed text

[main] INFO com.netflix.conductor.client.automator.TaskPollExecutor - Initialized the TaskPollExecutor with 1 threads
[main] INFO com.netflix.conductor.client.automator.TaskPollExecutor - Initialized the task lease extend executor
[main] WARN com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
[main] INFO com.netflix.config.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
[main] INFO com.netflix.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@7ee8290b
[pool-3-thread-1] WARN com.netflix.conductor.client.http.ClientBase - Unable to invoke Conductor API with uri: https://play.orkes.io/api/tasks/poll/8053task?workerid=shivendra-HP-All-in-One-22-c0xx, unexpected response from server: statusCode=401, responseBody='{"message":"Token cannot be null or empty","error":"INVALID_TOKEN","timestamp":1672808447076}
'.
[pool-3-thread-1] ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks
com.netflix.conductor.client.exception.ConductorClientException: Token cannot be null or empty {status=401, retryable: false}
	at com.netflix.conductor.client.http.ClientBase.handleUniformInterfaceException(ClientBase.java:339)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:213)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:187)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:135)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$2(TaskPollExecutor.java:162)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:45)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:160)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$init$0(TaskRunnerConfigurer.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[pool-3-thread-1] WARN com.netflix.conductor.client.http.ClientBase - Unable to invoke Conductor API with uri: https://play.orkes.io/api/tasks/poll/8053task?workerid=shivendra-HP-All-in-One-22-c0xx, unexpected response from server: statusCode=401, responseBody='{"message":"Token cannot be null or empty","error":"INVALID_TOKEN","timestamp":1672808448443}
'.
[pool-3-thread-1] ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks
com.netflix.conductor.client.exception.ConductorClientException: Token cannot be null or empty {status=401, retryable: false}
	at com.netflix.conductor.client.http.ClientBase.handleUniformInterfaceException(ClientBase.java:339)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:213)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:187)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:135)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$2(TaskPollExecutor.java:162)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:45)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:160)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$init$0(TaskRunnerConfigurer.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by v1r3n** [comment]
Hi @manojkumar968 play.orkes.io requires an authorization token.   
You can obtain the access keys by following the steps here: https://orkes.io/content/docs/getting-started/concepts/access-control-applications

Feel free to [connect](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) if you need further help.

**Comment by manojkumar968** [comment]
i got the token but i can not able to understand how to use that token in my simple java project 

# java code

package com.netflix.conductor.client.sample;
import java.util.Arrays;
import com.netflix.conductor.client.automator.TaskRunnerConfigurer;
import com.netflix.conductor.client.http.TaskClient;
import com.netflix.conductor.client.worker.Worker;

public class Main {

    public static void main(String[] args) {
        TaskClient taskClient = new TaskClient();
        taskClient.setRootURI("https://play.orkes.io/api/");
       
        int threadCount =1; 
        Worker worker = new SampleWorker("8054task");
        TaskRunnerConfigurer configurer =
                new TaskRunnerConfigurer. Builder(taskClient, Arrays.asList(worker))
                        .withThreadCount(threadCount)
                        .build();

        configurer.init();
    }
}

**Comment by manan164** [comment]
Hi @manojkumar968 , Please check [java-sdk-examples](https://github.com/conductor-sdk/java-sdk-examples). Please use the examples repo to create worker.
