### ISSUE TITLE
 while making conductor based project(simple java) and using orkes platform to define task and workflow , while running the project it is showing error(exception) token cannot be null or empty

### ISSUE THREAD

**Issue by manojkumar968** [Netflix/conductor#3424]
I have token(orkes) but i dont not able to use in my code could someone help how to insert token in my code

## Proposed text
i am getting this   @@error:

[main] INFO com.netflix.conductor.client.automator.TaskPollExecutor - Initialized the TaskPollExecutor with 1 threads
[main] INFO com.netflix.conductor.client.automator.TaskPollExecutor - Initialized the task lease extend executor
[main] WARN com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
[main] INFO com.netflix.config.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
[main] INFO com.netflix.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@7ee8290b
[pool-3-thread-1] WARN com.netflix.conductor.client.http.ClientBase - Unable to invoke Conductor API with uri: https://play.orkes.io/api/tasks/poll/8053task?workerid=shivendra-HP-All-in-One-22-c0xx, unexpected response from server: statusCode=401, responseBody='{"message":"Token cannot be null or empty","error":"INVALID_TOKEN","timestamp":1672836694593}
'.
[pool-3-thread-1] ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks
com.netflix.conductor.client.exception.ConductorClientException: Token cannot be null or empty {status=401, retryable: false}
	at com.netflix.conductor.client.http.ClientBase.handleUniformInterfaceException(ClientBase.java:339)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:213)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:187)
	at com.netflix.conductor.client.http.TaskClient.pollTask(TaskClient.java:135)
	at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$2(TaskPollExecutor.java:162)
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:45)
	at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:160)
	at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$init$0(TaskRunnerConfigurer.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by v1r3n** [comment]
@manojkumar968 do you want to chat [here](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg)? we can debug this realtime.
