### ISSUE TITLE
Error while validating pooled Jedis object.

### ISSUE THREAD

**Issue by ramyarajan-bnymellon** [Netflix/conductor#3431]
error.class:redis.clients.jedis.exceptions.JedisConnectionException
error.message:Unexpected end of stream.
error.stack:  at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
  at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
  at redis.clients.jedis.Protocol.process(Protocol.java:162)
  at redis.clients.jedis.Protocol.read(Protocol.java:227)
  at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
  at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)
  at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:380)
  at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:214)
  at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:745)
  at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:160)

**Comment by manan164** [comment]
Hi @ramyarajan-bnymellon , Thanks for reporting this. Can you please tell which version of the conductor you are trying to run? And if possible steps to reproduce this error?

**Comment by korolkevich7** [comment]
Hi, @ramyarajan-bnymellon. Do you use redis-haproxy?
