### ISSUE TITLE
When changing to es5 persistence,  Local Server cannot start 

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#346]
I have followed the steps here to change to es5 module:
https://github.com/Netflix/conductor/blob/master/es5-persistence/README.md 

Then when trying to run the server locally, exception is thrown.

[cquon@localhost server]$ ../gradlew server
Inferred project: conductor, version: 1.8.2-SNAPSHOT
Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.
:conductor-common:compileJava UP-TO-DATE
:conductor-common:processResources UP-TO-DATE
:conductor-common:classes UP-TO-DATE
:conductor-common:writeManifestProperties UP-TO-DATE
:conductor-common:jar UP-TO-DATE
:conductor-core:compileJava UP-TO-DATE
:conductor-core:processResources UP-TO-DATE
:conductor-core:classes UP-TO-DATE
:conductor-core:writeManifestProperties UP-TO-DATE
:conductor-core:jar UP-TO-DATE
:conductor-contribs:compileJava UP-TO-DATE
:conductor-contribs:processResources UP-TO-DATE
:conductor-contribs:classes UP-TO-DATE
:conductor-contribs:writeManifestProperties UP-TO-DATE
:conductor-contribs:jar UP-TO-DATE
:conductor-es5-persistence:compileJava UP-TO-DATE
:conductor-es5-persistence:processResources UP-TO-DATE
:conductor-es5-persistence:classes UP-TO-DATE
:conductor-es5-persistence:writeManifestProperties UP-TO-DATE
:conductor-es5-persistence:jar UP-TO-DATE
:conductor-jersey:compileJava UP-TO-DATE
:conductor-jersey:processResources UP-TO-DATE
:conductor-jersey:classes UP-TO-DATE
:conductor-jersey:writeManifestProperties UP-TO-DATE
:conductor-jersey:jar UP-TO-DATE
:conductor-mysql-persistence:compileJava UP-TO-DATE
:conductor-mysql-persistence:processResources UP-TO-DATE
:conductor-mysql-persistence:classes UP-TO-DATE
:conductor-mysql-persistence:writeManifestProperties UP-TO-DATE
:conductor-mysql-persistence:jar UP-TO-DATE
:conductor-redis-persistence:compileJava UP-TO-DATE
:conductor-redis-persistence:processResources UP-TO-DATE
:conductor-redis-persistence:classes UP-TO-DATE
:conductor-redis-persistence:writeManifestProperties UP-TO-DATE
:conductor-redis-persistence:jar UP-TO-DATE
:conductor-server:compileJava UP-TO-DATE
:conductor-server:processResources UP-TO-DATE
:conductor-server:classes UP-TO-DATE
:conductor-server:compileTestJava UP-TO-DATE
:conductor-server:processTestResources UP-TO-DATE
:conductor-server:testClasses UP-TO-DATE
:conductor-server:server
0    [main] INFO  com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch  - Deleting contents of data dir /tmp/elasticsearch_test_1507879792206data122547791495208706
7    [main] INFO  com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch  - Starting ElasticSearch for cluster elasticsearch_test
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtilBuilding 97% > :conductor-server:server
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:72)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:227)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
        at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:54)
        at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:105)
        at org.elasticsearch.node.Node.<init>(Node.java:253)
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch$PluginConfigurableNode.<init>(EmbeddedElasticSearch.java:58)
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:77)
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:63)
        at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:169)
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:115)
        at com.netflix.conductor.server.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
:conductor-server:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-server:server'.
> Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.08 secs

**Comment by cquon** [comment]
Update:

When changing 

	compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8.2'
	compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8.2'

versions to 2.9.1

in https://github.com/Netflix/conductor/blob/master/es5-persistence/build.gradle

it resolved the issue.

Should I open a PR?

**Comment by v1r3n** [comment]
@cquon please do send the PR if the issue is solved by changing the log4j.
