### ISSUE TITLE
ElasticSearch Exception in Conductor Server logs

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#356]
When looking up a workflow in the UI i.e. when I click a particular workflow instance id in the UI, I see the following exception in the Conductor Server logs:
```
999411 [qtp277630005-73] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - all shards failed
Failed to execute phase [query], all shards failed; shardFailures {[7EwHDM61SGCfY0oaeXMlQA][task_log_20171004][0]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171005][0]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171004][1]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171005][1]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171004][2]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171005][2]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171004][3]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171005][3]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171004][4]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }{[7EwHDM61SGCfY0oaeXMlQA][task_log_20171005][4]: RemoteTransportException[[conductor-es-data-steelix-1][10.6.66.50:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"query_string":{"query":"taskId:\"6c8036db-6ee0-47e1-9888-f9fe7c1e2478\""}}}}]}},"sort":[{"createdTime":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [createdTime] in order to sort on]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [createdTime] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more
```
Am I missing something in my configuration?

**Comment by v1r3n** [comment]
@clari-akhilesh what version of elasticsearch are you using?  seems like it is missing mapping for `createdTime` field - which indicates there was an issue when trying to register the types.

Can you check the index and `wfe` document type to see what mappings are present?

**Comment by clari-akhilesh** [comment]
@v1r3n , we're running the 2.4.6 version of elasticsearch. 
Here's the index I've in ES:
```
{
  "conductor" : {
    "aliases" : { },
    "mappings" : {
      "task" : {
        "dynamic_templates" : [ {
          "string_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        }, {
          "long_fields" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "double_fields" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        } ],
        "properties" : {
          "endTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "executionTime" : {
            "type" : "long"
          },
          "input" : {
            "type" : "string"
          },
          "log" : {
            "type" : "string"
          },
          "logs" : {
            "type" : "string"
          },
          "output" : {
            "type" : "string"
          },
          "queueWaitTime" : {
            "type" : "long"
          },
          "reasonForIncompletion" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "scheduledTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "startTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "status" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "taskDefName" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "taskId" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "taskType" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "updateTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "workflowId" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      },
      "_default_" : {
        "dynamic_templates" : [ {
          "string_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        }, {
          "long_fields" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "double_fields" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        } ]
      },
      "workflow" : {
        "dynamic_templates" : [ {
          "string_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        }, {
          "long_fields" : {
            "mapping" : {
              "type" : "long",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "long"
          }
        }, {
          "double_fields" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*",
            "match_mapping_type" : "double"
          }
        } ],
        "properties" : {
          "correlationId" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "endTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "executionTime" : {
            "type" : "long"
          },
          "input" : {
            "type" : "string"
          },
          "output" : {
            "type" : "string"
          },
          "rawJSON" : {
            "type" : "string",
            "index" : "no",
            "include_in_all" : false
          },
          "reasonForIncompletion" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "startTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "status" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "updateTime" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "version" : {
            "type" : "long"
          },
          "workflowId" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "workflowType" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date_string" : "2017-10-27T02:47:21.807Z",
        "refresh_interval" : "1s",
        "number_of_shards" : "5",
        "creation_date" : "1509072441807",
        "number_of_replicas" : "0",
        "uuid" : "uOoq56oRRAq1iBbIai3-Sw",
        "version" : {
          "created_string" : "2.4.6",
          "created" : "2040699"
        }
      }
    },
    "warmers" : { }
  }
}
```

**Comment by clari-akhilesh** [comment]
Looks like this issue has been addressed. Will reopen if necessary.
