### ISSUE TITLE
With ES5,exception while search all workflows

### ISSUE THREAD

**Issue by lydialmr120** [Netflix/conductor#377]
```
2017-11-28 21:48:20,545 120978 [ForkJoinPool.commonPool-worker-7] ERROR com.netflix.conductor.service.ExecutionService  - No such workflow found by id: 3465baf0-9c40-49fb-b53a-f4affccefaab
com.netflix.conductor.core.execution.ApplicationException: No such workflow found by id: 3465baf0-9c40-49fb-b53a-f4affccefaab
	at com.netflix.conductor.dao.dynomite.RedisExecutionDAO.getWorkflow(RedisExecutionDAO.java:363)
	at com.netflix.conductor.service.ExecutionService.lambda$search$2(ExecutionService.java:321)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Deleted workflows throw exception while searching all worklows.

**Comment by grfeng** [comment]
Hi，This is a defect, And if you delete the workflow, you need to filter it in ES without Archived

**Comment by zekeoptimo** [comment]
Is there any update on this defect? I'm experiencing this as well.
