### ISSUE TITLE
error start with db=dynomite

### ISSUE THREAD

**Issue by suxiaoyuv** [Netflix/conductor#38]
Many thanks!

1. I start a dynomite use docker 
```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                              NAMES
995c1689555a        dynomitedb/dynomite   "/entrypoint.sh dynom"   45 hours ago        Up 45 hours         0.0.0.0:8101-8102->8101-8102/tcp   dynomite

```

2. With the server.properties i copy from the document like this
```
db=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=localhost:8102:rack

# Dynomite cluster name
workflow.dynomite.cluster.name=dyno_cluster_name

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
queues.dynomite.nonQuorum.port=22122

# Transport address to elasticsearch
workflow.elasticsearch.url=localhost:9300

# Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

# Additional modules (optional)
conductor.additional.modules=class_extending_com.google.inject.AbstractModule
```

3. change the build.gradle add args
```
build.dependsOn('shadowJar')
task server(type: JavaExec) {
  systemProperty 'workflow.elasticsearch.url', 'localhost:9300'
  systemProperty 'loadSample', 'true'
  args '/Users/jerry/git/conductor/server/src/main/resources/server.properties', '/Users/jerry/git/conductor/server/src/main/resources/log4j.properties'
  main = 'com.netflix.conductor.server.Main'
  classpath = sourceSets.test.runtimeClasspath  
}
```

4. start server use ` ../gradlew server `

then throw exception
```
Inferred project: conductor, version: 1.6.0-SNAPSHOT
Publication nebula not found in project :.
[buildinfo] Not using buildInfo properties file for this build.
Publication named 'shadow' does not exist for project ':conductor-ui' in task ':conductor-ui:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-contribs' in task ':conductor-contribs:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-jersey' in task ':conductor-jersey:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':' in task ':artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-redis-persistence' in task ':conductor-redis-persistence:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-core' in task ':conductor-core:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-test-harness' in task ':conductor-test-harness:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-client' in task ':conductor-client:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-common' in task ':conductor-common:artifactoryPublish'.
:conductor-common:compileJava UP-TO-DATE
:conductor-common:processResources UP-TO-DATE
:conductor-common:classes UP-TO-DATE
:conductor-common:writeManifestProperties UP-TO-DATE
:conductor-common:jar UP-TO-DATE
:conductor-core:compileJava UP-TO-DATE
:conductor-core:processResources UP-TO-DATE
:conductor-core:classes UP-TO-DATE
:conductor-core:writeManifestProperties UP-TO-DATE
:conductor-core:jar UP-TO-DATE
:conductor-contribs:compileJava UP-TO-DATE
:conductor-contribs:processResources UP-TO-DATE
:conductor-contribs:classes UP-TO-DATE
:conductor-contribs:writeManifestProperties UP-TO-DATE
:conductor-contribs:jar UP-TO-DATE
:conductor-jersey:compileJava UP-TO-DATE
:conductor-jersey:processResources UP-TO-DATE
:conductor-jersey:classes UP-TO-DATE
:conductor-jersey:writeManifestProperties UP-TO-DATE
:conductor-jersey:jar UP-TO-DATE
:conductor-redis-persistence:compileJava UP-TO-DATE
:conductor-redis-persistence:processResources UP-TO-DATE
:conductor-redis-persistence:classes UP-TO-DATE
:conductor-redis-persistence:writeManifestProperties UP-TO-DATE
:conductor-redis-persistence:jar UP-TO-DATE
:conductor-server:compileJava UP-TO-DATE
:conductor-server:processResources
:conductor-server:classes
:conductor-server:compileTestJava UP-TO-DATE
:conductor-server:processTestResources UP-TO-DATE
:conductor-server:testClasses UP-TO-DATE
:conductor-server:server
Using /Users/jerry/git/conductor/server/src/main/resources/server.properties
Using log4j config /Users/jerry/git/conductor/server/src/main/resources/log4j.properties
0    [main] WARN  com.netflix.config.sources.URLConfigurationSource  - No URLs will be polled as dynamic configuration sources.
384  [main] INFO  com.netflix.config.sources.URLConfigurationSource  - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
499  [main] INFO  com.netflix.config.DynamicPropertyFactory  - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@4cdbe50f
633  [main] INFO  com.netflix.dyno.contrib.ArchaiusConnectionPoolConfiguration  - Dyno configuration: CompressionStrategy = NONE
737  [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Dyno Client runtime properties: ArchaiusConnectionPoolConfiguration{name=, maxConnsPerHost=DynamicProperty: {name=dyno..connection.maxConnsPerHost, current value=3}, maxTimeoutWhenExhausted=DynamicProperty: {name=dyno..connection.maxTimeoutWhenExhausted, current value=800}, maxFailoverCount=DynamicProperty: {name=dyno..connection.maxFailoverCount, current value=3}, connectTimeout=DynamicProperty: {name=dyno..connection.connectTimeout, current value=3000}, socketTimeout=DynamicProperty: {name=dyno..connection.socketTimeout, current value=12000}, localZoneAffinity=DynamicProperty: {name=dyno..connection.localZoneAffinity, current value=true}, resetTimingsFrequency=DynamicProperty: {name=dyno..connection.metrics.resetFrequencySeconds, current value=300}, configPublisherConfig=DynamicProperty: {name=dyno..config.publisher.address, current value=null}, compressionThreshold=DynamicProperty: {name=dyno..config.compressionThreshold, current value=5120}, loadBalanceStrategy=TokenAware, compressionStrategy=NONE, errorRateConfig=null, retryPolicyFactory=com.netflix.dyno.connectionpool.impl.RunOnce$RetryFactory@b684286, failOnStartupIfNoHosts=DynamicProperty: {name=dyno..config.startup.failIfNoHosts, current value=true}, isDualWriteEnabled=DynamicProperty: {name=dyno..dualwrite.enabled, current value=false}, dualWriteClusterName=DynamicProperty: {name=dyno..dualwrite.cluster, current value=null}, dualWritePercentage=DynamicProperty: {name=dyno..dualwrite.percentage, current value=0}}
1631 [main] WARN  com.netflix.dyno.contrib.DynoCPMonitor  - Failed to register metrics with monitor registry
java.lang.IllegalArgumentException: value cannot be empty
        at com.netflix.servo.util.Preconditions.checkArgument(Preconditions.java:48)
        at com.netflix.servo.tag.BasicTag.checkNotEmpty(BasicTag.java:39)
        at com.netflix.servo.tag.BasicTag.<init>(BasicTag.java:33)
        at com.netflix.servo.tag.Tags.newTag(Tags.java:53)
        at com.netflix.servo.tag.SortedTagList$Builder.withTag(SortedTagList.java:88)
        at com.netflix.servo.monitor.Monitors.addMonitorFields(Monitors.java:260)
        at com.netflix.servo.monitor.Monitors.addMonitors(Monitors.java:242)
        at com.netflix.servo.monitor.Monitors.newObjectMonitor(Monitors.java:144)
        at com.netflix.dyno.contrib.DynoCPMonitor.<init>(DynoCPMonitor.java:34)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:3356)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3292)
        at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:136)
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:108)
        at com.netflix.conductor.server.Main.main(Main.java:52)
1634 [main] WARN  com.netflix.dyno.jedis.DynoJedisClient  - TOKEN AWARE selected and no token supplier found, using default HttpEndpointBasedTokenMapSupplier()
1687 [main] WARN  com.netflix.dyno.jedis.DynoJedisClient  - DynoJedisClient for app=[] is configured for local rack affinity but cannot determine the local rack! DISABLING rack affinity for this instance. To make the client aware of the local rack either use ConnectionPoolConfigurationImpl.setLocalRack() when constructing the client instance or ensure EC2_AVAILABILTY_ZONE is set as an environment variable, e.g. run with -DEC2_AVAILABILITY_ZONE=us-east-1c
1712 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app 
1719 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=localhost, ipAddress=null, port=8102, rack: rack, datacenter: rac, status: Up]
1720 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=localhost, ipAddress=null, port=8102, rack: rack, datacenter: rac, status: Up], with conns:3
1900 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=localhost, ipAddress=null, port=8102, rack: rack, datacenter: rac, status: Up]
3265 [main] WARN  com.netflix.dyno.connectionpool.impl.lb.AbstractTokenMapSupplier  - Could not get json response for token topology [java.net.ConnectException: Connection refused]
3298 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - registered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
3337 [main] INFO  com.netflix.conductor.server.ConductorServer  - Starting conductor server using dynomite cluster dyno_cluster_name




                     _            _             
  ___ ___  _ __   __| |_   _  ___| |_ ___  _ __ 
 / __/ _ \| '_ \ / _` | | | |/ __| __/ _ \| '__|
| (_| (_) | | | | (_| | |_| | (__| || (_) | |   
 \___\___/|_| |_|\__,_|\__,_|\___|\__\___/|_|   




3784 [main] INFO  com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO  - DynoQueueDAO initialized with prefix conductor_queues.test!
6437 [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
6453 [main] WARN  com.netflix.conductor.server.ConductorConfig  - class_extending_com.google.inject.AbstractModule
java.lang.ClassNotFoundException: class_extending_com.google.inject.AbstractModule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.netflix.conductor.server.ConductorConfig.getAdditionalModules(ConductorConfig.java:122)
        at com.netflix.conductor.server.ServerModule.configure(ServerModule.java:99)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.netflix.conductor.server.ConductorServer.start(ConductorServer.java:167)
        at com.netflix.conductor.server.Main.main(Main.java:62)
7353 [main] INFO  org.eclipse.jetty.util.log  - Logging initialized @10146ms
7617 [main] INFO  org.eclipse.jetty.server.Server  - jetty-9.3.9.v20160517
一月 18, 2017 7:06:00 下午 com.sun.jersey.api.core.PackagesResourceConfig init
信息: Scanning for root resource and provider classes in the packages:
  com.netflix.conductor.server.resources
  io.swagger.jaxrs.json
  io.swagger.jaxrs.listing
一月 18, 2017 7:06:01 下午 com.sun.jersey.api.core.ScanningResourceConfig logClasses
信息: Root resource classes found:
  class com.netflix.conductor.server.resources.MetadataResource
  class io.swagger.jaxrs.listing.ApiListingResource
  class com.netflix.conductor.server.resources.TaskResource
  class com.netflix.conductor.server.resources.AdminResource
  class com.netflix.conductor.server.resources.WorkflowResource
  class io.swagger.jaxrs.listing.AcceptHeaderApiListingResource
一月 18, 2017 7:06:01 下午 com.sun.jersey.api.core.ScanningResourceConfig logClasses
信息: Provider classes found:
  class io.swagger.jaxrs.listing.SwaggerSerializers
  class com.netflix.conductor.server.resources.ApplicationExceptionMapper
  class com.netflix.conductor.server.resources.GenericExceptionMapper
  class com.netflix.conductor.server.resources.WebAppExceptionMapper
一月 18, 2017 7:06:01 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
信息: Registering com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider as a provider class
一月 18, 2017 7:06:01 下午 com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
信息: Initiating Jersey application, version 'Jersey: 1.19.1 03/11/2016 02:42 PM'
一月 18, 2017 7:06:02 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.netflix.conductor.server.resources.ApplicationExceptionMapper to GuiceInstantiatedComponentProvider
一月 18, 2017 7:06:02 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.netflix.conductor.server.resources.GenericExceptionMapper to GuiceInstantiatedComponentProvider
一月 18, 2017 7:06:02 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
一月 18, 2017 7:06:03 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.netflix.conductor.server.resources.AdminResource to GuiceInstantiatedComponentProvider
一月 18, 2017 7:06:03 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.netflix.conductor.server.resources.MetadataResource to GuiceInstantiatedComponentProvider
一月 18, 2017 7:06:03 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.netflix.conductor.server.resources.TaskResource to GuiceInstantiatedComponentProvider
一月 18, 2017 7:06:03 下午 com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
信息: Binding com.netflix.conductor.server.resources.WorkflowResource to GuiceInstantiatedComponentProvider
10179 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.s.ServletContextHandler@1e53135d{/,file:///Users/jerry/git/conductor/server/build/resources/main/swagger-ui/,AVAILABLE}
10297 [main] INFO  org.eclipse.jetty.server.AbstractConnector  - Started ServerConnector@24fb2775{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
10299 [main] INFO  org.eclipse.jetty.server.Server  - Started @13092ms
Started server on http://localhost:8080/
Creating kitchensink workflow
11246 [qtp2018260103-16] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
com.netflix.dyno.connectionpool.exception.PoolOfflineException: PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnection(HostSelectionWithFallback.java:161)
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnectionUsingRetryPolicy(HostSelectionWithFallback.java:120)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:292)
        at com.netflix.dyno.jedis.DynoJedisClient.d_hset(DynoJedisClient.java:723)
        at com.netflix.dyno.jedis.DynoJedisClient.hset(DynoJedisClient.java:718)
        at com.netflix.conductor.dao.dynomite.DynoProxy.hset(DynoProxy.java:115)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.insertOrUpdateTaskDef(RedisMetadataDAO.java:72)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.createTaskDef(RedisMetadataDAO.java:57)
        at com.netflix.conductor.service.MetadataService.registerTaskDef(MetadataService.java:54)
        at com.netflix.conductor.server.resources.MetadataResource.registerTaskDef(MetadataResource.java:93)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:167)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
11435 [main] ERROR com.netflix.conductor.server.ConductorServer  - POST http://localhost:8080/api/metadata/taskdefs returned a response status of 500 Internal Server Error
com.sun.jersey.api.client.UniformInterfaceException: POST http://localhost:8080/api/metadata/taskdefs returned a response status of 500 Internal Server Error
        at com.sun.jersey.api.client.WebResource.voidHandle(WebResource.java:709)
        at com.sun.jersey.api.client.WebResource.access$400(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:555)
        at com.netflix.conductor.server.ConductorServer.createKitchenSink(ConductorServer.java:220)
        at com.netflix.conductor.server.ConductorServer.start(ConductorServer.java:190)
        at com.netflix.conductor.server.Main.main(Main.java:62)
> Could not read standard output of: command '/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java'.
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:291)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by suxiaoyuv** [comment]
it must be delete default property set in `build.gradle`
```
systemProperty 'workflow.elasticsearch.url', 'localhost:9300'
 systemProperty 'loadSample', 'true'
```

```
build.dependsOn('shadowJar')
task server(type: JavaExec) {
  systemProperty 'workflow.elasticsearch.url', 'localhost:9300'
  systemProperty 'loadSample', 'true'
  args '/Users/jerry/git/conductor/server/src/main/resources/server.properties', '/Users/jerry/git/conductor/server/src/main/resources/log4j.properties'
  main = 'com.netflix.conductor.server.Main'
  classpath = sourceSets.test.runtimeClasspath  
}
```

**Comment by suxiaoyuv** [comment]
but it still has the error with call api
```
24741 [qtp768776793-16] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
com.netflix.dyno.connectionpool.exception.PoolOfflineException: PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnection(HostSelectionWithFallback.java:161)
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnectionUsingRetryPolicy(HostSelectionWithFallback.java:120)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:292)
        at com.netflix.dyno.jedis.DynoJedisClient.d_hscan(DynoJedisClient.java:588)
        at com.netflix.dyno.jedis.DynoJedisClient.hscan(DynoJedisClient.java:583)
        at com.netflix.conductor.dao.dynomite.DynoProxy.hgetAll(DynoProxy.java:128)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getAllTaskDefs(RedisMetadataDAO.java:94)
        at com.netflix.conductor.service.MetadataService.getTaskDefs(MetadataService.java:73)
        at com.netflix.conductor.server.resources.MetadataResource.getTaskDefs(MetadataResource.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.netflix.conductor.server.JerseyModule$1.doFilter(JerseyModule.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by v1r3n** [comment]
@suxiaoyuv Try with the ```v1r3n/dynomite``` docker image and config file from [here](https://github.com/Netflix/conductor/blob/dev/docker/tmp/config.properties).  

We have also recently created a docker compose for Conductor, which relies on the tested containers.  You can find the instructions here:

https://github.com/Netflix/conductor/tree/dev/docker

**Comment by suxiaoyuv** [comment]
ok  thanks! I will try it.

**Comment by suxiaoyuv** [comment]
@v1r3n I have some questions for develop, which one IDE do you use for java develop? thanks~ 
I use IntelliJ IDEA the Java IDE - JetBrains.

**Comment by v1r3n** [comment]
We have a team with individuals using both IntelliJ IDEA and Eclipse.  A lot of UI development is also done using Atom.

**Comment by suxiaoyuv** [comment]
Many thanks!
