### ISSUE TITLE
Unable to deploy Conductor Server War in Tomcat

### ISSUE THREAD

**Issue by spsmurthy** [Netflix/conductor#431]
HI Team,

We are unable to deploy 1.7.0 war in tomcat. Also we tried with latest dev code. We could see below error:
java.lang.IllegalArgumentException: The servletContext org.apache.catalina.core.ApplicationContextFacade@46858b5f org.apache.catalina.core.ApplicationContextFacade is not org.eclipse.jetty.server.handler.ContextHandler$Context
	at org.eclipse.jetty.servlet.DefaultServlet.initContextHandler(DefaultServlet.java:342)
	at org.eclipse.jetty.servlet.DefaultServlet.init(DefaultServlet.java:185)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4572)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)  

Could you please suggest as it seems changes required to support default servlet for tomcat

**Comment by v1r3n** [comment]
@spsmurthy can you provide more detailed stack trace if there is any?
Also provide the following:

1. Java version
2. Tomcat version

**Comment by spsmurthy** [comment]
@v1r3n Thanks for the quick response.
We could see only the above stacktrace in tomcat container log. Tomcat started but war hasn't got deployed with the issue mentioned.
1. Java  1.8
2. Tomcat version  is 8.5.11.

**Comment by piokania** [comment]
@v1r3n I found similar issue with conductor-server-1.12.3.war (downloaded from http://central.maven.org/maven2/com/netflix/conductor/conductor-server/1.12.3/ )

Tomcat 8.0.36
Java 1.8.0_62

02-Oct-2018 11:50:05.438 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter guiceFilter
 java.lang.IllegalArgumentException: The servletContext org.apache.catalina.core.ApplicationContextFacade@2a950a9d org.apache.catalina.core.ApplicationContextFacade is not org.eclipse.jetty.server.handler.ContextHandler$Context
	at org.eclipse.jetty.servlet.DefaultServlet.initContextHandler(DefaultServlet.java:342)
	at org.eclipse.jetty.servlet.DefaultServlet.init(DefaultServlet.java:185)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5329)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Please, advise.

Thank you for your time and help!
[catalina.2018-10-02.log](https://github.com/Netflix/conductor/files/2437544/catalina.2018-10-02.log)
[localhost.2018-10-02.log](https://github.com/Netflix/conductor/files/2437545/localhost.2018-10-02.log)

**Comment by kishorebanala** [comment]
This might have been outdated.

Closing this issue, as there is no activity for a while. Please feel free to open another issue if you still have questions.
