### ISSUE TITLE
es5 error

### ISSUE THREAD

**Issue by kervin521** [Netflix/conductor#458]
D:\soft\conductor-1.8.2-rc10>gradle server

> Configure project :
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.

Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

> Task :conductor-redis-persistence:compileJava
D:\soft\conductor-1.8.2-rc10\redis-persistence\src\main\java\com\netflix\conductor\dao\RedisESWorkflowModule.java:31: 错误: 程序包com.netflix.conducto
r.dao.es5.index不存在
import com.netflix.conductor.dao.es5.index.ElasticSearchDAO;
                                          ^
D:\soft\conductor-1.8.2-rc10\redis-persistence\src\main\java\com\netflix\conductor\dao\RedisESWorkflowModule.java:32: 错误: 程序包com.netflix.conducto
r.dao.es5.index不存在
import com.netflix.conductor.dao.es5.index.ElasticsearchModule;
                                          ^
D:\soft\conductor-1.8.2-rc10\redis-persistence\src\main\java\com\netflix\conductor\dao\RedisESWorkflowModule.java:43: 错误: 找不到符号
                install(new ElasticsearchModule());
                            ^
  符号:   类 ElasticsearchModule
  位置: 类 RedisESWorkflowModule
D:\soft\conductor-1.8.2-rc10\redis-persistence\src\main\java\com\netflix\conductor\dao\RedisESWorkflowModule.java:47: 错误: 找不到符号
                bind(IndexDAO.class).to(ElasticSearchDAO.class);
                                        ^
  符号:   类 ElasticSearchDAO
  位置: 类 RedisESWorkflowModule
4 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-redis-persistence:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 46s
21 actionable tasks: 1 executed, 20 up-to-date

D:\soft\conductor-1.8.2-rc10>gradle server

> Configure project :
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.
Git repository not found at D:\soft\conductor-1.8.2-rc10 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a
different directory.

Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

> Task :conductor-server:server
0    [main] INFO  com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch  - Deleting contents of data dir C:\Users\YICE3A~1.ZHA\AppData\Local\Temp\ela
sticsearch_1521457446845data4804345591466881392
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/plugins/NetworkPlugin
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
79   [main] INFO  com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch  - Starting ElasticSearch for cluster elasticsearch
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:77)
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:63)
        at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:151)
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:115)
        at com.netflix.conductor.server.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-server:server'.
> Process 'command 'C:\Java\jdk1.8\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 3s
27 actionable tasks: 4 executed, 23 up-to-date

**Comment by kervin521** [comment]
Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

> Task :conductor-server:server
0    [main] INFO  com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch  - Deleting contents of data dir C:\Users\YICE3A~1.ZHA\AppData\Local\Temp\ela
sticsearch_1521457446845data4804345591466881392
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/plugins/NetworkPlugin
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
79   [main] INFO  com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch  - Starting ElasticSearch for cluster elasticsearch
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:77)
        at com.netflix.conductor.dao.es5.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:63)
        at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:151)
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:115)
        at com.netflix.conductor.server.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-server:server'.
> Process 'command 'C:\Java\jdk1.8\bin\java.exe'' finished with non-zero exit value 1

**Comment by saidatta** [comment]
According to this https://github.com/Netflix/conductor/issues/21, Conductor has been tested on MacOS / Windows. 

Have you tried in any of the above two environments?

**Comment by pctreddy** [comment]
@kervin521  I was able to check out git tag RC-10:

```script
~/r/c/server> git status
HEAD detached at v1.8.2-rc10
```
and run the `server` successfully:

```script
~/r/c/server> gw server
Using gradle at '/Users/preddy/repos/conductor/gradlew' to run buildfile '/Users/preddy/repos/conductor/server/build.gradle':

> Configure project :
Inferred project: conductor, version: 1.8.2-SNAPSHOT

> Configure project :conductor-server
A constructor for `org.gradle.api.internal.java.JavaLibrary` is used by Shadow plugin v1.2.x, and has been preserved for compatibility. This has been deprecated and is scheduled to be removed in Gradle 5.0. If you're using the Shadow plugin, try upgrading to v2.x.

Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

> Task :conductor-server:server
0    [main] INFO  com.netflix.conductor.dao.es.EmbeddedElasticSearch  - Deleting contents of data dir /var/folders/8k/pwvhv4jn6m9dht36f9k3p8580000gn/T/elasticsearch_test_1524242819368data1873537865223523520
6    [main] INFO  com.netflix.conductor.dao.es.EmbeddedElasticSearch  - Starting ElasticSearch for cluster elasticsearch_test
142  [main] INFO  org.elasticsearch.node  - [Monet St. Croix] version[2.4.6], pid[36603], build[5376dca/2017-07-18T12:17:44Z]
142  [main] INFO  org.elasticsearch.node  - [Monet St. Croix] initializing ...
145  [main] INFO  org.elasticsearch.plugins  - [Monet St. Croix] modules [], plugins [], sites []
179  [main] INFO  org.elasticsearch.env  - [Monet St. Croix] using [1] data paths, mounts [[/ (/dev/disk1s1)]], net usable_space [427.6gb], net total_space [465.6gb], spins? [unknown], types [apfs]
179  [main] INFO  org.elasticsearch.env  - [Monet St. Croix] heap size [3.5gb], compressed ordinary object pointers [true]
181  [main] WARN  org.elasticsearch.env  - [Monet St. Croix] max file descriptors [10240] for elasticsearch process likely too low, consider increasing to at least [65536]
1004 [main] WARN  org.elasticsearch.bootstrap  - JNA not found. native methods will be disabled.
java.lang.ClassNotFoundException: com.sun.jna.Native
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45)
        at org.elasticsearch.bootstrap.BootstrapInfo.isMemoryLocked(BootstrapInfo.java:44)
        at org.elasticsearch.monitor.process.ProcessProbe.processInfo(ProcessProbe.java:130)
        at org.elasticsearch.monitor.process.ProcessService.<init>(ProcessService.java:44)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:150)
        at com.netflix.conductor.dao.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:64)
        at com.netflix.conductor.dao.es.EmbeddedElasticSearch.start(EmbeddedElasticSearch.java:50)
        at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:150)
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:114)
        at com.netflix.conductor.server.Main.main(Main.java:44)
1385 [main] INFO  org.elasticsearch.node  - [Monet St. Croix] initialized
1387 [main] INFO  org.elasticsearch.node  - [Monet St. Croix] starting ...
1460 [main] INFO  org.elasticsearch.transport  - [Monet St. Croix] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
1465 [main] INFO  org.elasticsearch.discovery  - [Monet St. Croix] elasticsearch_test/Y0qrloMKQ7SNvrod0HLefQ
4510 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service  - [Monet St. Croix] new_master {Monet St. Croix}{Y0qrloMKQ7SNvrod0HLefQ}{127.0.0.1}{127.0.0.1:9300}{local=false}, reason: zen-disco-join(elected_as_master, [0] joins received)
4523 [main] INFO  org.elasticsearch.http  - [Monet St. Croix] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
4523 [main] INFO  org.elasticsearch.node  - [Monet St. Croix] started
4523 [main] INFO  com.netflix.conductor.dao.es.EmbeddedElasticSearch  - ElasticSearch cluster elasticsearch_test started in local mode on port 9200
4523 [main] INFO  com.netflix.conductor.server.ConductorServer  - Starting conductor server using in memory data store




                     _            _
  ___ ___  _ __   __| |_   _  ___| |_ ___  _ __
 / __/ _ \| '_ \ / _` | | | |/ __| __/ _ \| '__|
| (_| (_) | | | | (_| | |_| | (__| || (_) | |
 \___\___/|_| |_|\__,_|\__,_|\___|\__\___/|_|




4558 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.gateway  - [Monet St. Croix] recovered [0] indices into cluster_state
4578 [main] INFO  com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO  - DynoQueueDAO initialized with prefix null.test!
4868 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task HTTP
4966 [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
4967 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task JSON_JQ_TRANSFORM
5186 [main] INFO  org.elasticsearch.plugins  - [Chief Examiner] modules [], plugins [], sites []
5227 [main] INFO  com.netflix.conductor.dao.index.ElasticSearchDAO  - Creating the index template 'wfe_template'
5458 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata  - [Monet St. Croix] [conductor] creating index, cause [api], templates [wfe_template], shards [5]/[1], mappings [_default_, task]
5579 [main] INFO  com.netflix.conductor.dao.index.ElasticSearchDAO  - Adding the workflow type mappings
5590 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata  - [Monet St. Croix] [conductor] create_mapping [workflow]
5604 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata  - [Monet St. Croix] [task_log_20180403] creating index, cause [api], templates [wfe_template], shards [5]/[1], mappings [_default_, task]
5615 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - System Task Worker Initialized with 10 threads and a callback time of 30 second and queue size 100 with pollCount 10
5615 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task SUB_WORKFLOW
5615 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task WAIT
5615 [Thread-2] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Started listening HTTP
5616 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task EVENT
5631 [main] INFO  org.eclipse.jetty.util.log  - Logging initialized @6005ms
5719 [main] INFO  org.eclipse.jetty.server.Server  - jetty-9.3.9.v20160517
5722 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.routing.allocation  - [Monet St. Croix] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[conductor][4]] ...]).
Apr 20, 2018 9:47:05 AM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  com.netflix.conductor.server.resources
  io.swagger.jaxrs.json
  io.swagger.jaxrs.listing
Apr 20, 2018 9:47:05 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class com.netflix.conductor.server.resources.AdminResource
  class io.swagger.jaxrs.listing.AcceptHeaderApiListingResource
  class com.netflix.conductor.server.resources.TaskResource
  class com.netflix.conductor.server.resources.EventResource
  class com.netflix.conductor.server.resources.WorkflowResource
  class io.swagger.jaxrs.listing.ApiListingResource
  class com.netflix.conductor.server.resources.MetadataResource
Apr 20, 2018 9:47:05 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class com.netflix.conductor.server.resources.WebAppExceptionMapper
  class com.netflix.conductor.server.resources.GenericExceptionMapper
  class com.netflix.conductor.server.resources.ApplicationExceptionMapper
  class io.swagger.jaxrs.listing.SwaggerSerializers
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider as a provider class
Apr 20, 2018 9:47:05 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19.1 03/11/2016 02:42 PM'
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.ApplicationExceptionMapper to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.GenericExceptionMapper to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.TaskResource to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.MetadataResource to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.EventResource to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.WorkflowResource to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding com.netflix.conductor.server.resources.AdminResource to GuiceInstantiatedComponentProvider
Apr 20, 2018 9:47:05 AM com.sun.jersey.spi.inject.Errors processErrorMessages
WARNING: The following warnings have been detected with resource and/or provider classes:
  WARNING: Return type java.util.Map<java.lang.String, ?> of method public java.util.Map<java.lang.String, ?> com.netflix.conductor.server.resources.EventResource.getEventQueues(boolean) is not resolvable to a concrete type
6166 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.s.ServletContextHandler@4ae280da{/,file:///Users/preddy/repos/conductor/server/build/resources/main/swagger-ui/,AVAILABLE}
6170 [main] INFO  org.eclipse.jetty.server.AbstractConnector  - Started ServerConnector@5e67a490{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
6171 [main] INFO  org.eclipse.jetty.server.Server  - Started @6544ms
Started server on http://localhost:8080/
Creating kitchensink workflow
6593 [qtp901614537-117] INFO  com.netflix.conductor.core.execution.WorkflowExecutor  - A new instance of workflow kitchensink created with workflow id 5a47f4ee-469c-4847-a01d-3f4c5b31bf71
6667 [qtp901614537-117] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task DECISION
6667 [qtp901614537-117] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task FORK
6668 [qtp901614537-117] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding system task JOIN
6688 [elasticsearch[Monet St. Croix][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata  - [Monet St. Croix] [conductor] update_mapping [task]
6710 [pool-7-thread-1] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve HTTP
6720 [qtp901614537-117] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve task_1
6750 [qtp901614537-117] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve _deciderQueue
6754 [main] INFO  com.netflix.conductor.server.ConductorServer  - Kitchen sink workflows are created!
<============-> 97% EXECUTING [30s]
> :conductor-server:server
```

**Comment by kishorebanala** [comment]
Closing this issue, as there is no activity for a while. Please feel free to open another issue if that doesn't resolve your concern.
