### ISSUE TITLE
End2EndTests. testAll fails

### ISSUE THREAD

**Issue by marczahn** [Netflix/conductor#486]
When I run 
~~~
gradlew build
~~~
as suggested in docker/README.md, I get this error:
~~~
java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: GET http://localhost:8080/api/workflow/search?query=workflowType%3D'test' returned a response status of 500 Internal Server Error
	at com.netflix.conductor.client.http.ClientBase.handleException(ClientBase.java:189)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:179)
	at com.netflix.conductor.client.http.WorkflowClient.search(WorkflowClient.java:160)
	at com.netflix.conductor.tests.integration.End2EndTests.testAll(End2EndTests.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET http://localhost:8080/api/workflow/search?query=workflowType%3D'test' returned a response status of 500 Internal Server Error
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:700)
	at com.sun.jersey.api.client.WebResource.access$300(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:514)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:176)
	... 46 more
~~~
Are there any preconditions necessary?

**Comment by marczahn** [comment]
https://gist.github.com/marczahn/005334771f51f5923380d46f83a0d7ff

**Comment by pctreddy** [comment]
@marczahn Which branch are on `dev` or `master` ? And from which module are you executing your command from ?

Looks like you have an error in the output you posted:

```script 
com.netflix.conductor.tests.integration.End2EndTests STANDARD_OUT
    4773 [elasticsearch[Damballah][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service  - [Damballah] new_master {Damballah}{Gvuh263KTguFK0SCIgVOcQ}{127.0.0.1}{127.0.0.1:9301}{local=false}, reason: zen-disco-join(elected_as_master, [0] joins received)
    4785 [Test worker] ERROR com.netflix.conductor.server.ConductorServer  - Error starting embedded elasticsearch.  Search functionality will be impacted: Failed to bind to [9200]
    BindHttpException[Failed to bind to [9200]]; nested: ChannelException[Failed to bind to: /127.0.0.1:9200]; nested: BindException[Address already in use];
```
Looks like the port 9200 is already in use on your machine.

I was able to do a ./gradlew clean build from the root of the project

```script
~/r/conductor> gw clean build
Using gradle at '/Users/preddy/repos/conductor/gradlew' to run buildfile '/Users/preddy/repos/conductor/build.gradle':


> Configure project :
Inferred project: conductor, version: 1.9.0-SNAPSHOT

> Configure project :conductor-server
A constructor for `org.gradle.api.internal.java.JavaLibrary` is used by Shadow plugin v1.2.x, and has been preserved for compatibility. This has been deprecated and is scheduled to be removed in Gradle 5.0. If you're using the Shadow plugin, try upgrading to v2.x.

Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

> Task :conductor-core:compileJava
Note: /Users/preddy/repos/conductor/core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/preddy/repos/conductor/core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :conductor-contribs:compileJava
Note: /Users/preddy/repos/conductor/contribs/src/main/java/com/netflix/conductor/contribs/ContribsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :conductor-es5-persistence:compileJava
Note: /Users/preddy/repos/conductor/es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAO.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Download https://jcenter.bintray.com/com/apple/AppleJavaExtensions/1.4/AppleJavaExtensions-1.4.pom
Download https://jcenter.bintray.com/net/sourceforge/pmd/pmd/5.6.1/pmd-5.6.1.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/3/oss-parent-3.pom
Missing header in: common/src/main/java/com/netflix/conductor/common/metadata/tasks/PollData.java
Missing header in: common/src/main/java/com/netflix/conductor/common/metadata/workflow/StartWorkflowRequest.java

> Task :conductor-core:compileTestJava
Note: /Users/preddy/repos/conductor/core/src/test/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapperTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Missing header in: mysql-persistence/src/main/resources/db/migration/V1__initial_schema.sql
Missing header in: mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
Missing header in: mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLBaseDAO.java
Missing header in: mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
Missing header in: mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAO.java

> Task :conductor-server:shadowJar
The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.


BUILD SUCCESSFUL in 1m 45s
94 actionable tasks: 86 executed, 8 up-to-date

```

And also from test-harness:
```script ~/r/c/test-harness> gw clean build
Using gradle at '/Users/preddy/repos/conductor/gradlew' to run buildfile '/Users/preddy/repos/conductor/test-harness/build.gradle':


> Configure project :
Inferred project: conductor, version: 1.9.0-SNAPSHOT

> Configure project :conductor-server
A constructor for `org.gradle.api.internal.java.JavaLibrary` is used by Shadow plugin v1.2.x, and has been preserved for compatibility. This has been deprecated and is scheduled to be removed in Gradle 5.0. If you're using the Shadow plugin, try upgrading to v2.x.

Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

BUILD SUCCESSFUL in 41s
```

**Comment by marczahn** [comment]
Strange thing - I was running Elasticsearch in another project but stopped it defintally. Doesn't matter. I updated it to the current master and it works now.

Thanks for making effort!
