### ISSUE TITLE
getting an error when trying to update a task from java 

### ISSUE THREAD

**Issue by thinkdell01** [Netflix/conductor#522]
When trying to update a task  through java code getting below error.  
1. Everything is running in memory 
2. When same thing is called from swagger API it works. 

ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - Validation Failed: 1: id
is missing;
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: id is missing;
        at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29)
        at org.elasticsearch.action.get.GetRequest.validate(GetRequest.java:127)
        at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:46)
        at org.elasticsearch.client.transport.support.TransportProxyClient$1.doWithNode(TransportProxyClient.java:58)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:228)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:295)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
        at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:446)
        at com.netflix.conductor.dao.index.ElasticSearchDAO.get(ElasticSearchDAO.java:436)
        at com.netflix.conductor.dao.dynomite.RedisExecutionDAO.getWorkflow(RedisExecutionDAO.java:359)
        at com.netflix.conductor.dao.dynomite.RedisExecutionDAO.getWorkflow(RedisExecutionDAO.java:342)
        at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:400)
        at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:162)
        at com.netflix.conductor.server.resources.TaskResource.updateTask(TaskResource.java:129)`

Below is actual code which is being executed. 

`ResteasyWebTarget resteasyWebTarget  = resteasyClient.target( "http://localhost:8080/api/tasks");
// CloseTask is pojo with workflowInstanceId, taskId, reasonForIncompletion,callbackAfterSeconds,workerId,status

 CloseTask task = new CloseTask(workflowInstanceId,
                                            taskId,"Manual Completeion",
                                                                0,"1","COMPLETED");
return resteasyWebTarget.request().post(Entity.entity(task, MediaType.APPLICATION_JSON));
`

**Comment by apanicker-nflx** [comment]
Closing issue for now, please try with newer released versions.
