### ISSUE TITLE
Conductor forces to use redis region as us-east-1c instead actual region

### ISSUE THREAD

**Issue by gsambasiva** [Netflix/conductor#558]
I am using redis as persistence store for conductor application.
And it is deployed in region us-east-1b.
But in config.properties, if we use workflow.dynomite.cluster.hosts with us-east-1b as region, conductor unable to execute tasks.

But if we use us-east-1c as redis region it is working fine, as mentioned in below comment.

In server.properties, I have seen below comment
**For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property. 
EC2_AVAILABILTY_ZONE=us-east-1c.**

What is the reason behind hard coding redis region?
Any suggestions, If I still want to use  us-east-1b instead of us-east-1c ?

**Comment by cyzhao** [comment]
does it not work if you set EC2_AVAILABILITY_ZONE=us-east-1b in server.properties?

**Comment by saidatta** [comment]
@gsambasiva @cyzhao As a side note, I have us-east-1d,us-east-1e in my config.properties that works for me.

**Comment by mudit3774** [comment]
We just moved from a db=redis to db=redis_cluster but the server is unable to start. We are on conductor version 2.x.x

I am able to telnet and redis-cli is working from the box.

This is the config we are using : 

`db=redis_cluster
#Dynomite Cluster details.
#format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=<config-endpoint>:6379:us-east-1c

#namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

#namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor

#no. of threads allocated to dyno-queues
queues.dynomite.threads=75

workflow.dynomite.connection.maxConnsPerHost=75

workflow.system.task.worker.callback.seconds=30
workflow.system.task.worker.poll.interval=10
workflow.system.task.worker.thread.count=80
workflow.system.task.worker.poll.count=80
workflow.system.task.worker.queue.size=800
#non-quorum port used to connect to local redis.  Used by dyno-queues
queues.dynomite.nonQuorum.port=6379

#Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

#Elasticsearch major release version.
workflow.elasticsearch.version=5

# For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property.
EC2_AVAILABILITY_ZONE=us-east-1c
EC2_REGION=us-east-1

port=8080

#Sweeper
decider.sweep.disable=true
decider.sweep.frequency.seconds=6000

workflow.elasticsearch.instanceType=EXTERNAL
workflow.elasticsearch.url=<aws-es-service-endpoint>:80`

This is the error log : 

`2018-12-22 10:03:55 INFO  ModulesProvider:90 - Starting conductor server using redis_cluster.
2018-12-22 10:03:55 INFO  ModulesProvider:113 - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:38)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:111)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:51)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
2018-12-22 10:03:55 INFO  SystemTaskWorkerCoordinator:103 - Adding the queue for system task: HTTP
2018-12-22 10:03:56 INFO  HttpTask:89 - HttpTask initialized...
2018-12-22 10:04:05 INFO  ModulesProvider:90 - Starting conductor server using redis_cluster.
2018-12-22 10:04:05 INFO  ModulesProvider:113 - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:38)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:111)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:51)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
2018-12-22 10:04:05 INFO  SystemTaskWorkerCoordinator:103 - Adding the queue for system task: HTTP
2018-12-22 10:04:05 INFO  HttpTask:89 - HttpTask initialized...`
