### ISSUE TITLE
Conductor server is not working via jar 

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#57]
Running conductor via jar is not working.
java  -jar build/libs/conductor-server-1.7.0-SNAPSHOT-all.jar 

![image](https://cloud.githubusercontent.com/assets/7519767/22577566/5902c5d6-e977-11e6-9567-b85057fb63e3.png)

RemoteTransportException[[Longshot][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":100,"query":{"bool":{"must":[{"query_string":{"query":"*"}},{"bool":{"must":{"match_all":{}}}}]}},"fields":[],"sort":[{"startTime":{"order":"desc"}}]}]]; nested: SearchParseException[No mapping found for [startTime] in order to sort on]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [startTime] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more

Its working fine if i run server via "../gradlew server".

Please suggest.

**Comment by ajayaks** [comment]
Even getting different response in apis like 
api/admin/config , showing lots of info if i run via "../gradlew server" but showing just few properties if i run via jar.

api/metadata/taskdefs , showing all taskdefs via "../gradlew server" but not via jar

**Comment by v1r3n** [comment]
Do you have the complete startup log? Which environment are you testing on? Windows/*nix?

**Comment by v1r3n** [comment]
Also, can you try starting it up with ```-D loadSample=true``` JVM option?

**Comment by ajayaks** [comment]
Perfect , its working now.
Whats the purpose of -DloadSample=true?

**Comment by v1r3n** [comment]
loadSample option loads a kitchensink workflow. UI currently has a bug where it throws error when there are no workflows defined and DB is empty.  Fix coming soon, but in the meantime, creating at-least one workflow instance makes the UI functional.

**Comment by ajayaks** [comment]
Hi Viren, 

I have raised one more issue for #59 where i am getting ArrayIndexOutOfBound while starting the conductor, please have a look.
