### ISSUE TITLE
v1.10.0 redis java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by juaby** [Netflix/conductor#579]
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3538)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.createConnectionPool(DynoJedisClient.java:3509)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:3487)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3421)
	at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:139)
	at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:115)
	at com.jdjr.cds.conductor.Main.main(Main.java:31)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.calculateReplicationFactor(HostSelectionWithFallback.java:394)
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.initWithHosts(HostSelectionWithFallback.java:351)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.initSelectionStrategy(ConnectionPoolImpl.java:627)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:526)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3521)
	... 6 more

**Comment by mateimicu** [comment]
Make sure the `rack` portion of the config from `workflow.dynomite.cluster.hosts` is a valid region `us-east-1b`. Even if you use `db=redis` you still need a valid region there for validation reasons. 

More info here: https://github.com/Netflix/conductor/issues/59

**Comment by rajeshso** [comment]
I am using redis from a local docker container. There is no rack value for the local container. How can i provide a value ?

**Comment by mateimicu** [comment]
`workflow.dynomite.cluster.hosts=redis-host:redis-us-east-1b;` should work for local use
