### ISSUE TITLE
Build Failure while building the server module.

### ISSUE THREAD

**Issue by akshat-g** [Netflix/conductor#581]
I cloned the repo and built it using ../gradlew server command. Build failed because some of the dependencies could not be found/downloaded.
`* What went wrong:
Could not resolve all files for configuration ':conductor-es5-persistence:compileClasspath'.
> Could not download transport.jar (org.elasticsearch.client:transport:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/client/transport/5.6.8/transport-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/client/transport/5.6.8/transport-5.6.8.jar'.
         > Read timed out
> Could not download transport-netty3-client.jar (org.elasticsearch.plugin:transport-netty3-client:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/plugin/transport-netty3-client/5.6.8/transport-netty3-client-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/plugin/transport-netty3-client/5.6.8/transport-netty3-client-5.6.8.jar'.
         > Read timed out
> Could not download transport-netty4-client.jar (org.elasticsearch.plugin:transport-netty4-client:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/plugin/transport-netty4-client/5.6.8/transport-netty4-client-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/plugin/transport-netty4-client/5.6.8/transport-netty4-client-5.6.8.jar'.
         > Read timed out
> Could not download reindex-client.jar (org.elasticsearch.plugin:reindex-client:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/plugin/reindex-client/5.6.8/reindex-client-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/plugin/reindex-client/5.6.8/reindex-client-5.6.8.jar'.
         > Read timed out
> Could not download lang-mustache-client.jar (org.elasticsearch.plugin:lang-mustache-client:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/plugin/lang-mustache-client/5.6.8/lang-mustache-client-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/plugin/lang-mustache-client/5.6.8/lang-mustache-client-5.6.8.jar'.
         > Read timed out
> Could not download percolator-client.jar (org.elasticsearch.plugin:percolator-client:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/plugin/percolator-client/5.6.8/percolator-client-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/plugin/percolator-client/5.6.8/percolator-client-5.6.8.jar'.
         > Read timed out
> Could not download parent-join-client.jar (org.elasticsearch.plugin:parent-join-client:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/plugin/parent-join-client/5.6.8/parent-join-client-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/plugin/parent-join-client/5.6.8/parent-join-client-5.6.8.jar'.
         > Read timed out
> Could not download elasticsearch.jar (org.elasticsearch:elasticsearch:5.6.8)
   > Could not get resource 'https://jcenter.bintray.com/org/elasticsearch/elasticsearch/5.6.8/elasticsearch-5.6.8.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/elasticsearch/elasticsearch/5.6.8/elasticsearch-5.6.8.jar'.
         > Read timed out
> Could not download lucene-core.jar (org.apache.lucene:lucene-core:6.6.1)
   > Could not get resource 'https://jcenter.bintray.com/org/apache/lucene/lucene-core/6.6.1/lucene-core-6.6.1.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/apache/lucene/lucene-core/6.6.1/lucene-core-6.6.1.jar'.
         > Read timed out
> Could not download lucene-analyzers-common.jar (org.apache.lucene:lucene-analyzers-common:6.6.1)
   > Could not get resource 'https://jcenter.bintray.com/org/apache/lucene/lucene-analyzers-common/6.6.1/lucene-analyzers-common-6.6.1.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/apache/lucene/lucene-analyzers-common/6.6.1/lucene-analyzers-common-6.6.1.jar'.
         > Read timed out
> Could not download lucene-highlighter.jar (org.apache.lucene:lucene-highlighter:6.6.1)
   > Could not get resource 'https://jcenter.bintray.com/org/apache/lucene/lucene-highlighter/6.6.1/lucene-highlighter-6.6.1.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/apache/lucene/lucene-highlighter/6.6.1/lucene-highlighter-6.6.1.jar'.
         > Read timed out
> Could not download lucene-queries.jar (org.apache.lucene:lucene-queries:6.6.1)
   > Could not get resource 'https://jcenter.bintray.com/org/apache/lucene/lucene-queries/6.6.1/lucene-queries-6.6.1.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/apache/lucene/lucene-queries/6.6.1/lucene-queries-6.6.1.jar'.
         > Read timed out
`

**Comment by kishorebanala** [comment]
@akshat-g I tried with a fresh copy and couldn't reproduce this. Was this recurring? We're you behind a proxy?

**Comment by akshat-g** [comment]
@kishorebanala  - hey Yeah so I was behind a proxy. However today I am getting this error while building- 

`Error injecting constructor, java.lang.NullPointerException
  at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.<init>(RedisMetadataDAO.java:58)
  at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.class(RedisMetadataDAO.java:54)
  while locating com.netflix.conductor.dao.dynomite.RedisMetadataDAO
  while locating com.netflix.conductor.dao.MetadataDAO
    for the 1st parameter of com.netflix.conductor.core.execution.DeciderService.<init>(DeciderService.java:73)
  while locating com.netflix.conductor.core.execution.DeciderService
    for the 1st parameter of com.netflix.conductor.core.execution.WorkflowExecutor.<init>(WorkflowExecutor.java:91)
  while locating com.netflix.conductor.core.execution.WorkflowExecutor
    for the 1st parameter of com.netflix.conductor.core.events.ActionProcessor.<init>(ActionProcessor.java:62)
  at com.netflix.conductor.core.config.CoreModule.configure(CoreModule.java:63) (via modules: com.netflix.conductor.server.ServerModule -> com.netflix.conductor.core.config.CoreModule)
  while locating com.netflix.conductor.core.events.ActionProcessor
Caused by: java.lang.NullPointerException
        at java.lang.StringBuilder.<init>(StringBuilder.java:112)
        at com.netflix.conductor.dao.dynomite.BaseDynoDAO.nsKey(BaseDynoDAO.java:51)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getAllTaskDefs(RedisMetadataDAO.java:124)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.refreshTaskDefs(RedisMetadataDAO.java:92)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.<init>(RedisMetadataDAO.java:59)
        at com.netflix.conductor.dao.dynomite.RedisMetadataDAO$$FastClassByGuice$$1f364347.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.netflix.conductor.server.ConductorServer.start(ConductorServer.java:210)
        at com.netflix.conductor.server.Main.main(Main.java:54)`

Any help would be appreciated since I am really new to conductor and playing a catchup game.

**Comment by kishorebanala** [comment]
@akshat-g We have a fix in progress - https://github.com/Netflix/conductor/pull/588. If you would like to use this meanwhile, just specify "workflow.namespace.prefix" to some value in configuration. For example, "conductor" would be a good candidate. This sets conductor as prefix to Dyno / Redis keys.

**Comment by kishorebanala** [comment]
@akshat-g Please feel free to provide any feedback while you're learning.
