### ISSUE TITLE
Lastest release error loading config.properties

### ISSUE THREAD

**Issue by deluxor** [Netflix/conductor#590]
Hey guys, after the compilation of the latest release of conductor and deploying it to our docker swarm something weird started to occur, please check out the logs below:

> Starting Conductor server
> Property file: config.properties
> config.properties
> Using 'config.properties'
> Using config fileconductor-server-1.11.0-SNAPSHOT-all.jar
> Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
> at java.util.Properties.loadConvert(Properties.java:574)
> at java.util.Properties.load0(Properties.java:391)
> at java.util.Properties.load(Properties.java:341)
> at com.netflix.conductor.server.Main.loadConfigFile(Main.java:62)
> at com.netflix.conductor.server.Main.main(Main.java:36)

At the beginning I tought that was because of my file encoding, but then I remembered that  this particular file was being used in the last version.

My config file:

```java
db=mysql
jdbc.url=jdbc:mysql://db:3306/conductor
jdbc.username=conductor
jdbc.password=mypasswordblablabla
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
workflow.elasticsearch.url=es:9300
workflow.elasticsearch.index.name=conductor
loadSample=false
```

**Comment by kishorebanala** [comment]
@deluxor We're you able to debug where exactly this is breaking? Does it breaks for a particular setting? Also, can you get me full error logs please.

**Comment by deluxor** [comment]
@kishorebanala The config I used is above, I just checkout the git repo, built the JAR's, generated the docker images and started the services on docker, but no luck

**Comment by star-yar** [comment]
Have same problem even after recompilation fails because of encoding.

**Comment by reidlai** [comment]
same here
