### ISSUE TITLE
Connection Reset errors with high volume of concurrent transactions

### ISSUE THREAD

**Issue by jvemugunta** [Netflix/conductor#634]
Perf testing was done with 100 concurrent users for 10 mins.

I see these errors in the middle of the tests. Any ideas on the root cause of the problem ?

3787390 [qtp1596843797-125] DEBUG org.eclipse.jetty.server.HttpConnection  - New HTTP Connection HttpConnection@66618ef8[SelectChannelEndPoint@5f3fd51e{/127.0.0.1:65521<->8080,Open,in,out,-,-,1/30000,null@0}{io=0/0,kio=0,kro=0}][p=HttpParser{s=START,0 of 0},g=HttpGenerator@4757300f{s=START},c=HttpChannelOverHttp@406df0c{r=0,c=false,a=IDLE,uri=null}]
3787390 [qtp1596843797-97] DEBUG com.netflix.conductor.common.utils.RetryUtil  - Attempt # 1, 1 millis since first attempt. Operation: updateWithRetry, description:Index workflow into doc_type workflow
3787390 [qtp1596843797-125] DEBUG org.eclipse.jetty.io.AbstractConnection  - onOpen HttpConnection@66618ef8[SelectChannelEndPoint@5f3fd51e{/127.0.0.1:65521<->8080,Open,in,out,-,-,1/30000,HttpConnection@66618ef8}{io=0/0,kio=0,kro=0}][p=HttpParser{s=START,0 of 0},g=HttpGenerator@4757300f{s=START},c=HttpChannelOverHttp@406df0c{r=0,c=false,a=IDLE,uri=null}]
3787390 [qtp1596843797-120] DEBUG org.eclipse.jetty.server.HttpChannel  - HttpChannelOverHttp@36ab5ed6{r=1,c=false,a=IDLE,uri=null} handle exit, result COMPLETE
3787390 [qtp1596843797-125] DEBUG org.eclipse.jetty.io.AbstractConnection  - fillInterested HttpConnection@66618ef8[SelectChannelEndPoint@5f3fd51e{/127.0.0.1:65521<->8080,Open,in,out,-,-,1/30000,HttpConnection@66618ef8}{io=0/0,kio=0,kro=0}][p=HttpParser{s=START,0 of 0},g=HttpGenerator@4757300f{s=START},c=HttpChannelOverHttp@406df0c{r=0,c=false,a=IDLE,uri=null}]
3787390 [qtp1596843797-147] DEBUG org.eclipse.jetty.io.ChannelEndPoint  - 
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.eclipse.jetty.io.ChannelEndPoint.fill(ChannelEndPoint.java:145)
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:325)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:233)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)

**Comment by apanicker-nflx** [comment]
Please let us know if you see this issue with the newest releases (2.7.+).
Closing this issue for now.
