### ISSUE TITLE
Starting UI Server failed

### ISSUE THREAD

**Issue by HardiChandra** [Netflix/conductor#703]
Hi,

I am new to conductor, trying to start the UI server in a new machine.
I run `npm install` before doing `gulp watch`
And I got the message below when I'm doing it.

```
[12:08:32] Requiring external module babel-register
process.argv =====>  [ '/usr/local/bin/node', '/usr/local/bin/gulp', 'watch' ]
DEBUG =====>  true
WATCH =====>  true
[12:08:34] Using gulpfile ~/Learn/conductor/conductor/ui/gulpfile.babel.js
[12:08:34] Starting 'watch'...
[12:08:34] Starting 'clean'...
[12:08:34] Finished 'clean' after 6.24 ms
[12:08:34] Starting 'set-env'...
[12:08:34] Finished 'set-env' after 2.72 ms
[12:08:34] Starting 'serve'...
Stats : undefined
[12:08:34] Starting 'watchTask'...
[12:08:34] Finished 'watchTask' after 29 ms
[12:08:34] Starting 'public'...
[12:08:34] Finished 'public' after 6.9 ms
[12:08:34] Starting 'styles'...
[12:08:34] Finished 'styles' after 5.77 ms
[12:08:34] Starting 'fonts'...
[12:08:34] Finished 'fonts' after 653 μs
[12:08:34] Starting 'lint'...
[12:08:34] Finished 'lint' after 40 ms
[12:08:34] Starting 'images'...
[12:08:34] Finished 'images' after 890 μs
/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:102
        throw new Error(message.join(""));
        ^

Error: /Users/HC/Learn/conductor/conductor/ui/.eslintrc.js:
	Configuration for rule "indent" is invalid:
	Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").

    at validateRuleOptions (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:147:35)
    at Object.load (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:390:19)
    at loadConfig (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:74:33)
    at getLocalConfig (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:177:23)
    at Config.getConfig (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:272:22)
    at processText (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:203:27)
    at CLIEngine.executeOnText (/Users/HC/Learn/conductor/conductor/ui/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:686:26)
```

I tried running `npm install babel-register - g` and `npm install eslint -g`

but still it doesn't work
Any suggestions? thx In advance

**Comment by josedab** [comment]
@HardiChandra Try deleting the `.eslintrc` file. That will make gulp to not run the eslint rules. It worked for me as a short term solution.

However, if you are changing code on the UI, I would recommend to have the rules on before submitting a PR as these rules help detect coding style issues.

**Comment by apanicker-nflx** [comment]
@HardiChandra are you still seeing this issue with the latest versions?
Closing this issue for now, please reopen if you run into this.
