### ISSUE TITLE
Connectivity issue with AWS managed ElasticSearch

### ISSUE THREAD

**Issue by rksinha** [Netflix/conductor#728]
Tried using AWS managed ElasticSearch version 5.5 and version 6.2 both on port 80 and 443.

**Getting issue :** 
2963 [main] ERROR com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5  - None of the configured nodes are available: [{#transport#-1}{gCAkVVRvTHes5XXXXXXX}{xxxxxxx.amazonaws.com}{172.xxx.xxx.xxx:443}]
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{gCAkVVRvTHes5XXXXXXX}{xxxxxxx.amazonaws.com}{172.xxx.xxx.xxx:443}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.initIndex(ElasticSearchDAOV5.java:188)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.<init>(ElasticSearchDAOV5.java:147)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5$$FastClassByGuice$$1c3df583.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)

@cyzhao @v1r3n

**Comment by cyzhao** [comment]
@kishorebanala

**Comment by saidatta** [comment]
I usually encountered when the AWS was not reachable from the conductor node. Also, when I tried bringing up ElasticSearch before the ConductorServer booted up.

**Comment by malpani** [comment]
the main reason for this is conductor currently uses the transport client only, are there plans to support this using the Rest API - https://github.com/Netflix/conductor/issues/455 ? I am new to conductor so it will be great if the contributors could share some insights on the changes that would be involved in adding support for the rest client?

**Comment by bitbier** [comment]
We wanted the same thing. So I'm currently working on it for my company and asking for comments and suggestions on improving the code that I wrote here: https://github.com/Netflix/conductor/pull/803. I have not done Java work in a long time, so any comments on improving how I do things here.

**Comment by JasperB** [comment]
Hi,
Does this issue resolved? we also met this issue we cannot connect to ES with es master node with default port:9300, anyone know how to fix this to connect external ES cluster?

**Comment by JasperB** [comment]
@rksinha 
Hi,
Did this issue fixed? we also meet this issue when we try to use external ES cluster with transport port 9300.

**Comment by malpani** [comment]
@JasperB https://github.com/Netflix/conductor/pull/803 fixes this

**Comment by apanicker-nflx** [comment]
Closing this issue because using the ES Rest client resolves the connectivity issue with AWS managed ElasticSearch.
