### ISSUE TITLE
Error in UI

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#79]
UI is not showing anything.

Hi, 

Conductor is running on 8080 port , dynomite is also running, elsatic search is also runnin with index.

Same setup was  working fine but now suddenly i am getting below exception. I can see the list of tasks, workflows from apis but not from UI. I am getting same exception everytime. Please suggest.

Error: Not Found
    at Request.callback (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by v1r3n** [comment]
Do you have a screenshot or some other error?  When you started the conductor server, did you pass ```-DloadSample=true``` JVM argument?  There is a known bug with UI that causes errors when the database is empty.

**Comment by v1r3n** [comment]
A screenshot will be helpful.  Also, try doing ```npm install``` to make sure all the dependencies are installed.

**Comment by v1r3n** [comment]
closing - as reported in https://github.com/Netflix/conductor/issues/70
