### ISSUE TITLE
Is it possible to start server right now?

### ISSUE THREAD

**Issue by unikzforce** [Netflix/conductor#805]
I Cannot start server in any method. you know how to resolve this?

in docker-compose, conductor-server cannot be started:
`docker-compose up | grep conductor-server`:
```
Starting docker_elasticsearch_1 ... done
Starting docker_dynomite_1      ... done
Starting docker_conductor-server_1 ... done
Starting docker_conductor-ui_1     ... done
Attaching to docker_dynomite_1, docker_elasticsearch_1, docker_conductor-server_1, docker_conductor-ui_1
conductor-ui_1      | using Conductor API server from 'http://conductor-server:8080/api/'
conductor-server_1  | Starting Conductor server
conductor-server_1  | Property file: config.properties
conductor-server_1  | config.properties
conductor-server_1  | Using 'config.properties'
conductor-server_1  | Using config file/app/config/config.properties
conductor-server_1  | 0    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - Starting conductor server using dynomite/redis cluster.
conductor-server_1  | 3    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - External payload storage is not configured, provided: , supported values are: [S3]
conductor-server_1  | java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
conductor-server_1  | 	at java.lang.Enum.valueOf(Enum.java:238)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:33)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:99)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:46)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
conductor-server_1  | 317  [main] INFO  com.netflix.archaius.guice.ConfigurationInjectingListener  - Initializing ConfigurationInjectingListener
conductor-server_1  | 944  [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
conductor-server_1  | 945  [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
conductor-server_1  | 947  [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 947  [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null], with conns:10
conductor-server_1  | 962  [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 10 of 10 to Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 966  [main] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Adding Host to TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 968  [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - registered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
conductor-server_1  | 971  [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
conductor-server_1  | 971  [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
conductor-server_1  | 971  [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 971  [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null], with conns:10
conductor-server_1  | 972  [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 10 of 10 to Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 978  [main] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Adding Host to TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 979  [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole has already been registered !
conductor-server_1  | 985  [main] INFO  com.netflix.conductor.dyno.RedisQueuesProvider  - DynoQueueDAO initialized with prefix conductor_queues.test!
conductor-server_1  | ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
conductor-server_1  | 2077 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - System Task Worker initialized with 10 threads and a callback time of 30 seconds and queue size: 100 with pollCount: 10 and poll interval: 50
conductor-server_1  | 2077 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: SUB_WORKFLOW
conductor-server_1  | 2077 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: WAIT
conductor-server_1  | 2077 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: EVENT
conductor-server_1  | NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{I91YPutbQaG66GW4Bd6WoA}{es}{172.23.0.3:9300}]]
conductor-server_1  | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
conductor-server_1  | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
conductor-server_1  | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
conductor-server_1  | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
conductor-server_1  | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
conductor-server_1  | 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
conductor-server_1  | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
conductor-server_1  | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
conductor-server_1  | 	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.setup(ElasticSearchDAOV5.java:157)
conductor-server_1  | 	at com.netflix.conductor.bootstrap.Main.main(Main.java:71)
conductor-server_1  | 2081 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Removing host dyno1 from selectionStrategy, cpHealthTracker, cpMonitor
conductor-server_1  | 2081 [Thread-2] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Removing host dyno1 from selectionStrategy, cpHealthTracker, cpMonitor
conductor-server_1  | 2081 [Thread-1] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Removing Host from TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 2081 [Thread-2] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Removing Host from TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 2081 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Shutting down connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 2081 [Thread-2] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Shutting down connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
conductor-server_1  | 2082 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2082 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2082 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2082 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2082 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2083 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-1] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2084 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Remove host: Successfully removed hostPool for host dyno1 from connection pool
conductor-server_1  | 2085 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - deregistered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
conductor-server_1  | 2085 [Thread-2] WARN  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null] Unexpected end of stream.
conductor-server_1  | 2085 [Thread-2] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Remove host: Successfully removed hostPool for host dyno1 from connection pool
docker_conductor-server_1 exited with code 3
```

**Comment by unikzforce** [comment]
i made a [pull request](https://github.com/Netflix/conductor/pull/806) for this.
it's the first time in my life to create a pull request on a big project like this.. if it's not okey, please tell me how to fix it.
