### ISSUE TITLE
About mysql Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by juaby** [Netflix/conductor#815]
```ERROR com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator - BACKEND_ERROR - BACKEND_ERROR
com.netflix.conductor.core.execution.ApplicationException: BACKEND_ERROR - BACKEND_ERROR
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:103) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.pop(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.pollAndExecute(SystemTaskWorkerCoordinator.java:143) ~[conductor-core-1.10.10.jar:1.10.10]
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$listen$1(SystemTaskWorkerCoordinator.java:125) ~[conductor-core-1.10.10.jar:1.10.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: com.netflix.conductor.core.execution.ApplicationException: BACKEND_ERROR
	at com.netflix.conductor.dao.mysql.Query.executeQuery(Query.java:297) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.Query.executeAndFetch(Query.java:417) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$peekMessages$23(MySQLQueueDAO.java:208) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.query(MySQLBaseDAO.java:155) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.peekMessages(MySQLQueueDAO.java:207) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.popMessages(MySQLQueueDAO.java:226) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$pop$4(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:98) ~[conductor-mysql-persistence-1.10.10.jar:?]
	... 10 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_66]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_66]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1999) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3403) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:471) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3115) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2344) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2739) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.2.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.2.0.jar:?]
	at com.netflix.conductor.dao.mysql.Query.executeQuery(Query.java:295) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.Query.executeAndFetch(Query.java:417) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$peekMessages$23(MySQLQueueDAO.java:208) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.query(MySQLBaseDAO.java:155) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.peekMessages(MySQLQueueDAO.java:207) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.popMessages(MySQLQueueDAO.java:226) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$pop$4(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:98) ~[conductor-mysql-persistence-1.10.10.jar:?]
	... 10 more
2018-10-16 16:29:06.822 [HikariPool-1 housekeeper] WARN  com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@52e9636b on thread pool-23-thread-1, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-3.2.0.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:94) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.pop(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.pollAndExecute(SystemTaskWorkerCoordinator.java:143) ~[conductor-core-1.10.10.jar:1.10.10]
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$listen$1(SystemTaskWorkerCoordinator.java:125) ~[conductor-core-1.10.10.jar:1.10.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
2018-10-16 16:29:37.905 [pool-23-thread-1] INFO  com.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection com.mysql.jdbc.JDBC4Connection@52e9636b on thread pool-23-thread-1 was returned to the pool (unleaked)
2018-10-16 16:29:37.905 [pool-23-thread-1] ERROR com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator - BACKEND_ERROR - BACKEND_ERROR
com.netflix.conductor.core.execution.ApplicationException: BACKEND_ERROR - BACKEND_ERROR
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:103) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.pop(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.pollAndExecute(SystemTaskWorkerCoordinator.java:143) ~[conductor-core-1.10.10.jar:1.10.10]
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$listen$1(SystemTaskWorkerCoordinator.java:125) ~[conductor-core-1.10.10.jar:1.10.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: com.netflix.conductor.core.execution.ApplicationException: BACKEND_ERROR
	at com.netflix.conductor.dao.mysql.Query.executeQuery(Query.java:297) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.Query.executeAndFetch(Query.java:417) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$peekMessages$23(MySQLQueueDAO.java:208) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.query(MySQLBaseDAO.java:155) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.peekMessages(MySQLQueueDAO.java:207) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.popMessages(MySQLQueueDAO.java:226) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$pop$4(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:98) ~[conductor-mysql-persistence-1.10.10.jar:?]
	... 10 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_66]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_66]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1999) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3403) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:471) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3115) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2344) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2739) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.2.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.2.0.jar:?]
	at com.netflix.conductor.dao.mysql.Query.executeQuery(Query.java:295) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.Query.executeAndFetch(Query.java:417) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$peekMessages$23(MySQLQueueDAO.java:208) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.query(MySQLBaseDAO.java:155) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.peekMessages(MySQLQueueDAO.java:207) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.popMessages(MySQLQueueDAO.java:226) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLQueueDAO.lambda$pop$4(MySQLQueueDAO.java:57) ~[conductor-mysql-persistence-1.10.10.jar:?]
	at com.netflix.conductor.dao.mysql.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:98) ~[conductor-mysql-persistence-1.10.10.jar:?]
	... 10 more
```

**Comment by kishorebanala** [comment]
Closing this as it has been a while. Please feel free to reopen if you still see the issue.

**Comment by 0532** [comment]
![image](https://user-images.githubusercontent.com/5317048/63736829-029e2600-c8b7-11e9-91e9-deda0954b6cb.png)

I have encountered the same problem and can give some advice.

linux 
jdk 1.8.0
mysql-persistence 2.13.5
conductor-core 2.13.5
@kishorebanala
