### ISSUE TITLE
SampleWorker: "Error when pollig for task" with JsonMappingException

### ISSUE THREAD

**Issue by niwy** [Netflix/conductor#83]
Hello,

I'm trying the SampleWorker at: [https://github.com/Netflix/conductor/tree/dev/client/src/test/java/com/netflix/conductor/client/sample]

I started an instance of kitchensink, and tried to poll task_1 using SampleWorker. However, I got the following errors. I am working on Win 7. Please help. Thanks.

```
[pool-1-thread-1] ERROR com.netflix.conductor.client.task.WorkflowTaskCoordinator - Error when pollig for task
java.lang.RuntimeException: com.sun.jersey.api.client.ClientHandlerException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "type": com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params) vs com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params)
	at com.netflix.conductor.client.http.ClientBase.handleException(ClientBase.java:189)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:179)
	at com.netflix.conductor.client.http.TaskClient.poll(TaskClient.java:88)
	at com.netflix.conductor.client.task.WorkflowTaskCoordinator.pollForTask(WorkflowTaskCoordinator.java:208)
	at com.netflix.conductor.client.task.WorkflowTaskCoordinator.lambda$2(WorkflowTaskCoordinator.java:173)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.sun.jersey.api.client.ClientHandlerException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "type": com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params) vs com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:644)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:604)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:698)
	at com.sun.jersey.api.client.WebResource.access$300(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:514)
	at com.netflix.conductor.client.http.ClientBase.getForEntity(ClientBase.java:176)
	... 10 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "type": com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params) vs com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:270)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:245)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:406)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:882)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:436)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:297)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:245)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:406)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:653)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:444)
	at com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:1566)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1405)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:860)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
	... 15 more
Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property "type": com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params) vs com.netflix.conductor.common.metadata.workflow.WorkflowTask#setType(1 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:583)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:479)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:409)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:358)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:265)
	... 33 more
```

**Comment by v1r3n** [comment]
@niwy The error indicates the incompatibility between the version of jackson mapper used by conductor and your runtime JVM.

We recommend using 2.7.5 version of jackson-* libraries in your classpath.

**Comment by niwy** [comment]
@v1r3n Thanks for replying.
 I'm using 2.7.5 jackson, and the Java version is 1.8.0_121.
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

I tired different versions of jackson, e.g., 2.6.7, 2.7.4, 2.8.6. Besides, I exported a jar to run a linux machine with java 1.8.0_101. Anyhow, the errors remain.

**Comment by v1r3n** [comment]
@niwy I have renamed the offending method (it was on the TODO list already).  Can you give it a try with the ```dev``` branch again?  Let me know if the problem persists.

**Comment by niwy** [comment]
@v1r3n It works now. Thanks a lot.
