### ISSUE TITLE
 Conductor server always error "Malformed \uxxxx encoding"

### ISSUE THREAD

**Issue by boshido** [Netflix/conductor#836]
Conductor version: 2.0.0
Build type: Docker (Following README.md in docker directory)
Runner: docker-compose up

```
Starting Conductor server
Property file: config.properties
config.properties
Using 'config.properties'
Using config fileconductor-server-2.1.0-SNAPSHOT-all.jar
Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.util.Properties.loadConvert(Properties.java:574)
        at java.util.Properties.load0(Properties.java:391)
        at java.util.Properties.load(Properties.java:341)
        at com.netflix.conductor.server.Main.loadConfigFile(Main.java:62)
        at com.netflix.conductor.server.Main.main(Main.java:36)

```

Run without CONFIG_PROP=config.properties
```
Starting Conductor server
Property file:

Using an in-memory instance of conductor
Using config fileconductor-server-2.1.0-SNAPSHOT-all.jar
Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.util.Properties.loadConvert(Properties.java:574)
        at java.util.Properties.load0(Properties.java:391)
        at java.util.Properties.load(Properties.java:341)
        at com.netflix.conductor.server.Main.loadConfigFile(Main.java:62)
        at com.netflix.conductor.server.Main.main(Main.java:36)
```

**Comment by chinajuanbob** [comment]
+1

**Comment by kishorebanala** [comment]
Closing this as it's been a while. Please feel free to reopen if you still see the issue.
