### ISSUE TITLE
NullPointerException when starting up (using dynomite)

### ISSUE THREAD

**Issue by stevenctl** [Netflix/conductor#856]
Using conductor version 2.1.0 (downloaded from https://bintray.com/netflixoss/maven/conductor/2.1.0)

Configuration is as follows (all IPs replaced with 1.2.3.4, they are unique in actual config)

I have validated the dynomite cluster is functioning properly using redis-cli

```
db=dynomite
workflow.dynomite.cluster=my-dyno
workflow.dynomite.cluster.name=my-dyno

workflow.dynomite.cluster.hosts=1.2.3.4:8102:us-west-2a:us-west-2;1.2.3.4:8102:us-west-2a:us-west-2;1.2.3.4:8102:us-east-1a:us-east-1;1.2.3.4:8102:us-east-1a:us-east-1;1.2.3.4:8102:eu-west-1a:eu-west-1;1.2.3.4:8102:eu-west-1a:eu-west-1

queues.dynomite.nonQuorum.port=8102
queues.dynomite.threads=10

workflow.namespace.prefix=my-conductor
wworkflow.namespace.queue.prefix=my-conductor-queue

# Elasticsearch

workflow.elasticsearch.instanceType=memory

# workflow.elasticsearch.url=my-elasticsearch.my.dom:9300
# workflow.elasticsearch.version=5
# workflow.elasticsearch.index.name=my-conductor-index


# I tried running with and without this property 
EC2_AVAILABILITY_ZONE=us-east-1a
```

Stack Trace
```
1) Error in custom provider, java.lang.RuntimeException: java.lang.NullPointerException
  while locating com.netflix.conductor.jedis.DynomiteJedisProvider
  at com.netflix.conductor.server.DynomiteClusterModule.configure(DynomiteClusterModule.java:25)
  while locating redis.clients.jedis.JedisCommands
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4309)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.createConnectionPool(DynoJedisClient.java:4281)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:4257)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:4186)
        at com.netflix.conductor.jedis.DynomiteJedisProvider.get(DynomiteJedisProvider.java:49)
        at com.netflix.conductor.jedis.DynomiteJedisProvider.get(DynomiteJedisProvider.java:14)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
        at com.netflix.governator.event.ApplicationEventModule$ApplicationEventSubscribingProvisionListener.onProvision(ApplicationEventModule.java:89)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
Caused by: java.lang.NullPointerException
        at com.netflix.dyno.connectionpool.impl.HostsUpdater.refreshHosts(HostsUpdater.java:111)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:486)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4292)
        ... 29 more
```

Full log (there are 51 "Error in custom provider" stack traces, mostly very similar)
[server.log](https://github.com/Netflix/conductor/files/2558912/server.log)

**Comment by stevenctl** [comment]
This only occurs when I specify multiple dynomite hosts, if I specify one it gets stuck doing this:

```
10713 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
10713 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
10714 [pool-27-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=10.124.15.65, ipAddress=null, port=8102, rack: us-west-2a, datacenter: us-west-2, status: Up, hashtag=null]
```

And the pool numbers climb indefinitely

**Comment by suanyi001** [comment]
hey,i have the same error,have you solved it?

**Comment by ndidi-did** [comment]
I'm getting the same error -- I thought to add a third node just in case that 3 are required for HA purposes but it seems as if that's not the case, they are all connected and working together in the cluster but I'm still getting the same error as above when containing more than one host in the hosts property.

**Comment by suanyi001** [comment]
Thanks a lot!This has been bothering for a long time！


原始邮件
发件人:Sambanotifications@github.com
收件人:Netflix/conductorconductor@noreply.github.com
抄送:susamasuanyi001@126.com; Commentcomment@noreply.github.com
发送时间:2018年12月28日(周五) 15:28
主题:Re: [Netflix/conductor] NullPointerException when starting up (usingdynomite) (#856)


I am also getting the same error, I did some debug and updated below class code. It solved my problem.
https://github.com/Netflix/conductor/blob/master/redis-persistence/src/main/java/com/netflix/conductor/jedis/TokenMapSupplierProvider.java
@override
 public TokenMapSupplier get() {
 return new TokenMapSupplier() {
// FIXME This isn't particularly safe, but it is equivalent to the existing code. // FIXME It seems like we should be supply tokens for more than one host? HostToken token = new HostToken(1L, Lists.newArrayList(hostSupplier.getHosts()).get(0)); @Override public ListHostToken getTokens(SetHost dynoHosts) { ListHostToken hostTokens = new ArrayList(); long i=1l; for (Host host : dynoHosts) { HostToken hostToken = new HostToken(i, host); hostTokens.add(hostToken); i++; } return hostTokens; } @Override public HostToken getTokenForHost(Host host, SetHost activeHosts) { return token; } }; }
