### ISSUE TITLE
conductor can not connected dynomite cluster

### ISSUE THREAD

**Issue by suanyi001** [Netflix/conductor#895]
when i used dynomite cluster(Deploy locally) , conductor server can not connected.Below is my configuration ：

```
#dynomite-c1

dyn_o_mite:
    datacenter: us-east-2
    dyn_listen: 127.0.0.1:8401
    dyn_seed_provider: simple_provider
    dyn_seeds:
    - 127.0.0.1:8501:us-east-2b:us-east-2:1
    - 127.0.0.1:8601:us-east-2c:us-east-2:1
    listen: 127.0.0.1:8402
    rack: us-east-2a
    secure_server_option: all
    servers:
    - 127.0.0.1:7004:1
    stats_listen: 127.0.0.1:30003
    timeout: 150000
    tokens: 1

#dynomite-c2

dyn_o_mite:
    datacenter: us-east-2
    dyn_listen: 127.0.0.1:8501
    dyn_seed_provider: simple_provider
    dyn_seeds:
    - 127.0.0.1:8401:us-east-2a:us-east-2:1
    - 127.0.0.1:8601:us-east-2c:us-east-2:1
    listen: 127.0.0.1:8502
    rack: us-east-2b
    secure_server_option: all
    servers:
    - 127.0.0.1:7005:1
    stats_listen: 127.0.0.1:30004
    timeout: 150000
    tokens: 1
#dynomite-c3

dyn_o_mite:
    datacenter: us-east-2
    dyn_listen: 127.0.0.1:8601
    dyn_seed_provider: simple_provider
    dyn_seeds:
    - 127.0.0.1:8401:us-east-2a:us-east-2:1
    - 127.0.0.1:8501:us-east-2b:us-east-2:1
    listen: 127.0.0.1:8602
    rack: us-east-2c
    secure_server_option: all
    servers:
    - 127.0.0.1:7006:1
    stats_listen: 127.0.0.1:30005
    timeout: 1
    tokens: 1

conductor server config

# Database persistence model.  Possible values are memory, redis, redis_cluster and dynomite.
# If omitted, the persistence used is memory
#
# memory : The data is stored in memory and lost when the server dies.  Useful for testing or demo
# redis : non-Dynomite based redis instance
# redis_cluster: AWS Elasticache Redis (cluster mode enabled).See [http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Clusters.Create.CON.RedisCluster.html]
# dynomite : Dynomite cluster.  Use this for HA configuration.
db=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
# for AWS Elasticache Redis (cluster mode enabled) the format is configuration_endpoint:port:us-east-1e. The region in this case does not matter
workflow.dynomite.cluster.hosts=127.0.0.1:8102:us-east-1a;127.0.0.1:8202:us-east-1b;127.0.0.1:8302:us-east-1c

# Dynomite cluster name
workflow.dynomite.cluster.name=dyno_cluster_name

# Maximum connections to redis/dynomite
workflow.dynomite.connection.maxConnsPerHost=31

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
#queues.dynomite.nonQuorum.port=7000,7001,7003

# Transport address to elasticsearch
workflow.elasticsearch.url=localhost:9300

# Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

EC2_AVAILABILITY_ZONE=us-east-1b

EC2_REGION=us-east-1
```

Below is my logs:
```
0    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - Starting conductor server using dynomite/redis cluster.
5    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:37)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:105)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:50)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
289  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: HTTP
464  [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
465  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: JSON_JQ_TRANSFORM
1097 [main] INFO  com.netflix.archaius.guice.ConfigurationInjectingListener  - Initializing ConfigurationInjectingListener
1250 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
1250 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
1260 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
1260 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
1265 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
1265 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
.....
.....
Caused by: java.lang.NullPointerException
        at com.netflix.dyno.connectionpool.impl.HostsUpdater.refreshHosts(HostsUpdater.java:111)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:486)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4292)
        ... 82 more
....
Caused by: java.lang.RuntimeException (same stack trace as error #37)
50 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)

```
please help me ==!

**Comment by suanyi001** [comment]
@v1r3n please help

**Comment by saidatta** [comment]
I believe you dont need to enter multiple quorom ports. Did you try pointing it to a single one?

**Comment by suanyi001** [comment]
> I believe you dont need to enter multiple quorom ports. Did you try pointing it to a single one?

which post?Dynomite or conductor.

**Comment by ndidi-did** [comment]
It seems as if it's this inside TokenMapSupplier.java:

```
    @Override
    public TokenMapSupplier get() {
        return new TokenMapSupplier() {

            // FIXME This isn't particularly safe, but it is equivalent to the existing code.
            // FIXME It seems like we should be supply tokens for more than one host?
            HostToken token = new HostToken(1L, Lists.newArrayList(hostSupplier.getHosts()).get(0));

            @Override
            public List<HostToken> getTokens(Set<Host> activeHosts) {
                return Arrays.asList(token);
            }

            @Override
            public HostToken getTokenForHost(Host host, Set<Host> activeHosts) {
                return token;
            }
        };
    }
```
I've tested by adding a second token when having more than 1 host provided and it seems to be working.

**Comment by suanyi001** [comment]
> It seems as if it's this inside TokenMapSupplier.java:
> 
> ```
>     @Override
>     public TokenMapSupplier get() {
>         return new TokenMapSupplier() {
> 
>             // FIXME This isn't particularly safe, but it is equivalent to the existing code.
>             // FIXME It seems like we should be supply tokens for more than one host?
>             HostToken token = new HostToken(1L, Lists.newArrayList(hostSupplier.getHosts()).get(0));
> 
>             @Override
>             public List<HostToken> getTokens(Set<Host> activeHosts) {
>                 return Arrays.asList(token);
>             }
> 
>             @Override
>             public HostToken getTokenForHost(Host host, Set<Host> activeHosts) {
>                 return token;
>             }
>         };
>     }
> ```
> I've tested by adding a second token when having more than 1 host provided and it seems to be working.

Thanks,it`s worked!
