### ISSUE TITLE
Deploying conductor to PCF with AWS elasticache Redis

### ISSUE THREAD

**Issue by sivacham** [Netflix/conductor#909]
HI,

I am trying to deploy the Conductor 1.12 Version in PCF and facing issues in using AWS elasticache Redis as a service with the Conductor Server. The redis Service in the environment variable is as follows
`
"aws-elasticache-redis": [
        {
          "name": "c2mConductorRedis",
          "instance_name": "c2mConductorRedis",
          "binding_name": null,
          "credentials": {
            "host": "master.cf-**********.******.apse2.cache.amazonaws.com",
            "name": "cf-**********",
            "password": "*******-****************************************",
            "port": 6379
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "aws-elasticache-redis",
          "provider": null,
          "plan": "small",
          "tags": [
            "elasticache",
            "redis"
          ]
        }
      ],
`
I have tried multiple options but I don't see any configuration for the host with password but I am trying something as below
`
db=dynomite
workflow.dynomite.cluster.hosts=rediss://:password@master.cf-***************.******.apse2.cache.amazonaws.com:6379:ap-southeast-2
workflow.dynomite.connection.maxConnsPerHost=31
queues.dynomite.nonQuorum.port=6379
`	  
But I am not able to establish the connection and start the server
`
2018-12-14T11:15:55.025+05:30 [APP/PROC/WEB/0] [OUT] 1700 [localhost-startStop-1] WARN com.netflix.dyno.jedis.JedisConnectionFactory - Caught JedisConnectionException: java.net.SocketException: Connection reset
2018-12-14T11:15:55.032+05:30 [APP/PROC/WEB/0] [ERR] com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=master.cf-*****************.91mvq1.apse2.cache.amazonaws.com, ipAddress=null, port=6379, rack: ap-southeast-2, datacenter: ap-southeast-, status: Up, hashtag=null], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
2018-12-14T11:15:55.032+05:30 [APP/PROC/WEB/0] [OUT] 1708 [localhost-startStop-1] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl - Failed to close connection for host: Host [hostname=master.cf-*************.******.apse2.cache.amazonaws.com, ipAddress=null, port=6379, rack: ap-southeast-2, datacenter: ap-southeast-, status: Up, hashtag=null] java.net.SocketException: Broken pipe (Write failed)
2018-12-14T11:15:55.032+05:30 [APP/PROC/WEB/0] [OUT] 1708 [localhost-startStop-1] WARN com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl - Received FatalConnectionException; closing connection {port=6379, host=master.cf-*****************.91mvq1.apse2.cache.amazonaws.com} to host Host [hostname=master.cf-*****************.91mvq1.apse2.cache.amazonaws.com, ipAddress=null, port=6379, rack: ap-southeast-2, datacenter: ap-southeast-, status: Up, hashtag=null]
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.netflix.conductor.dao.dynomite.RedisMetadataDAO$$FastClassByGuice$$1f364347.newInstance(<generated>)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.<init>(RedisMetadataDAO.java:65)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.refreshTaskDefs(RedisMetadataDAO.java:95)
2018-12-14T11:15:55.033+05:30 [APP/PROC/WEB/0] [ERR] at com.netflix.conductor.dao.dynomite.RedisMetadataDAO.getAllTaskDefs(RedisMetadataDAO.java:131)
`

`
ConnectionPoolConfigurationImpl connectionPoolConfiguration = new ConnectionPoolConfigurationImpl(dynoClusterName)
					.withTokenSupplier(getTokenMapSupplier(dynoHosts))
					.setLocalRack(conductorConfig.getAvailabilityZone())
					.setLocalDataCenter(conductorConfig.getRegion())
					.setSocketTimeout(50000)
					.setConnectTimeout(50000)
					.setMaxConnsPerHost(conductorConfig.getIntProperty("workflow.dynomite.connection.maxConnsPerHost", 10));

			jedis = new DynoJedisClient.Builder()
					.withHostSupplier(hostSupplier)
					.withApplicationName(conductorConfig.getAppId())
					.withDynomiteClusterName(dynoClusterName)
					.withCPConfig(connectionPoolConfiguration)
					.build();
`
I see this code is creating the connectionfactory but i dont see any settings for SSL or password enabling in the Jedis jar or Dyno core Jar
Help wanted to resolve the issue ? I am wondering if I am missing any configuration

**Comment by sivacham** [comment]
I have done some changes as per the post by DavidWadden [https://github.com/davidwadden/conductor/commits/pws](url) by adding the password as well as using 1.6.5 version  of dyno-core and dyno-jedis.

But I am facing a new issue now

`2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] 540 [pool-3-thread-1] INFO com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl - Failed to init host pool for host: Host [hostname=master.cf-*****************.******.apse2.cache.amazonaws.com, ipAddress=null, port=6379, rack: ap-southeast-2, datacenter: ap-southeast-, status: Up, hashtag=null, password=masked]
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] com.netflix.dyno.connectionpool.exception.DynoConnectException: DynoConnectException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down, hashtag=null, password=null], latency=0(0), attempts=0]Unable to make ANY successful connections to host Host [hostname=master.cf-*****************.******.apse2.cache.amazonaws.com, ipAddress=null, port=6379, rack: ap-southeast-2, datacenter: ap-southeast-, status: Up, hashtag=null, password=masked]
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl.primeConnections(HostConnectionPoolImpl.java:173)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.addHost(ConnectionPoolImpl.java:176)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl$2.call(ConnectionPoolImpl.java:504)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl$2.call(ConnectionPoolImpl.java:500)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-12-19T15:39:18.827+05:30 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748)
2018-12-19T15:39:18.833+05:30 [APP/PROC/WEB/0] [OUT] 547 [localhost-startStop-1] INFO com.netflix.dyno.connectionpool.TokenPoolTopology - Adding Host to TopologyHost [hostname=master.cf-*****************.******.apse2.cache.amazonaws.com, ipAddress=null, port=6379, rack: ap-southeast-2, datacenter: ap-southeast-, status: Up, hashtag=null, password=masked]`

I have also tried setting the following property while forming the connection in ConductorServer.java
`connectionPoolConfiguration.setLoadBalancingStrategy(ConnectionPoolConfiguration.LoadBalancingStrategy.RoundRobin);`
`
Any Idea why the issue is coming?

**Comment by sivacham** [comment]
Issue resolved after using Jedispool to form the connection . Now the Conductor war has deployed on PCF but still not able to get the Swagger page

The tomcat version is Apache Tomcat/8.5.37

```
2018-12-24T11:41:18.446+05:30 [APP/PROC/WEB/0] [OUT] WARNING: Return type java.util.Map<java.lang.String, ?> of method public java.util.Map<java.lang.String, ?> com.netflix.conductor.server.resources.EventResource.getEventQueues(boolean) is not resolvable to a concrete type
2018-12-24T11:41:18.459+05:30 [APP/PROC/WEB/0] [OUT] 5521 [localhost-startStop-1] INFO org.eclipse.jetty.util.log - Logging initialized @11206ms
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] [CONTAINER] lina.core.ContainerBase.[Catalina].[localhost].[/] SEVERE Exception starting filter [guiceFilter]
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] java.lang.IllegalArgumentException: The servletContext org.apache.catalina.core.ApplicationContextFacade@8be51f4 org.apache.catalina.core.ApplicationContextFacade is not org.eclipse.jetty.server.handler.ContextHandler$Context
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] at org.eclipse.jetty.servlet.DefaultServlet.initContextHandler(DefaultServlet.java:342)
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] at org.eclipse.jetty.servlet.DefaultServlet.init(DefaultServlet.java:185)
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] at javax.servlet.GenericServlet.init(GenericServlet.java:158)
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
2018-12-24T11:41:18.483+05:30 [APP/PROC/WEB/0] [OUT] at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
```

Saw someone had a similar issue and used GuiceContainer instead of the DefaultServlet but got he Mime type error

[(https://github.com/Netflix/conductor/pull/792)]

**Comment by kishorebanala** [comment]
Closing this issue as there is no activity for a while. Please feel free to reopen if you still have questions or concerns.
