### ISSUE TITLE
Trouble using dynomite/redis with Elasticsearch

### ISSUE THREAD

**Issue by ndidi-did** [Netflix/conductor#912]
I've almost got conductor up and running running a local one node dynomite/redis instance:

Redis startup: 

> ./redis-server --port 22122

Dynomite config:

```
dyn_o_mite:
  listen: 127.0.0.1:8102
  dyn_listen: 127.0.0.1:8101
  tokens: '101134286'
  servers:
  - 127.0.0.1:22122:1
  data_store: 0
  mbuf_size: 16384
  max_msgs: 300000
```

conductor server.properties

```
#Dynomite Cluster details.
#format is host:port:rack separated by semicolon

workflow.dynomite.cluster.hosts=127.0.0.1:8102:us-east-1a
workflow.dynomite.cluster.name=dyn_o_mite
#namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

db=dynomite

#namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor

#no. of threads allocated to dyno-queues
queues.dynomite.threads=10
#non-quorum port used to connect to local redis.  Used by dyno-queues
queues.dynomite.nonQuorum.port=22122

#Transport address to elasticsearch
#workflow.elasticsearch.url=127.0.0.1:9300

#Name of the elasticsearch cluster
#workflow.elasticsearch.index.name=conductor

#Elasticsearch major release version.

workflow.elasticsearch.version=5

# For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property.
EC2_AVAILABILITY_ZONE=us-east-1
#workflow.elasticsearch.instanceType=EXTERNAL
```

Stacktrace:

```

1002 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: HTTP
1460 [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
1462 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: JSON_JQ_TRANSFORM
2862 [main] DEBUG com.netflix.archaius.readers.PropertiesConfigReader  - Attempting to load : file:/Users/jorge/Programming/conductor/application.properties
2870 [main] DEBUG com.netflix.archaius.readers.PropertiesConfigReader  - Unable to load configuration file file:/Users/jorge/Programming/conductor/application.properties. /Users/jorge/Programming/conductor/application.properties (No such file or directory)
2872 [main] DEBUG com.netflix.archaius.DefaultConfigLoader  - Loaded application 
2872 [main] INFO  com.netflix.archaius.guice.ConfigurationInjectingListener  - Initializing ConfigurationInjectingListener
3204 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
3204 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
3282 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null]
3283 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null], with conns:10
3442 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 10 of 10 to Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null]
3471 [main] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Adding Host to TopologyHost [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null]
3477 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - registered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
3485 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
3485 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
3486 [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null]
3486 [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null], with conns:10
3491 [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 10 of 10 to Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null]
3492 [main] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Adding Host to TopologyHost [hostname=127.0.0.1, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up, hashtag=null]
3492 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole has already been registered !
3514 [main] INFO  com.netflix.conductor.dyno.RedisQueuesProvider  - DynoQueueDAO initialized with prefix conductor_queues.test!
3680 [main] DEBUG com.netflix.conductor.dao.dynomite.RedisMetadataDAO  - Refreshed task defs 0
4474 [pool-2-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.health.ConnectionPoolHealthTracker  - Running, pending pools size: 0
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
4496 [pool-5-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.health.ConnectionPoolHealthTracker  - Running, pending pools size: 0
8015 [main] INFO  com.netflix.conductor.core.events.EventProcessor  - Event Processing is ENABLED. executorThreadCount set to 2
8018 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - System Task Worker initialized with 10 threads and a callback time of 30 seconds and queue size: 100 with pollCount: 10 and poll interval: 50
8019 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: SUB_WORKFLOW
8019 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: WAIT
8019 [Thread-3] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Started listening for system task: HTTP
8019 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: EVENT
9034 [pool-13-thread-1] ERROR com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Error executing system task:HTTP
java.lang.IllegalArgumentException: value cannot be empty
	at com.netflix.servo.util.Preconditions.checkArgument(Preconditions.java:63)
	at com.netflix.servo.tag.BasicTag.checkNotEmpty(BasicTag.java:41)
	at com.netflix.servo.tag.BasicTag.<init>(BasicTag.java:33)
	at com.netflix.servo.tag.Tags.newTag(Tags.java:63)
	at com.netflix.servo.monitor.MonitorConfig$Builder.withTag(MonitorConfig.java:64)
	at com.netflix.dyno.queues.redis.QueueMonitor.create(QueueMonitor.java:115)
	at com.netflix.dyno.queues.redis.QueueMonitor.<init>(QueueMonitor.java:81)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.<init>(RedisDynoQueue.java:119)
	at com.netflix.dyno.queues.redis.RedisQueues.get(RedisQueues.java:104)
	at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:153)
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.pollAndExecute(SystemTaskWorkerCoordinator.java:142)
	at com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator.lambda$listen$0(SystemTaskWorkerCoordinator.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
I have tried ES locally 2.x, 5.x, 6.x, as well as in memory but I keep getting this error. I must be missing something, but I can't seem to see what it might be. Any advice?

Edit: I've also just made sure that I can see activity when going through redis-cli and using the monitor functionality:

from the redis-cli:
```
test-MBP:src test$ ./redis-cli -h 127.0.0.1 -p 8102
127.0.0.1:8102> set foo bar
OK
127.0.0.1:8102> 
```

from the monitor tool:

```
test-MBP:src test$ ./redis-cli -h 127.0.0.1 -p 22122 monitor
OK
1545209625.224249 [0 127.0.0.1:53598] "set" "foo" "bar"
```

But still no luck when trying to connect via conductor, it just loops through and keeps logging out the above error:
```
26124 [pool-13-thread-1] ERROR com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Error executing system task:HTTP
java.lang.IllegalArgumentException: value cannot be empty
```

**Comment by ndidi-did** [comment]
Looks like removing the EC2_availability flag did the trick -- I ended up with:

```
#Dynomite Cluster details.
#format is host:port:rack separated by semicolon

workflow.dynomite.cluster.hosts=127.0.0.1:8102:us-east-1a

db=dynomite

# Dynomite cluster name
workflow.dynomite.cluster.name=dyno_cluster_name

# Maximum connections to redis/dynomite
workflow.dynomite.connection.maxConnsPerHost=31

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
queues.dynomite.nonQuorum.port=22122

# Transport address to elasticsearch
workflow.elasticsearch.url=localhost:9300

# Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor
```
