### ISSUE TITLE
Unable to start server with redis_cluster 

### ISSUE THREAD

**Issue by mudit3774** [Netflix/conductor#917]
We are trying to move from db=redis to db=redis_cluster and we are facing issues with starting the server. We are using conductor 2.x.x 

We are able to telnet to the elastic cache cluster and also redis-cli is working from the box.

This is the config we have :

```
db=redis_cluster
#Dynomite Cluster details.
#format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=<config-endpoint>:6379:us-east-1c

#namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

#namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor

#no. of threads allocated to dyno-queues
queues.dynomite.threads=75

workflow.dynomite.connection.maxConnsPerHost=75

workflow.system.task.worker.callback.seconds=30
workflow.system.task.worker.poll.interval=10
workflow.system.task.worker.thread.count=80
workflow.system.task.worker.poll.count=80
workflow.system.task.worker.queue.size=800
#non-quorum port used to connect to local redis.  Used by dyno-queues
queues.dynomite.nonQuorum.port=6379

#Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

#Elasticsearch major release version.
workflow.elasticsearch.version=5

# For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property.
EC2_AVAILABILITY_ZONE=us-east-1c
EC2_REGION=us-east-1

port=8080

#Sweeper
decider.sweep.disable=true
decider.sweep.frequency.seconds=6000

workflow.elasticsearch.instanceType=EXTERNAL
workflow.elasticsearch.url=http://<aws-es-endpoint>:80
```

We have enabled debug logging but this is the only log we are getting : 

```
2018-12-22 10:26:45 INFO  ModulesProvider:90 - Starting conductor server using redis_cluster.
2018-12-22 10:26:45 INFO  ModulesProvider:113 - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:38)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:111)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:51)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
2018-12-22 10:26:46 INFO  SystemTaskWorkerCoordinator:103 - Adding the queue for system task: HTTP
2018-12-22 10:26:46 INFO  HttpTask:89 - HttpTask initialized...
2018-12-22 10:26:55 INFO  ModulesProvider:90 - Starting conductor server using redis_cluster.
2018-12-22 10:26:55 INFO  ModulesProvider:113 - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:38)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:111)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:51)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
2018-12-22 10:26:55 INFO  SystemTaskWorkerCoordinator:103 - Adding the queue for system task: HTTP
2018-12-22 10:26:56 INFO  HttpTask:89 - HttpTask initialized...
2018-12-22 10:27:05 INFO  ModulesProvider:90 - Starting conductor server using redis_cluster.
2018-12-22 10:27:05 INFO  ModulesProvider:113 - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:38)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:111)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:51)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
2018-12-22 10:27:05 INFO  SystemTaskWorkerCoordinator:103 - Adding the queue for system task: HTTP
2018-12-22 10:27:05 INFO  HttpTask:89 - HttpTask initialized...
```

We did upgrade the redis engine to 5.0.0 and boxes to cache.r5.2x.large. Also, we are running a 9 node cluster with 3 shards. 

Any help would be appreciated.

@cyzhao @clari-akhilesh @v1r3n

**Comment by clari-akhilesh** [comment]
We haven't tested redis_cluster with the 2.x.x version. We're currently running 1.8.6 version in Production. Nothing stands out in your config that could be incorrect. Can you try with the following parameter instead of the one you have:
`workflow.dynomite.cluster.hosts=<config-endpoint>:6379:c`
Let me know if that works @mudit3774

**Comment by mudit3774** [comment]
@clari-akhilesh Thank you for your reply. I tried the suggested setting and it is still getting stuck with the same log and restarting again. 

We will try to isolate the issue by bringing the redis version down and if this is still happening.

**Comment by mudit3774** [comment]
Thanks @clari-akhilesh for the reply. I tried with 3.2.4 redis engine version and it is still stuck. There is no error log, it just tries to start the server again, we get the above log in a loop with each iterations 'n' seconds apart.

**Comment by kishorebanala** [comment]
@mudit3774 Closing this issue as there is no activity for a while. Please feel free to reopen if you still have questions or concerns.
