### ISSUE TITLE
gulp watch error

### ISSUE THREAD

**Issue by zhangzhefang-github** [Netflix/conductor#998]
[22:47:49] Failed to load external module @babel/register
[22:47:49] Failed to load external module babel-register
[22:47:49] Failed to load external module babel-core/register
[22:47:49] Failed to load external module babel/register
/apps/conductor-master/ui/gulpfile.babel.js:2
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at execute (/apps/node-v4.6.0-linux-x64/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/apps/node-v4.6.0-linux-x64/lib/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/apps/node-v4.6.0-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)

**Comment by iamthadiyan** [comment]
If you haven't already tried, do `$ npm install -g gulp`, then `$ npm install gulp`. After that `$ gulp watch` will download and set all dependencies.

**Comment by kishorebanala** [comment]
@zhangzhefang-github Please follow the instructions above to resolve this issue. Make sure to use compatible versions when building the client. I.e compatible node version, gulp version etc. Please feel free to reopen this issue if you still have questions.
